### ISSUE TITLE
Add support to set message size on azure_rm_servicebusqueue and azure_rm_servicebustopic

### ISSUE THREAD

**Issue by madmalkav** [ansible/ansible_collections_azure#1003]
##### SUMMARY
azure_rm_servicebusqueue and azure_rm_servicebustopic doesn't allow to set message size

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_servicebusqueue

##### ADDITIONAL INFORMATION
Premium namespaces allow to set message sizes, but Ansible doesn't support this.

**Comment by madmalkav** [comment]
By the way this probably should be done too for topics and subscriptions.

**Comment by madmalkav** [comment]
I barely have any understading of coding, but seems like the API ansible uses already supports this, with **max_message_size_in_kilobytes** for both [queues](https://learn.microsoft.com/en-us/python/api/azure-mgmt-servicebus/azure.mgmt.servicebus.v2022_01_01_preview.models.sbqueue?view=azure-python)  and [topics](https://learn.microsoft.com/en-us/python/api/azure-mgmt-servicebus/azure.mgmt.servicebus.v2022_01_01_preview.models.sbtopic?view=azure-python)

**Comment by madmalkav** [comment]
Happy New Year everyone!

Sorry to be annoying but is there any chance we get an answer about this ticket being accepted or not?

**Comment by energgumeno** [comment]
+1

**Comment by Fred-sun** [comment]
@madmalkav @energgumeno Added in #1092

**Comment by madmalkav** [comment]
Thanks a lot!
