### ISSUE TITLE
azure_rm_servicebustopicsubscription doesn't allow to set filters

### ISSUE THREAD

**Issue by madmalkav** [ansible/ansible_collections_azure#1008]
##### SUMMARY
azure_rm_servicebustopicsubscription doesn't allow to set filters

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_servicebustopicsubscription

##### ADDITIONAL INFORMATION

Subscriptions support two type of filters: correlation and SQL syntax based. Ansible doesn't allow to set either, even if it supports parameters related to filters behavior ( dead_lettering_on_filter_evaluation_exceptions ). 
On Azure Portal, these filters are managed as part of a subscription, but at API level, SBSubscription doesn't seems to have more options linked to filters other than SBSubscription.DeadLetteringOnFilterEvaluationExceptions 

Azure Management API have [CorrelationFilter](https://learn.microsoft.com/en-us/python/api/azure-mgmt-servicebus/azure.mgmt.servicebus.v2022_01_01_preview.models.correlationfilter?view=azure-python) and [SqlFilter](https://learn.microsoft.com/en-us/python/api/azure-mgmt-servicebus/azure.mgmt.servicebus.v2022_01_01_preview.models.sqlfilter?view=azure-python) these are probably the APIs in charge of the filters, but as someone that is not familiar to coding I fail to see how to link those to a subscription. None of them seems to be currently implemented in azcollection.

In any case, the goal should be we can easily assign filters to a subscription in Ansible like it can easily be done with the GUI or the [AZ CLI](https://learn.microsoft.com/en-us/cli/azure/servicebus/topic/subscription/rule?view=azure-cli-latest)

**Comment by Fred-sun** [comment]
@madmalkav Thanks for your reportig! "azure_rm_servicebustopicsubscritpion" not support "these filter" , It is support in "Azure Service Bus Rule", not the same module! Thank you very much!

**Comment by madmalkav** [comment]
Thanks for your answer @Fred-sun . If I understand correctly this will be covered by a new module in the collection. Do you want me to rename the ticket to better reflect that? Something like "Implement Azure Service Bus Rule so filters can be set on Service Bus Subscriptions" ?

**Comment by Fred-sun** [comment]
@madmalkav Yes, this feature should be included in the new module, it is recommended to close the Issue and recreate a requirement to add a new module. Thanks!

**Comment by madmalkav** [comment]
Created new ticket as per @Fred-sun instructions, closing this one.
