### ISSUE TITLE
Azure batch pool

### ISSUE THREAD

**Issue by ossonts** [ansible/ansible_collections_azure#1019]
##### SUMMARY

Add/create a batch pool

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Ansible enables the creation of a batch account, but not the compute resources (pool)

##### ADDITIONAL INFORMATION

Here are the options I would like
```
pools {
          myPoolName{
            vmType = 'standard_d15_v2'
            vmCount = 1
            maxVmCount = 1
            privileged = true 
          }

```

**Comment by Fred-sun** [comment]
@ossonts Thank you for submitting the question, we will complete the addition as soon as possible!
