### ISSUE TITLE
Can't use Azure collection   {{ Maybe the ansible-runner in the EE is outdated as it claims?)

### ISSUE THREAD

**Issue by tux1980** [ansible/ansible_collections_azure#1022]
##### SUMMARY
Hi I do have an Issue with using the Ansible Azure Collection. I Updated them already on the last updated version + updating ansible-runner in the ee in question, build the EE also new   -but always same result. Did also try different EE's with different Base Images - didn't help. Creating an Azure Ressource Group for example always resulted in the weird error I attached. I attached two pastbin URLS with two examples. 
Thanks a lot!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
I tried out several Azure Modules like "azure_rm_resourcegroup" or "azure_rm_securitygroup" - always the same error message.

##### ANSIBLE VERSION
core 2.13.10
But tried different ee with different versions and different base images, I'm always getting that message.
My EE (Among others): quay.io/scottharwell/cloud-ee:latest

##### COLLECTION VERSION
azure.azcollection Version 1.13.0

##### OS / ENVIRONMENT
AAP 2.2 is running with the operator-based method on Openshift 4.11

##### ACTUAL RESULTS
See image attached, thats all I have unfortunate..

**Comment by tux1980** [comment]
Azure Collection Error 1: (Sync Inventory) 
[https://pastebin.com/F9RkzSGu](url)

Azure Collection Error 2: (Deploy WIN2022 Server) 
[https://pastebin.com/weERBEV8](url)

**Comment by Fred-sun** [comment]
@tux1980 Can you share how to reproduce this problem? This will help solve the current problem!

**Comment by Fred-sun** [comment]
> Azure Collection Error 1: (Sync Inventory) [https://pastebin.com/F9RkzSGu](url)
> 
> Azure Collection Error 2: (Deploy WIN2022 Server) [https://pastebin.com/weERBEV8](url)

@tux1980 Could you share more info? There is no logs in both urls. Thank you very much!

**Comment by tux1980** [comment]
Hi, these we can close, no issue anymore. But Thanks
Br
