### ISSUE TITLE
KeyVault Network Rules

### ISSUE THREAD

**Issue by rasselmaliyekkal** [ansible/ansible_collections_azure#1026]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

I cannot find a network rule in keyvault mode, I'm stuck with deployment due to org level policy to restrict public access of keyvault.

cant find network rule property in this module:
https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_keyvault_module.html#ansible-collections-azure-azcollection-azure-rm-keyvault-module

**Comment by Fred-sun** [comment]
@rasselmaliyekkal You mean we need to add a module in order to add network rules to the keyvault module! right?

**Comment by rasselmaliyekkal** [comment]
@Fred-sun - Yes

**Comment by Fred-sun** [comment]
@rasselmaliyekkal I'm sorry for replying you so late. The SDK does not support the creation of 'keyvault Network rules' for the time being. It cannot be added once it is supported. We will consider adding this support! Thanks!

**Comment by michie1** [comment]
@Fred-sun What do you mean with "It cannot be added once it is supported."? Do you mean "It can be added"?
How to check if the SDK already supports it now we are a couple of years further?

**Comment by Fred-sun** [comment]
@michie1 Yes, this problem has been held for some time. I will check whether the latest SDK supports it and add it as soon as possible. Thank you!

**Comment by Fred-sun** [comment]
@michie1 @rasselmaliyekkal Added in #1738
