### ISSUE TITLE
Inventory plugin does not work with Ansible 2.10 (ansible-base)

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible_collections_azure#103]
##### SUMMARY
The inventory plugin works with Ansible 2.9, but does not work with current `devel` branch, which becomes Ansible 2.10 at some point.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/inventory

##### ANSIBLE VERSION
```paste below
ansible-inventory 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
defaults

##### OS / ENVIRONMENT
mac / control machine

##### STEPS TO REPRODUCE
Call `ansible-inventory` and point it to your inventory file location.

##### EXPECTED RESULTS
works same in Ansible 2.9 and Ansible 2.10.

##### ACTUAL RESULTS

```
[WARNING]:  * Failed to parse /tmp/awx_135_3xm2x23k/azure_rm.yml with auto
plugin: unknown doc_fragment(s) in file /var/lib/awx/vendor/inventory_collectio
ns/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py: azure
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 287, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/auto.py", line 50, in parse
    plugin = inventory_loader.get(plugin_name)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 553, in get
    self._load_config_defs(name, self._module_cache[path], path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 290, in _load_config_defs
    add_fragments(dstring, path, fragment_loader=fragment_loader)
  File "/usr/lib/python2.7/site-packages/ansible/utils/plugin_docs.py", line 116, in add_fragments
    raise AnsibleError('unknown doc_fragment(s) in file {0}: {1}'.format(filename, to_native(', '.join(unknown_fragments))))
```

This is caused by:

https://github.com/ansible-collections/azure/blob/40fac2381edb280d9f864f43dca1e39476eea78e/plugins/inventory/azure_rm.py#L11-L12

You can reference the FQCN doc fragment, that is `azure.azcollection.azure`, but `azure` was removed with the removal of content from Ansible core.

This isn't the only collection hit by this, it's a thing going around. I'm using this, so you hear about it from me.

**Comment by Fred-sun** [comment]
PR has been merge. So close it!
