### ISSUE TITLE
azure_rm_virtualmachine does not support encryption-at-host

### ISSUE THREAD

**Issue by rafajot1** [ansible/ansible_collections_azure#1031]
##### SUMMARY
As of now (v1.14.0) azure_rm_virtualmachine doesn't seem to support encryption-at-host

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine and possibly azure_rm_virtualmachinescaleset

**Comment by Fred-sun** [comment]
@rafajot1  Already add to azure_rm_virtualmachine, Now work in azure_rm_virtualmachinescaleset! Thank  you very much!

**Comment by Fred-sun** [comment]
azure_rm_virtualmachinescalset.py added 'security_profile' in #1033

**Comment by rafajot1** [comment]
It seems to work fine. Thank you!

**Comment by rafajot1** [comment]
Hey, is there any rough estimate when this could be merged?

**Comment by Fred-sun** [comment]
@rafajot1 Is being pushed to merge. Thanks!

**Comment by xuzhang3** [comment]
New feature available in #1033
