### ISSUE TITLE
Please allow me to generate the inventory_hostname

### ISSUE THREAD

**Issue by cognifloyd** [ansible/ansible_collections_azure#104]
##### SUMMARY
I would like to define my own formula for generating the inventory_hostname. As Azure does not allow renaming VMs, I need to use a tag to get our names for the VM. I want to use our standardize tag name so that I can add vars in `host_vars/` as required.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm inventory plugin

##### ADDITIONAL INFORMATION
This is a continuation of https://github.com/ansible/ansible/issues/54065 which only requested the ability to configure the legacy behavior.

I want to define my own inventory_hostname as mentiond here:
https://github.com/ansible-collections/azure/blob/4467d13b459dc171857e3d7956a3f1fa6139d379/plugins/inventory/azure_rm.py#L366-L368

For reference, this is the section that currently defines the legacy/unique hostname definition:
https://github.com/ansible-collections/azure/blob/4467d13b459dc171857e3d7956a3f1fa6139d379/plugins/inventory/azure_rm.py#L504-L508

In both cases, this uses `vm_model['name']` but I explicitly do NOT want to use `vm_model['name']` because Azure doesn't let me rename VMs.

**Comment by cognifloyd** [comment]
Maybe one way to do this, would be to allow adding `inventory_hostname` to `hostvar_expressions`:
https://github.com/ansible-collections/azure/blob/4467d13b459dc171857e3d7956a3f1fa6139d379/plugins/inventory/azure_rm.py#L328
And do something like:
```python
compose_inventory_hostname = constructable_config_compose.pop("inventory_hostname")
```
And pass that to get_hostname here:
https://github.com/ansible-collections/azure/blob/4467d13b459dc171857e3d7956a3f1fa6139d379/plugins/inventory/azure_rm.py#L333
```python
inventory_hostname = self._get_hostname(h, compose_inventory_hostname, strict=constructable_config_strict)
```

Then _get_hostname would change to something like this:
```python
def _get_hostname(self, host, compose=None, strict=False):
    if not compose:
        return host.default_inventory_hostname
    try:
        return self._compose(compose, h.hostvars)
    except Exception as e:
        if strict:
            raise AnsibleParserError("Could not generate inventory_hostname for host %s from hostvar_expressions.inventory_hostname: %s" % (host.default_inventory_hostname, to_native(e)))
        return host.default_inventory_hostname
```

Any comments on doing it like this? Or would using something other than `hostvar_expressions` be preferrable?

**Comment by mwinfie** [comment]
Can a maintainer review this? I think this would solve a similar issue we are having where we want to be able to pull in hosts by ip address instead of the vm name.

**Comment by mwinfie** [comment]
Can a maintainer review this? I think this would solve a similar issue we are having where we want to be able to pull in hosts by ip address instead of the vm name.

**Comment by Fred-sun** [comment]
> Can a maintainer review this? I think this would solve a similar issue we are having where we want to be able to pull in hosts by ip address instead of the vm name


This PR has been reviewed and will be merged soon. Thank you!
