### ISSUE TITLE
When azure VM was created from the image, the OS disks were set to Standard disk, but data disk is not inheriting the storage type

### ISSUE THREAD

**Issue by tophercamino** [ansible/ansible_collections_azure#1051]
Hello All,

Need some help on the error we encounter upon commissioning of Azure VM via ansible. Below is the ansible playbook that we used:

- hosts: localhost
  connection: local
  collections:
   - azure.azcollection
  tasks:
      - name: Azure deploy VirtualMachine
        azure_rm_virtualmachine:
          admin_username: "cohen"
          admin_password: "Password123!"
          resource_group: "Cohen_739"
          cert_validation_mode: ignore
          location: "southeastasia"
          name: "cohenansible6"
          managed_disk_type: "StandardSSD_LRS"
          state: present
          started: yes
          vm_size: "Standard_D4s_v4"
          public_ip_allocation_method: Disabled
          os_type: "Windows"
          virtual_network_name: "Cohen_739-vnet"
          subnet_name: "default"
          image:
            id: "/subscriptions/e9d3aa6a-bd19-4491-8a76-6f51b65c21ab/resourcegroups/Cohen_739/providers/Microsoft.Compute/galleries/cohengallery/images/cohenimagedef/versions/1.0.0"
          data_disks:
            - lun: 0
              disk_size_gb: 4
              managed_disk_type: "StandardSSD_LRS"
            - lun: 1
              disk_size_gb: 4
              managed_disk_type: "StandardSSD_LRS"
            - lun: 2
              disk_size_gb: 4
              managed_disk_type: "StandardSSD_LRS"

Below is the error we have recieved.

TASK [Azure deploy VirtualMachine] ****************************************************************************************************************************************************************************************************************************************

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine cohenansible6 - (InvalidParameter) Cannot specify user image overrides for a disk already defined in the specified image reference.\nCode: InvalidParameter\nMessage: Cannot specify user image overrides for a disk already defined in the specified image reference.\nTarget: storageProfile"}

When we do not specify the data disk type, the data disk type should inherit OS disk type. However, when we checked from the backend, the data disk type was specified to "Premium_LRS" in the request coming from Ansible.

- hosts: localhost
  connection: local
  collections:
   - azure.azcollection
  tasks:
      - name: Azure deploy VirtualMachine
        azure_rm_virtualmachine:
          admin_username: "cohen"
          admin_password: "Password123!"
          resource_group: "Cohen_739"
          cert_validation_mode: ignore
          location: "southeastasia"
          name: "cohenansible3"
          managed_disk_type: "StandardSSD_LRS"
          state: present
          started: yes
          vm_size: "Standard_D4s_v4"
          public_ip_allocation_method: Disabled
          os_type: "Windows"
          virtual_network_name: "Cohen_739-vnet"
          subnet_name: "default"
          image:
            id: "/subscriptions/e9d3aa6a-bd19-4491-8a76-6f51b65c21ab/resourcegroups/Cohen_739/providers/Microsoft.Compute/galleries/cohengallery/images/cohenimagedef/versions/1.0.0"

See snippet below.

{
  "name": "cohenansible2_lun_2_4_0ba83bad199a473f86ab37198af1cd1f",
  "id": "/subscriptions/e9d3aa6a-bd19-4491-8a76-6f51b65c21ab/resourceGroups/COHEN_739/providers/Microsoft.Compute/disks/cohenansible2_lun_2_4_0ba83bad199a473f86ab37198af1cd1f",
  "type": "Microsoft.Compute/disks",
  "location": "southeastasia",
  "tags": {
    "_own_nsg_": "cohenansible201",
    "_own_nic_": "cohenansible201"
  },
  "managedBy": "/subscriptions/e9d3aa6a-bd19-4491-8a76-6f51b65c21ab/resourceGroups/Cohen_739/providers/Microsoft.Compute/virtualMachines/cohenansible2",
  "sku": {
    "name": "Premium_LRS",
    "tier": "Premium"
  },
  "properties": {
    "creationData": {
      "createOption": "FromImage",
      "imageReference": {
        "id": "/subscriptions/e9d3aa6a-bd19-4491-8a76-6f51b65c21ab/resourceGroups/Cohen_739/providers/Microsoft.Compute/galleries/cohengallery/images/cohenimagedef/versions/1.0.2",
        "lun": 2
      }
    },
    "diskSizeGB": 4,
    "diskIOPSReadWrite": 120,
    "diskMBpsReadWrite": 25,
    "encryption": {
      "type": "EncryptionAtRestWithPlatformKey"
    },
    "publicNetworkAccess": "Enabled",
    "diskState": "Attached",
    "uniqueId": "0ba83bad-199a-473f-86ab-37198af1cd1f"
  }
}

**Comment by Fred-sun** [comment]
@tophercamino Thanks for your reporting! I will check this issue as soon as possible!

**Comment by jeethendrad** [comment]
Is there any update on this please?

**Comment by ZoneKKL** [comment]
Hi team, may we get any update?

**Comment by tophercamino** [comment]
Hello @Fred-sun , 

I would just like to follow up if we have an update on this? Thanks

**Comment by Fred-sun** [comment]
@tophercamino @ZoneKKL Sorry for the late reply. When creating VM through Image, it will create a new disk according to the configuration of the data disk that was previously mirrored. The disk type cannot be changed for the time being. Thanks!

**Comment by ZoneKKL** [comment]
@Fred-sun But actually, when we create VM via ansible, the data disk type is set to Premium, which is different from the mirrored data disk type Standard, could you help check it?

**Comment by ZoneKKL** [comment]
@Fred-sun @tophercamino if possible, can we schedule a teams meeting to discuss?

**Comment by Fred-sun** [comment]
@ZoneKKL I tested it locally and found that it was not set to 'premium', but the same configuration as the VM disk used to make the image. Thanks!

**Comment by ZoneKKL** [comment]
@Fred-sun thanks for the update. Can we talk about it on teams chat. You could reach out to me via v-zhoujian@microsoft.com. Thank you!

**Comment by Fred-sun** [comment]
@ZoneKKL As our teams talk. The VM is now created using an OS image. Because the image cannot be parsed for the time being, you cannot set the type of data disk in the image. Thanks!

**Comment by Fred-sun** [comment]
Duplicate with #883 , I will closed it and tracking it in #883
