### ISSUE TITLE
Module azure_rm_virtualmachine data_disks/caching documentation should mention about none

### ISSUE THREAD

**Issue by msLinuxNinja** [ansible/ansible_collections_azure#106]
##### SUMMARY
The documentation for the azure_rm_virtualmachine module doesn't specify that the parameter data_disks: caching=none option can be used.

Docs: [https://docs.ansible.com/ansible/latest/modules/azure_rm_virtualmachine_module.html](https://docs.ansible.com/ansible/latest/modules/azure_rm_virtualmachine_module.html)

Ideally the it should explicitly say that the parameter data_disks/caching can be set to none.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
azure_rm_virtualmachine data_disks/caching

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/panzer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/panzer/.local/lib/python3.6/site-packages/ansible
  executable location = /home/panzer/.local/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

**Comment by haiyuazhang** [comment]
@msLinuxNinja  red hat is working on a new way to document ansible collection and not yet finished.
so most likely, any module documentation update/change will hold for a while

**Comment by msLinuxNinja** [comment]
`sad face` Understand! Hopefully we'll see these options implemented. If nothing can be done, we can close this issue.

**Comment by Fred-sun** [comment]
Nothing can be done, close this!
