### ISSUE TITLE
Documentation mentions non-working "compose" option.

### ISSUE THREAD

**Issue by mohag** [ansible/ansible_collections_azure#1062]
##### SUMMARY
The [documentation for version 1.14](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html) of the inventory plugin mentions a [`compose` option](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html#parameter-compose), seemingly identical to `hostvar_expressions`, that does not work.

I do not see this parameter in the [.py file](https://github.com/ansible-collections/azure/blob/dev/plugins/inventory/azure_rm.py).

It seems to be pulled in from [the `constructed` documentation fragment](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/constructed.py).

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
azure.azcollection.azure_rm

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gertvdb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gertvdb/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/gertvdb/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gertvdb/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

**Comment by mohag** [comment]
Looking at the code, the [`groups` parameter]() likely has the same issue with being [named `conditional_groups`](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html#parameter-conditional_groups) in this plugin instead.

**Comment by Fred-sun** [comment]
@mohag This parameter works, can you share your test case? Let me check it for you. Thank you.

**Comment by mohag** [comment]
Inventory 1: (using `compose`)
```
plugin: azure.azcollection.azure_rm

exclude_host_filters:
- tags['managed-by'] is not defined or tags['managed-by'] != 'ansible'

compose:
  testvar: "'testvar_value'"
```

Inventory 2: (using `hostvar_expression`)
```
plugin: azure.azcollection.azure_rm

exclude_host_filters:
- tags['managed-by'] is not defined or tags['managed-by'] != 'ansible'

hostvar_expressions:
  testvar: "'testvar_value'"
```
Expected output of ansible-inventory on both: Identical

Test of output difference:
```
$ diff -u <(ansible-inventory -i compose-azure_rm.yaml --list) <(ansible-inventory -i hostvar_expressions-azure_rm.yaml --list)
--- /dev/fd/63  2023-01-06 15:15:20.166527200 +0200
+++ /dev/fd/62  2023-01-06 15:15:20.171951500 +0200
@@ -54,6 +54,7 @@
                     "ansible_swapfile_size": "4G",
                     "managed-by": "ansible"
                 },
+                "testvar": "testvar_value",
                 "virtual_machine_size": "Standard_E2ds_v5",
                 "vmid": "<removed>",
                 "vmss": {}
@@ -111,6 +112,7 @@
                     "ansible_swapfile_size": "4G",
                     "managed-by": "ansible"
                 },
+                "testvar": "testvar_value",
                 "virtual_machine_size": "Standard_E2ds_v5",
                 "vmid": "<removed>",
                 "vmss": {}
@@ -168,6 +170,7 @@
                     "ansible_swapfile_size": "4G",
                     "managed-by": "ansible"
                 },
+                "testvar": "testvar_value",
                 "virtual_machine_size": "Standard_E2ds_v5",
                 "vmid": "<removed>",
                 "vmss": {}
```
**Note that `testvar` is only set when done with `hostvar_expression`, not when done with the `compose` options which is documented to be identical.** (I was basing the inventory on one for AWS and the compose option means less changes) (but the code (linked in the initial post on this bug) never processes the compose option - it is ignored)

More complete output with the compose option, with sensitive fields removed:  (the diff is easier than censoring two outputs) (I only kept one of the 3 hosts, for simplicity)
```
 $ ansible-inventory -i compose-azure_rm.yaml --list
{
    "_meta": {
        "hostvars": {
            "<removed hostname1>": {
                "ansible_host": "<removed>",
                "ansible_python_interpreter": "/usr/bin/python3",
                "availability_zone": null,
                "computer_name": "<removed>",
                "default_inventory_hostname": "<removed>",
                "id": "<removed>",
                "image": {
                    "offer": "0001-com-ubuntu-server-focal",
                    "publisher": "canonical",
                    "sku": "20_04-lts-gen2",
                    "version": "latest"
                },
                "location": "<removed>",
                "mac_address": "<removed>",
                "name": "<removed>",
                "network_interface": "<removed>",
                "network_interface_id": "<removed>",
                "os_disk": {
                    "name": "<removed>",
                    "operating_system_type": "linux"
                },
                "os_profile": {
                    "system": "linux"
                },
                "plan": null,
                "powerstate": "running",
                "private_ipv4_addresses": [
                    "<removed>"
                ],
                "provisioning_state": "succeeded",
                "public_dns_hostnames": [
                    "<removed>"
                ],
                "public_ip_id": "<removed>",
                "public_ip_name": "<removed>",
                "public_ipv4_addresses": [
                    "<removed>"
                ],
                "resource_group": "<removed>",
                "resource_type": "Microsoft.Compute/virtualMachines",
                "security_group": "<removed>",
                "security_group_id": "<removed>",
                "tags": {
                    <removed>,
                    "managed-by": "ansible"
                },
                "virtual_machine_size": "Standard_E2ds_v5",
                "vmid": "<removed>",
                "vmss": {}
            }
        }
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    },
    "ungrouped": {
        "hosts": [
            "<removed>"
        ]
    }
}
```

**Comment by akira6592** [comment]
It reproduced in my environment, too. (ansible-core 2.14.2 / azure.azcollection 1.14.0)

It appears that `hostvar_expressions` applies instead of `compose`.
https://github.com/ansible-collections/azure/blob/v1.14.0/plugins/inventory/azure_rm.py#L303

For comparison, here is the same part of `amazon.aws.aws_ec2` inventory plugin where `compose` can be used.
https://github.com/ansible-collections/amazon.aws/blob/5.1.0/plugins/inventory/aws_ec2.py#L794

**Comment by Fred-sun** [comment]
@mohag @akira6592 azure_rm.py replaces "compose" with" hostvar_expressions". What's wrong with that? Thanks!

**Comment by mohag** [comment]
> @mohag @akira6592 azure_rm.py replaces "compose" with" hostvar_expressions". What's wrong with that? Thanks!

This is a documentation issue. The documentation still mentions the "compose" option, which does not work. (which gets pulled in from a fragment)

**Comment by Fred-sun** [comment]
@mohag Yes, aze.azcollection.azure_rm it inherits the parameters of 'constructed' from ansible documentation, but does not use the parameter 'compse', I will see how to fix it. Thanks!

**Comment by Fred-sun** [comment]
@mohag I've added 'compose' support in #1065. Thanks!
