### ISSUE TITLE
Requirement package azure-mgmt-datalake-store version 1.0.0 has been yanked

### ISSUE THREAD

**Issue by gygitlab** [ansible/ansible_collections_azure#1072]
##### SUMMARY
Looks like the [`1.0.0` version of `azure-mgmt-datalake-store`](https://github.com/ansible-collections/azure/blob/dev/requirements-azure.txt#L17) has been [yanked from PyPi](https://pypi.org/project/azure-mgmt-datalake-store/1.0.0/) resulting in this warning being thrown by pip each time:

```python
WARNING: The candidate selected for download or install is a yanked version: 'azure-mgmt-datalake-store' candidate (version 1.0.0 at https://files.pythonhosted.org/packages/ff/24/9212a136eeb98aa9031d8d58c90733e0527647ceabb4776bcf42a0316bd8/azure_mgmt_datalake_store-1.0.0-py2.py3-none-any.whl#sha256=02c0ceed26f9188e588dc1d4b1191184767f48a631e43f4d38de7d114ff61034 (from https://pypi.org/simple/azure-mgmt-datalake-store/))
Reason for being yanked: Retiring this version of the SDK.
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Python package requirements

##### ANSIBLE VERSION
Not applicable

##### COLLECTION VERSION
Latest

##### CONFIGURATION
Not applicable

##### OS / ENVIRONMENT
Not applicable

##### STEPS TO REPRODUCE
Attempt to install the python packages in the [requirements file](https://github.com/ansible-collections/azure/blob/dev/requirements-azure.txt) via pip.

##### EXPECTED RESULTS
Packages install without any warnings

##### ACTUAL RESULTS
Package installs with the above warning.

**Comment by Fred-sun** [comment]
@gygitlab Thank you for submitting this question. This version will be used temporarily. Once there is a newer version, we will update to the latest one. In addition, the previous SDK version is old and we will not consider lowering it to a lower version. Thanks!

**Comment by Fred-sun** [comment]
@gygitlab Yes, azure-mgmt-datalake-store has been abandoned, azure_rm_datalake.py and azure_rm_datalake_info.py will also be abandoned. Please reference #1501. Thank you!
