### ISSUE TITLE
Issue with azure_rm_webapp_info 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible_collections_azure#1083]
##### SUMMARY

Unable to retrieve info of an azure app service (webapp). Error is unclear or is the module is broken.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`azure.azcollection.azure_rm_webapp_info`
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
```

##### COLLECTION VERSION

```paste below
1.14.0
```

##### OS / ENVIRONMENT

`Linux` `x64` `ubuntu 22.04`

##### STEPS TO REPRODUCE

- Create a resource group called `test-rg`
- Create and app service plan
- Create a web app within the new service plan
  - Docker container
  - Private Azure Container Registry
  - Connect to ACR using admin creds for pull
  - Enable vnet integration
- Use module `azure_rm_webapp_info` and only pass in a resource group, as per the examples provided
- Try to assign the information to a fact

```yaml
- name: Get facts for web apps
  azure.azcollection.azure_rm_webapp_info:
    resource_group: "test-rg"
  register: webapp_list
```

##### EXPECTED RESULTS

Output of the web app info contained in the fact called `webapp_list`

##### ACTUAL RESULTS

`fatal: [localhost]: FAILED! => ***"changed": false, "module_stderr": "Datetime with no tzinfo will be considered UTC.\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1676569203.7987483-172578-17808830956604/AnsiballZ_azure_rm_webapp_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1676569203.7987483-172578-17808830956604/AnsiballZ_azure_rm_webapp_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1676569203.7987483-172578-17808830956604/AnsiballZ_azure_rm_webapp_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_webapp_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_webapp_info', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_webapp_info_payload_dy1wefvr/ansible_azure.azcollection.azure_rm_webapp_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_webapp_info.py\", line 516, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_webapp_info_payload_dy1wefvr/ansible_azure.azcollection.azure_rm_webapp_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_webapp_info.py\", line 512, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_webapp_info_payload_dy1wefvr/ansible_azure.azcollection.azure_rm_webapp_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_webapp_info.py\", line 280, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_webapp_info_payload_dy1wefvr/ansible_azure.azcollection.azure_rm_webapp_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_webapp_info_payload_dy1wefvr/ansible_azure.azcollection.azure_rm_webapp_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_webapp_info.py\", line 296, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_webapp_info_payload_dy1wefvr/ansible_azure.azcollection.azure_rm_webapp_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_webapp_info.py\", line 329, in list_by_resource_group\n  File \"/tmp/ansible_azure.azcollection.azure_rm_webapp_info_payload_dy1wefvr/ansible_azure.azcollection.azure_rm_webapp_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_webapp_info.py\", line 429, in get_curated_webapp\nUnboundLocalError: local variable 'app_settings' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1***`

```paste below

```

**Comment by Fred-sun** [comment]
@RyanS-J I did not encounter your problem in the local test, could you please help to provide more detailed information? This will help solve the problems you encounter! Thanks!

**Comment by Fred-sun** [comment]
kindly ping!

**Comment by Fred-sun** [comment]
@RyanS-J If there is no more information on this issue, we will consider closing it down. We have no problem with repeated testing! Thank you very much!
