### ISSUE TITLE
Support cli auth for azure_keyvault_secret lookup

### ISSUE THREAD

**Issue by jkroepke** [ansible/ansible_collections_azure#1088]
##### SUMMARY

Most of the task plugins are supporting azure cli as credentials source.

However, the azure_keyvault_secret lookup plugin only supports MSI and Service Principal.

##### ISSUE TYPE
- Support cli auth for azure_keyvault_secret lookup

##### COMPONENT NAME
azure_keyvault_secret

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by Fred-sun** [comment]
@jkroepke I have added support for cli credentials in PR #1161. Please take a try. Thank you very much!
