### ISSUE TITLE
azure_rm dynamic inventory error:    [WARNING]:  * Failed to parse /home/nwmadmin/AWX/azure_rm.yaml with auto plugin: name 'azure_cloud' is not defined

### ISSUE THREAD

**Issue by jpsebasti** [ansible/ansible_collections_azure#1091]
I've searched all over the internet and cannot find a solution to this problem.

OS: Ubuntu 22.04.2

$ ansible --version
ansible [core 2.14.2]
  config file = /home/nwmadmin/.ansible.cfg
  configured module search path = ['/home/nwmadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/nwmadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

$ python3 --version
Python 3.10.6

I'm trying to get the dynamic inventory for my Azure subscription working.

Per the Azure documentation, I've created the file  azure_rm.yaml  with the following contents:

plugin: azure.azcollection.azure_rm
include_vm_resource_groups:
  - '*'
auth_source: auto

Using the command:

$ ansible-inventory -i azure_rm.yaml --graph -vvv
ansible-inventory [core 2.14.2]
  config file = /home/nwmadmin/.ansible.cfg
  configured module search path = ['/home/nwmadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/nwmadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-inventory
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
Using /home/nwmadmin/.ansible.cfg as config file
redirecting (type: inventory) ansible.builtin.azure_rm to azure.azcollection.azure_rm
host_list declined parsing /home/nwmadmin/AWX/azure_rm.yaml as it did not pass its verify_file() method
script declined parsing /home/nwmadmin/AWX/azure_rm.yaml as it did not pass its verify_file() method
Using inventory plugin 'ansible_collections.azure.azcollection.plugins.inventory.azure_rm' to process inventory source '/home/nwmadmin/AWX/azure_rm.yaml'
toml declined parsing /home/nwmadmin/AWX/azure_rm.yaml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /home/nwmadmin/AWX/azure_rm.yaml with auto plugin: name 'azure_cloud' is not defined
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/auto.py", line 59, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 220, in parse
    self._credential_setup()
  File "/usr/lib/python3/dist-packages/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 241, in _credential_setup
    self.azure_auth = AzureRMAuth(**auth_options)
  File "/usr/lib/python3/dist-packages/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1496, in __init__
    self._cloud_environment = azure_cloud.AZURE_PUBLIC_CLOUD  # SDK default
[WARNING]:  * Failed to parse /home/nwmadmin/AWX/azure_rm.yaml with yaml plugin: Plugin configuration YAML file, not YAML inventory
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/yaml.py", line 114, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse /home/nwmadmin/AWX/azure_rm.yaml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is
reserved to provide a port.
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/ini.py", line 137, in parse
    raise AnsibleParserError(e)
[WARNING]:  * Failed to parse /home/nwmadmin/AWX/azure_rm.yaml with ansible_collections.azure.azcollection.plugins.inventory.azure_rm plugin: name 'azure_cloud' is not
defined
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 220, in parse
    self._credential_setup()
  File "/usr/lib/python3/dist-packages/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 241, in _credential_setup
    self.azure_auth = AzureRMAuth(**auth_options)
  File "/usr/lib/python3/dist-packages/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1496, in __init__
    self._cloud_environment = azure_cloud.AZURE_PUBLIC_CLOUD  # SDK default
[WARNING]: Unable to parse /home/nwmadmin/AWX/azure_rm.yaml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
@all:
  |--@ungrouped:

I have also tried using a ~/.azure/credentials file with the  <value> replaced with my correct identifiers:
[default]
subscription_id=<value>
client_id=<value>
secret=<value>
tenant=<value>

I then change the azure_rm.yaml file to use auth_source: credential_file

The output errors are identical to what is shown above.

I then try first logging into the azure subscription with:
$ az login -u myusername
$ az account show
$ az account show
{
  "environmentName": "AzureCloud",
  "homeTenantId": "<value>",
  "id": "<value>",
  "isDefault": true,
  "managedByTenants": [],
  "name": "<value>",
  "state": "Enabled",
  "tenantId": "<value>",
  "user": {
    "name": "<myusername>",
    "type": "user"
  }
}

If I replace the auth_source in my azure_rm.yaml file with:   auth_source: cli
and then run the command:

$ ansible-inventory -i azure_rm.yaml --graph -vvv

The warning for the auto plugin is:

[WARNING]:  * Failed to parse /home/nwmadmin/AWX/azure_rm.yaml with auto plugin: Failed to import the required Python library (azure-cli) on ansibleautomationvm's Python
/usr/bin/python3. This is required for `cli` auth_source. Please read the module documentation and install it in the appropriate location. If the required library is
installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter

I've read the module documentation located here:
https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html

I see no reference in that documentation on how to or where to install the (azure-cli) python library.

**Comment by jpsebasti** [comment]
One other thing, I also tried adding to the azure_rm.yaml file the parameter:
cloud_environment: AzureCloud

This appears to be the default from the module documentation however, the original error message is still produced:

[WARNING]:  * Failed to parse /home/nwmadmin/AWX/azure_rm.yaml with auto plugin: name 'azure_cloud' is not defined

**Comment by Fred-sun** [comment]
@jpsebasti There is no problem in the local test. According to your error report, there is a problem with your "PlayBook". Could you please check your playbook? Or try again in a different environment！ Thanks!
```e.g.

**Comment by akira6592** [comment]
@jpsebasti Did you install dependent packages?

In my environment, I reproduced `'azure_cloud' is not defined` when I did not install any dependent packages. The same is true for method `pip install 'ansible[azure]'` as described in the [Ansible documentation](https://docs.ansible.com/ansible/latest/scenario_guides/guide_azure.html#requirements).

The right way is `pip install -r requirements-azure.txt`  (adjust path to collection if necessary) like [README.md](https://github.com/ansible-collections/azure#requirements) says.

**Comment by jpsebasti** [comment]
Thank you akira6592.  I missed the dependent packages in my installation.  It appears to be working now.

**Comment by akira6592** [comment]
Your welcome :)

**Comment by Slowdive-Aideron** [comment]
had the same problem, it was because the ansible collection (requirements) were not installed for the user executing ansible
