### ISSUE TITLE
Can I force a playbook using a dynamic inventory of Azure VMs to use the VM's private IP address?

### ISSUE THREAD

**Issue by jpsebasti** [ansible/ansible_collections_azure#1099]
This may be the way it is supposed to work and not a bug.

I am generating a Dynamic Inventory for Azure VMs with azure_rm.yaml file.
The azure_rm.yaml looks like:

plugin: azure.azcollection.azure_rm
plain_host_names: yes
include_vm_resource_groups:
  - '*'
auth_source: auto
cloud_environment: AzureCloud

conditional_groups:
  windows: "'windows' in os_profile.system"
  linux: "'linux' in os_profile.system"

This works great, my inventory is broken down into linux and windows groups with plain hostnames.

Some of the Windows VMs have public IP addresses.  All have private IP addresses.

When I run a play against the windows group, the play attempts to use the public IP address.  I want my play to always use the private IP address.  

Is there a way to configure this?  Is this expected behavior or a bug?  

I've been searching a lot to see if I can find a solution and so far, no luck.

Thanks in advance.

**Comment by akira6592** [comment]
Hello @jpsebasti 

Can you try adding bellow option to the `azure_rm.yaml` ?

```yaml
hostvar_expressions:
  ansible_host: private_ipv4_addresses | first
```

Then,  executing a `ansible-inventory -i azure_rm.yaml --list | grep ansible_host` private IP addresses will be shown.

```jsonc
                // example
                "ansible_host": "10.1.0.9",
                "ansible_host": "10.1.0.4",
                "ansible_host": "10.1.0.7",
                "ansible_host": "10.1.0.8",
```

And the play will attempt to use the public IP address.

**Comment by jpsebasti** [comment]
It looks like using hostvar_expressions: in my azure_rm.yaml file did the trick.
I was lucky enough to find an example that used a public IP address with hostvar_expressions on the internet.  I just guessed at the value to use below but it worked.   The documentation for some of these parameters on the Ansible web site is very slight.  There should be a lot more examples.

This is what my azure_rm.yaml file looks like now.  It returned the private IP address for all of my hosts:
plugin: azure.azcollection.azure_rm
plain_host_names: yes
include_vm_resource_groups:
  - '*'
auth_source: auto
cloud_environment: AzureCloud

hostvar_expressions:
  ansible_host: (private_ipv4_addresses) | first

conditional_groups:
  windows: "'windows' in os_profile.system"
  linux: "'linux' in os_profile.system"
