### ISSUE TITLE
spelling mistake in examples for module azure.azcollection.azure_rm_privatelinkservice_info

### ISSUE THREAD

**Issue by ramdaspotale** [ansible/ansible_collections_azure#1101]
##### SUMMARY

The module documentation for azure.azcollection.azure_rm_privatelinkservice_info has examples on how we can use the module. however there is spelling mistake in module name in examples.

there is extra "e" in name as azure_rm_privateelinkservice_info, which wont work as its incorrect. [link ](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_privatelinkservice_info_module.html#examples)

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

ansible module azure.azcollection.azure_rm_privatelinkservice_info
##### ANSIBLE VERSION

```paste below
azure.azcollection collection : version 1.14.0
```

**Comment by akira6592** [comment]
Hello @ramdaspotale .

Thank you for reporting! Fixed #1102
