### ISSUE TITLE
Consider using true/false for all booleans in docs

### ISSUE THREAD

**Issue by kristianheljas** [ansible/ansible_collections_azure#1106]
Based on the [community decision](https://github.com/ansible-community/community-topics/discussions/120) to use `true/false` for boolean values in documentation and examples, we ask that you evaluate booleans in this collection and consider changing any that do not use `true/false` (lowercase).

See [documentation block format](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#documentation-block) for more info (specifically, option defaults).

If you have already implemented this or decide not to, feel free to close this issue.

---

P.S. This is auto-generated issue, please raise any concerns [here](https://github.com/ansible-community/community-team/issues/60)

**Comment by Fred-sun** [comment]
@kristianheljas Ansible is developed based on python. By default, ansible interprets' yes', 'no', false, true, 1, 0, True, False, etc. into corresponding bool values. There is no restriction that the bool must be 'True' or 'False', thank you!

**Comment by kristianheljas** [comment]
@Fred-sun You are correct, there is no restriction and and in the foreseeable future, there won't be.

The main driver behind this is to normalize documentation (docs.ansible.com, ansible-doc, ...) and this would also conform to [yaml 1.2 spec](https://yaml.org/spec/1.2.2/#10212-boolean) avoiding the confusion about what a boolean actually is (see the [norway problem](https://hitchdev.com/strictyaml/why/implicit-typing-removed/) for example).

That said, this is not a hard requirement but a mere suggestion and you are free to choose whatever you prefer - we just ask you to consider it.

**Comment by Fred-sun** [comment]
@kristianheljas Thank you for your advice. This may be the goal we pursue in the future, but we don't want to change it for the time being, so we suggest closing it. Thanks!
