### ISSUE TITLE
Trying to figure out where the plugin is retrieving the returned values for ansible_user and ansible_password?

### ISSUE THREAD

**Issue by jpsebasti** [ansible/ansible_collections_azure#1107]
$ ansible --version
ansible [core 2.14.2]
  config file = /home/johnadmin/ansible/ansible.cfg
  configured module search path = ['/home/johnadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/johnadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

OS: Ubuntu 22.04
Machine is running in Azure.

My credentials file (~/.azure/credentials) contains this information
[default]
subscription_id=subscription id here
client_id=service principal ID here
secret=secret for service principal here
tenant=tenant id here

My azure_rm.yaml file looks like:

plain_host_names: yes
include_vm_resource_groups:
  - '*'
auth_source: auto
cloud_environment: AzureCloud

hostvar_expressions:
  ansible_host: (private_ipv4_addresses) | first

conditional_groups:
  windows: "'windows' in os_profile.system"
  linux: "'linux' in os_profile.system"

The ansible configuration file being used is: ~/.ansible.cfg
In this configuration file I have only these options set:

inventory=~/ansible/azure_rm.yaml
private_key_file=~/.ssh/johnadmin_id_rsa
remote_user=johnadmin
enable_plugins=host_list, script, auto, yaml, ini, toml, azure_rm

I'm logged into the Ubuntu host as user johnadmin
All of my linux VMs also have a johnadmin account on them.  
I have an SSH private key file for johnadmin that I use to successfully SSH to all of the remote linux machines.
That SSH Private Key file is:  ~/.ssh/johnadmin_id_rsa

The following SSH commands are all successful at connecting to the target Linux VMs from this ansible control host that 
I am running on:
$ ssh johnadmin@qualys-scanner-appliance -i ~/.ssh/johnadmin_id_rsa
$ ssh johnadmin@ansibleautomationvm -i /~/.ssh/johnadmin_id_rsa
$ ssh johnadmin@proxy-01 -i ~/.ssh/johnadmin_id_rsa
$ ssh johnadmin@ansibletowervm -i ~/.ssh/johnadmin_id_rsa
$ ssh johnadmin@lnx1 -i ~/.ssh/johnadmin_id_rsa

As far as I can tell, there are no hidden values being sent to ansible for ansible_user or ansible_password when I run this command:
$ ansible-inventory --list -vvv>outputfile.txt

When I edit the outputfile.txt, every returned value for ansible_user is 'vmadmin' and every returned value for ansible_password is set to one or more old versions of the password that I had set at some point for the vmadmin account.

NOTE: The account vmadmin is NOT a local OS account on any of my windows or linux hosts.  It is an Azure AD account in the Tenant that I specified in the ~/.azure/credentials file.

I can't understand where the plug-in is getting this Azure AD account as the ansible_user value that it returns.
The vmadmin Azure AD account is not associated in any way with the Service Principal that is used to connect to Azure with the Azure RM plugin.

My question is where is the Azure_RM inventory plugin retrieving this user and password information from when it returns the data with the --list option?  

The main problem I'm having is that for my Linux VMs I want ansible to SSH to them as johnadmin with the private key file that I specified in the ~/.ansible.cfg file however when I try and use this Azure_RM dynamic inventory, it appears to be trying to use the vmadmin account instead.  I'm guessing because the dynamic inventory is returning vmadmin as the ansible_user.   

Here is what I mean. When I issue this command while logged into the Ubuntu controller host as johnadmin, it appears to be trying to SSH to the linux hosts as user vmadmin which I assume is because the dynamic inventory is returning vmadmin as the value for ansible_user on all of those hosts:

$ ansible linux -m ping -vvv
ansible [core 2.14.2]
  config file = /home/johnadmin/.ansible.cfg
  configured module search path = ['/home/johnadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/johnadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
Using /home/johnadmin/.ansible.cfg as config file
redirecting (type: inventory) ansible.builtin.azure_rm to azure.azcollection.azure_rm
host_list declined parsing /home/johnadmin/ansible/azure_rm.yaml as it did not pass its verify_file() method
script declined parsing /home/johnadmin/ansible/azure_rm.yaml as it did not pass its verify_file() method
Using inventory plugin 'ansible_collections.azure.azcollection.plugins.inventory.azure_rm' to process inventory source '/home/johnadmin/ansible/azure_rm.yaml'
Parsed /home/johnadmin/ansible/azure_rm.yaml inventory source with auto plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
<10.5.0.6> ESTABLISH SSH CONNECTION FOR USER: vmadmin
<10.5.0.6> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/johnadmin/.ssh/johnadmin_id_rsa"' -o 'User="**vmadmin**"' -o ConnectTimeout=10 -o 'ControlPath="/home/johnadmin/.ansible/cp/83b8b80d0b"' 10.5.0.6 '/bin/sh -c '"'"'echo ~vmadmin && sleep 0'"'"''
<10.5.0.4> ESTABLISH SSH CONNECTION FOR USER: vmadmin
<10.5.0.4> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/johnadmin/.ssh/johnadmin_id_rsa"' -o 'User="vmadmin"' -o ConnectTimeout=10 -o 'ControlPath="/home/johnadmin/.ansible/cp/d6c7d28213"' 10.5.0.4 '/bin/sh -c '"'"'echo ~vmadmin && sleep 0'"'"''
<10.0.1.6> ESTABLISH SSH CONNECTION FOR USER: vmadmin
<10.0.1.6> SSH: EXEC sshpass -d14 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/johnadmin/.ssh/johnadmin_id_rsa"' -o 'User="vmadmin"' -o ConnectTimeout=10 -o 'ControlPath="/home/johnadmin/.ansible/cp/7a56a34a09"' 10.0.1.6 '/bin/sh -c '"'"'echo ~vmadmin && sleep 0'"'"''
<10.0.6.4> ESTABLISH SSH CONNECTION FOR USER: vmadmin
<10.0.6.4> SSH: EXEC sshpass -d16 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/johnadmin/.ssh/johnadmin_id_rsa"' -o 'User="vmadmin"' -o ConnectTimeout=10 -o 'ControlPath="/home/johnadmin/.ansible/cp/7c43ae2e51"' 10.0.6.4 '/bin/sh -c '"'"'echo ~vmadmin && sleep 0'"'"''
<10.0.21.4> ESTABLISH SSH CONNECTION FOR USER: vmadmin
<10.0.21.4> SSH: EXEC sshpass -d18 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/johnadmin/.ssh/johnadmin_id_rsa"' -o 'User="vmadmin"' -o ConnectTimeout=10 -o 'ControlPath="/home/johnadmin/.ansible/cp/2512c608c8"' 10.0.21.4 '/bin/sh -c '"'"'echo ~vmadmin && sleep 0'"'"''
<10.0.21.4> (255, b'', b'ssh: connect to host 10.0.21.4 port 22: Connection refused\r\n')
qualys-scanner-appliance | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 10.0.21.4 port 22: Connection refused",
    "unreachable": true
}
<10.5.0.6> (255, b'', b'vmadmin@10.5.0.6: Permission denied (publickey).\r\n')
ansibleautomationvm | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: vmadmin@10.5.0.6: Permission denied (publickey).",
    "unreachable": true
}
<10.0.6.4> (5, b'', b'Permission denied, please try again.\r\n')
proxy-01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Invalid/incorrect password: Permission denied, please try again.",
    "unreachable": true
}
<10.5.0.4> (5, b'', b'Permission denied, please try again.\r\n')
ansibletowervm | UNREACHABLE! => {
    "changed": false,
    "msg": "Invalid/incorrect password: Permission denied, please try again.",
    "unreachable": true
}
<10.0.1.6> (5, b'', b'Permission denied, please try again.\r\n')
lnx1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Invalid/incorrect password: Permission denied, please try again.",
    "unreachable": true
}

**Comment by Fred-sun** [comment]
@jpsebasti Judging from your error, your request to establish a connection was denied. From your description, your I(remote_user=johnadmin), but you are setting up a connection with I(remote_user=vmadmin), please confirm and try again, thanks very much!

**Comment by Fred-sun** [comment]
kindly ping!
