### ISSUE TITLE
azure_rm_servicebusqueue_module docs talk about tags, but tags seems unsupported

### ISSUE THREAD

**Issue by madmalkav** [ansible/ansible_collections_azure#1113]
##### SUMMARY

azure_rm_servicebusqueue_module docs talk about tags, but tags seems unsupported

I was going to implement tag management on my playbook, but I can't find anything about using tags on queues on the web portal, the REST API, etc, ... Also on the code here seems there is nothing to manage tags.

So, it seems tags are not supported on Service Bus queues and this is a documentation error? If I'm right, this is probably wrong also on azure.azcollection.azure_rm_servicebustopicsubscription and azure.azcollection.azure_rm_servicebustopic documentation.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_servicebusqueue_module.html

**Comment by Fred-sun** [comment]
Fixes by #1114

**Comment by madmalkav** [comment]
I see #1114 adds support for namespaces, but doesn’t fix what I reported here, that is the documentation saying the queues, topics, … support tags when they don’t

**Comment by Fred-sun** [comment]
@madmalkav The queues, topics ...  not support tags, document has update.  Thank you very much!
