### ISSUE TITLE
Ansible docs website hasn't been updated to show documentation for 1.15.0

### ISSUE THREAD

**Issue by kmj251** [ansible/ansible_collections_azure#1115]
##### SUMMARY

The documentation for this collection found here:
https://docs.ansible.com/ansible/latest/collections/azure/azcollection/index.html#plugins-in-azure-azcollection
doesn't reflect the newly released version. 

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by akira6592** [comment]
Hello @kmj251 .

It will probably be reflected in the Ansible 7.4.0 release.

The Ansible documentation depends on the release cycle of the Ansible Community Package. Not the release cycle of the collection.

The current documentation is for Ansible 7.3.0 includes `azure.azcollection` 1.14.0. The [`devel` version](https://docs.ansible.com/ansible/devel/collections/azure/azcollection/index.html#plugins-in-azure-azcollection) is already for 1.15.0.

**Comment by akira6592** [comment]
Hello @kmj251 

Due to the ansible 7.4.0 has released, it became 1.15.0 on latest documents.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/16851744/228999474-e9a61d64-0088-40ef-b0d3-8d2bdf65f61e.png">
