### ISSUE TITLE
allow to set owner, group and mode for downloade files using azure.azcollection.azure_rm_storageblob module

### ISSUE THREAD

**Issue by jannickk** [ansible/ansible_collections_azure#1116]
##### SUMMARY
Currently, you can download from azure blob storage using the azure_rm_storageblob module using 'dest' parameter and 'state: present'. However, the module does not allow to set the owner, group and mode of the downloaded file (as the get_url module allows it). It is recommended best practice to set owner, gorup and mode whenever a file or folder is created.
Currently, the owner is the user executing the task (which is usually root).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_storageblob

**Comment by Fred-sun** [comment]
@jannickk Thank you for submitting this question. Currently, the API does not support changing properties for downloaded files, but we can specify file properties through the file module! Thanks!

```e.g.
- name: Force upload blob
  azure_rm_storageblob:
    resource_group: "{{ resource_group }}"
    account_name: "{{ storage_account }}"
    container_name: my-blobs
    blob: 'Ratings.png'
    src: '{{ test2_file }}'
    content_type: image/png
    force: true

- name: Download file
  azure_rm_storageblob:
    resource_group: "{{ resource_group }}"
    account_name: "{{ storage_account }}"
    container_name: my-blobs
    blob: 'Ratings.png'
    dest: '{{ test1_file }}'

- name: change file attribute
  file:
    path: '{{ test1_file }}'
    owner: user1
    group: group1
    mode: 655
