### ISSUE TITLE
The version 1.15.0 does not have `release`

### ISSUE THREAD

**Issue by akira6592** [ansible/ansible_collections_azure#1121]
##### SUMMARY

The version 1.15.0 has already released and tagged, but does not have `release`.

To make clearly that 1.15.0 has released, I think it should have `release`. 

##### ISSUE TYPE
- Bug Report

![image](https://user-images.githubusercontent.com/16851744/227142370-e71f63c5-dea8-4461-b304-c366d15f80a4.png)

**Comment by Fred-sun** [comment]
@akira6592 It's already in the works and will be officially released soon! Thank  you very much!

**Comment by akira6592** [comment]
@Fred-sun Thank you!

**Comment by HarishHary** [comment]
Hello any new on this issue? Any reason of why no release has been done?

**Comment by Fred-sun** [comment]
@HarishHary Now the version installed through "ansible-galaxy collection install aze. azcollection" is already v1.15.0, and it has not been packaged for release because there is something wrong with the release account. Once it is fixed, it will be packaged and released immediately. Thanks!

**Comment by MallocArray** [comment]
This just caused confusion for us today as well, since ansible-galaxy downloaded a version I couldn't find on the repo

**Comment by l3ender** [comment]
Any update on adding the 1.15.0 release to Github? Thank you!

**Comment by Fred-sun** [comment]
@xuzhang3 Could you please help to check why the release information is still v1.14 instead of v1.15? Thank you

**Comment by xuzhang3** [comment]
@l3ender  @Fred-sun  GH v1.15.0   https://github.com/ansible-collections/azure/releases/tag/v1.15.0

**Comment by Fred-sun** [comment]
@l3ender Already Added, I will closed it! Thank you very much!

**Comment by akira6592** [comment]
Thank you for release!
