### ISSUE TITLE
azure_rm_snapshot with support for incremental snapshots

### ISSUE THREAD

**Issue by jasonrepos** [ansible/ansible_collections_azure#1131]
##### SUMMARY
In the spirit of saving $$$, it would be nice if the module azure_rm_snapshot supported incremental snapshots instead of only full blown copies of the entire VM disk.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_snapshot

##### ADDITIONAL INFORMATION
The module azure_rm_snapshot is currently using the API version 2018-09-30.
I could not find out how to view this version of the API on the Microsoft site, however API version 2021-12-01 does support the boolean parameter "incremental".
ref:  https://learn.microsoft.com/en-us/rest/api/compute/snapshots/create-or-update?tabs=HTTP

I guess the first step would be to see if the "incremental" parameter is available in API version 2018-09-30, if so then this could be added as a parameter and included in the request body.

**Comment by Fred-sun** [comment]
Fixes by #1135
