### ISSUE TITLE
azure_rm_adpassword_info add description to return values

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1150]
##### SUMMARY

Please include the description into the output of the azure_rm_adpassword_info for client secrets of azure ad applications

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_adpassword_info

##### ADDITIONAL INFORMATION

References #1149

```yaml

```

**Comment by Fred-sun** [comment]
@Klaas- From June 30, 2020, the Azure AD graph API will no longer be updated and will be slowly deprecated and replaced by msgrpah-sdk, which we are already doing. Please refer to #1112. Also, the Azure AD SDK does not support the parameter 'description', so it cannot be added, we will refine it later in msgraph-sdk. Thank you very much!

**Comment by Fred-sun** [comment]
@Klaas- If that's okay with you, I'll continue the development of azure_rm_mspassword,py and azure_rm_mspassword_info.py and close #1150 and #1149. Thanks!

**Comment by Klaas-** [comment]
Hi @Fred-sun - yeah that is perfectly fine, I'll close both issues and follow #1112
