### ISSUE TITLE
Backups retention policies configuration option required for sqlmi db instances

### ISSUE THREAD

**Issue by pingtouskar** [ansible/ansible_collections_azure#1159]
##### SUMMARY
Currently there is no ansible module available to configure the sqlmi db backup retention policies. This possible only from Azure Portal.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
-  Azure Managed SQL instance

##### ADDITIONAL INFORMATION
- Currently there is an ansible module `azure_rm_sqlmanagedinstance` to configure the sql managed instance.
- But its not having capabilities to configure the backup retention policy for individual sql db instances.
- [azure-cli](https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/automated-backups-change-settings?view=azuresql&tabs=azure-cli) based option is there and we need a similar option via ansible module itself.

**Comment by pingtouskar** [comment]
@xuzhang3 @Fred-sun do you guys think we should enhance `azure_rm_sqlmanagedinstance` ansible module to allow us to configure the db instance level backup retention policy as well ?

**Comment by Fred-sun** [comment]
@pingtouskar What kind of enhancement do you mean? Could you be more specific? Thanks!

**Comment by pingtouskar** [comment]
> @pingtouskar What kind of enhancement do you mean? Could you be more specific? Thanks!

  @Fred-sun  I am looking for an ansible module using which I can configure the [short-term]( https://learn.microsoft.com/en-us/cli/azure/sql/midb/short-term-retention-policy?view=azure-cli-latest) and [long-term](https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/long-term-backup-retention-configure?view=azuresql&tabs=azure-cli) backup retention policies as mentioned in these documents. Currently I am using azure cli but looking for some ansible module based capabilities to achieve it.

**Comment by Fred-sun** [comment]
@pingtouskar Adding in #1548, Thank you very much!

**Comment by Fred-sun** [comment]
@pingtouskar Will you try it on? Does it meet your requirements? Thank you very much!

**Comment by Udayendu** [comment]
> @pingtouskar Will you try it on? Does it meet your requirements? Thank you very much!

Hi @Fred-sun, I don't have that setup any more. So wont be able to test it. But I will pass it to my former colleagues and see if they can run some test for this module.

Thanks alot for your help and support to get this fixed.
