### ISSUE TITLE
ansible module required for sqlmi db restore for both point-in-time and long term backups

### ISSUE THREAD

**Issue by pingtouskar** [ansible/ansible_collections_azure#1164]
##### SUMMARY
Currently there is no ansible module available to restore the sqlmi db for both point-in-time and long term restore from the available backups. Hence we need an ansible module for this capability. Only mature option is Azure Portal. Even azcli and powershell are not 100% capable enough and required the date as an input to perform the restore activity as we cant list all the available restore points.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- Azure Managed SQL instance

##### ADDITIONAL INFORMATION (Capabilities Required)
 - How to list all the available point-in-time restore points ?
 - How to restore it to any one of the available restore point ?
    - How to restore it to the latest restore point ?  (May be using a specific flag to detect the latest restore point automatically and restore it to the available backup of that time.)

**Comment by pingtouskar** [comment]
@xuzhang3 @Fred-sun  This is another requirement for sqlmi db restore. Let me know if you guys need any additional information from my side.

**Comment by Fred-sun** [comment]
Added in #1548
