### ISSUE TITLE
azure_rm_ssh_public_key: missing functionality

### ISSUE THREAD

**Issue by sean-freeman** [ansible/ansible_collections_azure#1170]
##### SUMMARY

`azure_rm_ssh_public_key`: missing functionality, unable to import an SSH Public Key to MS Azure platform.

- GUI: https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.Compute%2FsshPublicKeys
- API: https://learn.microsoft.com/en-us/rest/api/compute/ssh-public-keys/create?tabs=HTTP
- Python SDK: https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2022_08_01.models.sshpublickeyresource?view=azure-python

This has a compounding issue for `azure_rm_virtualmachine`: unable to provision Azure VM with an SSH Public Key that has been loaded to MS Azure platform, must always use Ansible Variable containing the SSH Public Key string instead.

##### ISSUE TYPE
- Bug Report

##### ACTUAL RESULTS

Missing functionality, lack of parity with other methods (GUI, API, Python SDK, Terraform etc).

**Comment by Fred-sun** [comment]
Added in #1190

**Comment by sean-freeman** [comment]
@Fred-sun an update please on this PR?
