### ISSUE TITLE
Is release 1.15.0 OK?

### ISSUE THREAD

**Issue by madmalkav** [ansible/ansible_collections_azure#1171]
The release was done yesterday but it is based on the dev branch from two months ago. Is that correct? If so, we will have to wait until October or so to get the PR merged in April available in the Collection?

**Comment by Fred-sun** [comment]
@madmalkav Yes, Already released! Thank you very much!

**Comment by madmalkav** [comment]
I think you didn’t understand my comment? The release was done March 28th with code that is almost  3 months old. Is that correct? If so, when can we expect a release including the PR merged to dev in April?

**Comment by madmalkav** [comment]
I already got a (very unsatisfying) answer in https://github.com/ansible-collections/azure/pull/1092
