### ISSUE TITLE
The 1.16.0 release description is the same as 1.15.0

### ISSUE THREAD

**Issue by akira6592** [ansible/ansible_collections_azure#1179]
##### SUMMARY

The 1.16.0 release description as same as 1.15.0.

- [1.16.0](https://github.com/ansible-collections/azure/releases/tag/v1.16.0)
- [1.15.0](https://github.com/ansible-collections/azure/releases/tag/v1.15.0)

The 1.16.0 release description should be the same as 1.16.0 at [`CHANGELOG.md`](https://github.com/ansible-collections/azure/blob/dev/CHANGELOG.md#v1160-2023-5-31).

##### ISSUE TYPE
- Bug Report

**Comment by Fred-sun** [comment]
@xuzhang3 Can you help me look at this problem? Thanks!

**Comment by xuzhang3** [comment]
@akira6592 changelog updated https://github.com/ansible-collections/azure/releases/tag/v1.16.0

**Comment by akira6592** [comment]
@xuzhang3  Thank you for updating!
