### ISSUE TITLE
modules local_network_gateways + virtual_network_gateway_connections

### ISSUE THREAD

**Issue by nergalex** [ansible/ansible_collections_azure#118]
#### SUMMARY
Thank you for the module "azure_rm_virtualnetworkgateway".
In order to complete the setup of a VPN GW connection, have you already developed modules associated to the Python classes below ?

Use Case: connect another Cloud (private/public) to Azure with an IPsec VPN GW
Action needed to automate:

Provision a VPN GW of a remote Cloud (private/public) --> LocalNetworkGateways class
Connect the remote VPN GW to a Azure VPN GW (virtual_network_gateway) --> virtual_network_gateway_connections class

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
New modules : modules local_network_gateways + virtual_network_gateway_connections

##### ADDITIONAL INFORMATION
```
NetworkManagementClient.local_network_gateways
NetworkManagementClient.virtual_network_gateway_connections
Example of Python script currently used:

NetworkManagementClient(credentials, subscription_id).local_network_gateways.create_or_update(
                resource_group_name=local_gw['resource_group_name'],
                local_network_gateway_name=local_gw['local_network_gateway_name'],
                parameters={
                    'location': local_gw['location'],
                    'local_network_address_space': {
                        'address_prefixes': local_gw['local_network_address_space']
                    },
                    'gateway_ip_address': local_gw['gateway_ip_address'],
                    'tags': local_gw['tags']
                }

NetworkManagementClient(credentials, subscription_id).virtual_network_gateway_connections .create_or_update(
                resource_group_name=local_gw['resource_group_name'],
              virtual_network_gateway_connection_name=virtual_network_gateway_connection_name,
                parameters={
                    'location': local_gw['location'],
                    'tags': local_gw['tags'],
                    'virtual_network_gateway1': virtual_network_gateway,
                    'local_network_gateway2': local_network_gateway,
                    'connection_type': 'IPsec',
                    'connection_protocol': 'IKEv2',
                    'shared_key': local_gw['shared_key']
                }
            )
```

**Comment by Fred-sun** [comment]
@nergalex Glad you raised this question, we will investigate and add this feature. Thank you!

**Comment by paronnax** [comment]
Hi, I need these modules too
Will be ingretated soon ? 
Thank you, good luck

**Comment by Fred-sun** [comment]
@TJulesVerne Working on it! Thank you very much!

**Comment by XabiBeltza** [comment]
Creating a connection would allow us to complete the whole Express Route workflow. There is already a VPN_GW and ExpressRoute roles.

**Comment by rnotley** [comment]
+1 for getting these modules.  I'm currently using ARM deployments for these resources which works but not ideal.

**Comment by Fred-sun** [comment]
@XabiBeltza @rnotley  We are developing it, thank you!

**Comment by Fred-sun** [comment]
Added in #1627  and #1523
