### ISSUE TITLE
get_virtual_machine_scale_set_network_interface

### ISSUE THREAD

**Issue by nergalex** [ansible/ansible_collections_azure#119]
##### SUMMARY
Could you please add a module to get info on a network interface for a VM Scale Set?
As azure_rm_networkinterface_info does for VM.

Use Case: retrieve Private address IPs for VMSS instances.

Class network_interfaces, Method get_virtual_machine_scale_set_network_interface()

##### ISSUE TYPE
- Feature Idea

**Comment by Fred-sun** [comment]
@nergalex Glad you raised this question, we will investigate and add this feature. Thank you!

**Comment by Fred-sun** [comment]
Added in #1125
