### ISSUE TITLE
azure_rm_manageddisk does not allow to detach a disk where the disk and the vm are in different resource groups

### ISSUE THREAD

**Issue by bbooth2113** [ansible/ansible_collections_azure#1199]
Following the example in the doc I am able to attach a disk that is located in a different resource group to a VM residing in another resource group. 

  tasks:
    - name: Attaching SAS Installation Disk
      azure_rm_manageddisk:
        name: brboot-test-disk
        resource_group: disks
        disk_size_gb: 1024
        storage_account_type: Premium_LRS
        managed_by_extended:
          - resource_group: dev-brboot
            name: rhel8-brboot

This works fantastic. However when I try and umount it I get an error stating it isn't in the resource group

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error getting virtual machine rhel8-brboot - (ResourceNotFound) The Resource 'Microsoft.Compute/virtualMachines/rhel8-brboot' under resource group 'disks' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\nCode: ResourceNotFound\nMessage: The Resource 'Microsoft.Compute/virtualMachines/rhel8-brboot' under resource group 'disks' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}

using the following code

  tasks:
    - name: Attaching SAS Installation Disk
      azure_rm_manageddisk:
        name: brboot-test-disk
        resource_group: disks
        disk_size_gb: 1024
        storage_account_type: Premium_LRS
        managed_by: ''

I don't see a way to be able to detach the disk since the vm isn't in the same resource group. Any way around this?

**Comment by Fred-sun** [comment]
Fixes by #1201`

**Comment by bbooth2113** [comment]
Thank you very much!
