### ISSUE TITLE
New module (module: azure_rm_msgroup) does not allow user management for the group.

### ISSUE THREAD

**Issue by amarmh** [ansible/ansible_collections_azure#1204]
##### SUMMARY
The new changes/modules introduced in https://github.com/ansible-collections/azure/pull/1112 does not allow user management for the group.

##### ISSUE TYPE
Old  module : module: azure_rm_adgroup -  https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_adgroup.py used to provide a functionality to add/remove a particular user from a group:
Eg:
~~~
 - name: Ensure Users are Members of a Group using object_id
      azure_rm_adgroup:
        tenant: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        object_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        state: 'present'
        present_members:
          - "https://graph.windows.net/{{ ad_object_1_tenant_id }}/directoryObjects/{{ ad_object_1_object_id }}"
          - "https://graph.windows.net/{{ ad_object_2_tenant_id }}/directoryObjects/{{ ad_object_2_object_id }}"
~~~
However, this functionality does not exist with the new module.( azure_rm_msgroup)

##### COMPONENT NAME
repo - https://github.com/ansible-collections/azure 
Module name : 
  old - module: azure_rm_adgroup
  new- module: azure_rm_msgroup

**Comment by Fred-sun** [comment]
@amarmh As described in #1112, msgraph-core cannot be used directly for the time being, we are studying a new way, #1112 has been closed, close this Issue for the time being. Thank you!
