### ISSUE TITLE
azure_rm_backupazurevm module does not honor the subscription variable

### ISSUE THREAD

**Issue by scottharwell** [ansible/ansible_collections_azure#1218]
##### SUMMARY

This is a quote from a bug report submitted to Red Hat:

> I'm using the azure.azcollection.azure_rm_backupazurevm module to enable protection for a VM and I'm providing all the parameters including the subscription. The module uses my service principal's default subscription for the context and fails to locate the vault's resource group instead of using the subscription I provide to it. My service principal has access to the target subscription. Like other modules, the subscription provided in the parameters should be used but that is not the case here.
>
> More detailed description of the issue:
>
> We have a multi-subscription Azure tenant and we use a single service principal (SP) to run Ansible plays against it.
>
> Azure service principals (much like Azure AD accounts) have a default subscription associated with them
>
> When authenticating with Azure, the default SP subscription is used as the context for operations following authentication unless the context is explicitly changed to another subscription
>
> Most Azure modules I've used thus far allow specifying the context subscription and the operation (like creating a VM) just works fine and that is how it should be
>
> The azure_rm_backupazurevm however, does not respect the context subscription parameter passed to it like the other modules and ends up reporting an error stating it could not find the resources in question, since it uses the SP's default subscription.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

`azure_rm_backupazurevm`

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.16 (main, May 31 2023, 12:21:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 1.13.0
```

We have also explored the issue against v1.16.0 to see if the modern collection version corrected the issue.  There were no changes between those two versions that would appear to impact this function.

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS($HOME/.ansible.cfg) = True
CONFIG_FILE() = $HOME/.ansible.cfg
GALAXY_SERVER_LIST($HOME/.ansible.cfg) = ['automation_hub', 'galaxy']
INVENTORY_ENABLED($HOME/.ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml']
```

##### OS / ENVIRONMENT

Ansible Automation Platform on Microsoft Azure (Red Hat's managed application offering)

##### STEPS TO REPRODUCE

> I'm using the azure.azcollection.azure_rm_backupazurevm module to enable protection for a VM and I'm providing all the parameters including the subscription. The module uses my service principal's default subscription for the context and fails to locate the vault's resource group instead of using the subscription I provide to it. My service principal has access to the target subscription.

```yaml
name: "Apply backup policy {{ backup_policy }} to VM {{ vm_name }} in Vault {{ vault_name }}"
azure.azcollection.azure_rm_backupazurevm:
  backup_policy_id: "{{ backup_policy_info.id }}"
  resource_group: "{{ vault_rg }}"
  recovery_vault_name: "{{ vault_name }}"
  resource_id: "{{ vm_info.vms[0].id }}"
  subscription_id: "{{ subscription_id }}"
```

We have confirmed via screenshot that the resource group does belong to the subscription provided via the `subscription_id` parameter in a screenshot.

##### EXPECTED RESULTS

Like other modules, the subscription provided in the `subscription_id` variable should be used but that is not the case with this `azure_rm_backupazurevm`.

##### ACTUAL RESULTS

Removed subscription IDs and resource group names for security.

```paste below
{
    "msg": "Error in creating/updating protection for Azure VM Azure Error: ResourceGroupNotFound\nMessage: Resource group '<resource-group>' could not be found.",
    "exception": "  File \"/tmp/ansible_azure.azcollection.azure_rm_backupazurevm_payload_tnnhgil7/ansible_azure.azcollection.azure_rm_backupazurevm_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_backupazurevm.py\", line 282, in enable_update_protection_for_azure_vm\n  File \"/tmp/ansible_azure.azcollection.azure_rm_backupazurevm_payload_tnnhgil7/ansible_azure.azcollection.azure_rm_backupazurevm_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common_rest.py\", line 87, in query\n    raise exp\n",
    "invocation": {
      "module_args": {
        "backup_policy_id": "/subscriptions/<subscription>/resourceGroups/<resource-group>/providers/Microsoft.RecoveryServices/vaults/<vault>-RecoveryServicesVaultShared-01/backupPolicies/DefaultPolicy",
        "resource_group": "<resource-group>",
        "recovery_vault_name": "<vault>-RecoveryServicesVaultShared-01",
        "resource_id": "/subscriptions/<subscription>/resourceGroups/<resource_group>/providers/Microsoft.Compute/virtualMachines/ansibletest7",
        "subscription_id": "<subscription>",
        "auth_source": "auto",
        "cloud_environment": "AzureCloud",
        "api_profile": "latest",
        "append_tags": true,
        "state": "create",
        "profile": null,
        "client_id": null,
        "secret": null,
        "tenant": null,
        "ad_user": null,
        "password": null,
        "cert_validation_mode": null,
        "adfs_authority_url": null,
        "log_mode": null,
        "log_path": null,
        "x509_certificate_path": null,
        "thumbprint": null,
        "tags": null,
        "recovery_point_expiry_time": null
      }
    },
    "warnings": [
      "Azure API profile latest does not define an entry for GenericRestClient"
    ],
    "_ansible_no_log": null,
    "changed": false
  }
```

**Comment by xuzhang3** [comment]
@scottharwell  Currently `azure_rm_backupazurevm` does not support custom `subscription_id`

**Comment by scottharwell** [comment]
The module [documented](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_backuppolicy_module.html#ansible-collections-azure-azcollection-azure-rm-backuppolicy-module) as supporting the application of `subscription_id`, even if not implemented. And that documentation has existed for many versions of the module.

**Comment by xuzhang3** [comment]
What type of authorization is used for authentication? Custom `subscription_id` can be used when authenticating with the CLI

**Comment by scottharwell** [comment]
The "Microsoft Azure Resource Manager" credential type in Ansible Automation Platform.  Is your statement "Currently azure_rm_backupazurevm does not support custom subscription_id" true not just of `azure_rm_backupazurevm`, but also any module that inherits from `AzureRMModuleBaseExt` or other parent object?  If so, then we should account for where subscription id is not valid -- especially when the automation is run via Ansible Automation Platform or AWX.

**Comment by xuzhang3** [comment]
Considering the `subscription_id` as part of the authorization not a custom property set to other values. The doc is not reflect this behavior. A custom `sub_id` can be added to `azure_rm_backupazurevm` to support this feature.

**Comment by scottharwell** [comment]
@xuzhang3 thanks.  Just to be clear, you mean that "a custom sub_id can be added..." as an enhancement request, correct?  You're not stating that the custom `sub_id` is possible today, right?

**Comment by xuzhang3** [comment]
yes, a custom `sub_id` can be added in the future.

**Comment by xuzhang3** [comment]
@timway  @scottharwell I was wrong before. #1225 will fix this bug.
