### ISSUE TITLE
azure_rm_aks_info is not listing all AKS clusters under resource group

### ISSUE THREAD

**Issue by mayoubb** [ansible/ansible_collections_azure#1228]
##### SUMMARY

i am using the below module azure_rm_aks_info to list all AKS clusters under a resource group 

in your code the below python code is written : 
response = self.managedcluster_client.managed_clusters.list(self.resource_group)
while it should be : 
response = self.managedcluster_client.managed_clusters.list_by_resource_group(self.resource_group)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_aks_info
##### ANSIBLE VERSION

```
ansible [core 2.14.3]
  config file = None
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/jenkins/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```


```

##### CONFIGURATION

```
azure.azcollection
```

##### STEPS TO REPRODUCE

```

    - name: Get facts for all Azure Kubernetes Services
      azure_rm_aks_info:

even if i specify the resource group it's the same error 

```

##### EXPECTED RESULTS

should list all aks clusters 

##### ACTUAL RESULTS

```
10:46:46  fatal: [localhost]: FAILED! => {
10:46:46      "changed": false
10:46:46  }
10:46:46  
10:46:46  MSG:
10:46:46  
10:46:46  Failed to list all items - ManagedClustersOperations.list() takes 1 positional argument but 2 were given

```

**Comment by Fred-sun** [comment]
@mayoubb Many thanks for the problem reported, the code in the module was confused, should use list to get all the manged cluster under subscription, and use list_by_resource_group to get all the 'manged_cluster' under resource group. I'll fix this. Thank you!

**Comment by mayoubb** [comment]
@Fred-sun Thank youu !! 
Can you please take a look alseo on the below issue it's more important
https://github.com/ansible-collections/azure/issues/1227

**Comment by Fred-sun** [comment]
> @Fred-sun Thank youu !! Can you please take a look alseo on the below issue it's more important #1227

Working on it, thank you!

**Comment by sudheerkaramchand** [comment]
@Fred-sun  I'm trying to get details of AKS cluster like namespace & pods through Ansible playbook but couldn't find any supported parameters in Azure_rm_aks_info 
Could you please help !
