### ISSUE TITLE
Add instance_discovery toggle to modules for alternate Azure Clouds

### ISSUE THREAD

**Issue by lm-sig** [ansible/ansible_collections_azure#1236]
##### SUMMARY
Authentication with Azure passes through two libraries that changed behavior and caused a breakage in an environment I work in.

- Ansible collection (as of this report) depends on "azure-identity==1.7.0"
- Ansible collection pulls in MSAL version 1.22.0
- The MSAL library introduced a "[instance_discovery](https://msal-python.readthedocs.io/en/latest/#msal.ClientApplication.params.instance_discovery)" toggle to the PublicClientApplication function call.
- The azure-identity library added support for this toggle in version 1.13.0.

As of today the Azure Collection fails to connect in this environment:
- Network access is allowed to Azure US Government cloud. (login.microsoftonline.us)
- Network access is *not* allowed to Azure Public cloud. (login.microsoftonline.com)
- Trying to use the Azure collection in this environment fails with attempts to connect to login.microsoftonline.com.

Setting "instance_discovery=False" allows the environment to work again.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
All Azure modules.

##### ADDITIONAL INFORMATION

It may be possible to add support for this new instance_discovery toggle by checking for the existence of the "AZURE_AUTHORITY_HOST" environment variable.

```yaml

```

See also https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/578

**Comment by Fred-sun** [comment]
@lm-sig Is your problem still there? We previously encountered a similar issue, and it was fixed by specifying the permissions of Azure Active Directory endpoint #1129 when obtaining credentials. Can you update to the latest version to see if your issues are resolved? Thank you.

**Comment by lm-sig** [comment]
Thank you! It may take some time to test it, but I will try to test it.
