### ISSUE TITLE
API version 2021-03-01 does not have operation group 'virtual_networks'

### ISSUE THREAD

**Issue by Vamshidhar555** [ansible/ansible_collections_azure#1246]
Hi All,

We are trying to provision azure resources using ansible playbooks. we are running ansible playbooks using the ansible semaphore UI container.

we are able to create the  VNET from ansible playbook without azure cli installed. but when we install the azure cli 2.34.0 getting this below error.
azure_rm_virtualnetwork : API version 2021-03-01 does not have operation group 'virtual_networks' ()

 
We have explicitly mentioned the api version in the playbook but api version is not supported virtual networks and  getting the below error

 
azure_rm_virtualnetwork : Unsupported parameters for (azure_rm_virtualnetwork) module: api_version
and we are able to provision the VNET if azure cli is not installed on the host and if we install azure cli we are getting the above error.
(we tried install azure cli version of 2.27,2.34.0 and 2.51(latest))

Could anyone help on the above.

**Comment by Fred-sun** [comment]
@Vamshidhar555 Thanks for your question! From your description, the error in the installation of azure-cli should be that the installation of azure-cli has an impact on azure-mgmt-network. What if you reinstall azure-mgmt-network? Does the problem still exist?
```e.g.
sudo pip3 install azure-mgmt-network==19.1.0 -I --force

**Comment by Fred-sun** [comment]
@Vamshidhar555 Does your problem still exist? Or you can reinstall all the dependencies and that should fix the problem you're experiencing. Thank you!
