### ISSUE TITLE
Ansible docs lack file naming requirements for inventory plugin and plugin does not emit error message

### ISSUE THREAD

**Issue by msitte** [ansible/ansible_collections_azure#1251]
##### SUMMARY
- The [Ansible Documentation](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html) for the Azure Resource Manager inventory plugin lacks the key point that the Azure dynamic inventory config file must end with `azure_rm` and have an extension of either `yml` or `yaml`. This is only stated on Microsoft's [Tutorial page](https://learn.microsoft.com/en-us/azure/developer/ansible/dynamic-inventory-configure?tabs=azure-cli#generate-a-dynamic-inventory). 
- The `verify_file` function does not emit any error message but instead bails out silently, leading to obscure errors. Please add the error message back and change log level from DEBUG to ERROR.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
- azure/plugins/doc_fragments/azure.py, requirements section should contain note about the file naming
- azure/plugins/inventory/azure_rm.py, line 205, make this a proper error message

##### ANSIBLE VERSION
```
ansible [core 2.15.3]
  config file = /REDACTED/ansible.cfg
  configured module search path = ['/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /REDACTED/pythonenvs/ansible-devel-2023-08/lib64/python3.9/site-packages/ansible
  ansible collection location = /REDACTED/.ansible/collections:/usr/share/ansible/collections
  executable location = /REDACTED/pythonenvs/ansible-devel-2023-08/bin/ansible
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/REDACTED/pythonenvs/ansible-devel-2023-08/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by Fred-sun** [comment]
@msitte Thank you very much for your submission. For this, plugin/inventory/azure_rm.yml line 16, Have been standardized the file naming format. In addition, if it does not match, an exception will be raised in the verify_file and an error will be displayed. Please refer to the relevant PR -- #1348 Thank you!
