### ISSUE TITLE
Update documentation to reflect azure_rm_virtualmachine changes

### ISSUE THREAD

**Issue by arughrat** [ansible/ansible_collections_azure#1257]
The parameter vm_identity has changed from string to dict as of https://github.com/ansible-collections/azure/pull/1177

The docs here still show as string: 
https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_virtualmachine_module.html#ansible-collections-azure-azcollection-azure-rm-virtualmachine-module

**Comment by cpiment** [comment]
If I enter in that link I see the correct documentation:

![image](https://github.com/ansible-collections/azure/assets/10828255/cd6a4440-fff1-4cc3-8cec-89d953bc5e84)

**Comment by Fred-sun** [comment]
There is a time lag in documentation updates, now that it is correct, it will close this issue! Thank you!
