### ISSUE TITLE
Make it possible to distinct windows clients from windows servers when using dynamic inventories

### ISSUE THREAD

**Issue by jonlarsdizparc** [ansible/ansible_collections_azure#1259]
##### SUMMARY
Currently the only thing we have to sort machines based on os with is `os_profile.system` when using azure_rm as a dynamic inventory. The usage of image/publisher/offer is possible as well, but is very unreliable as migrated machines/custom templates do not use these fields at all times.

The Azure portal makes use of a field called `Operating system` under the `Virtual machine` section. This could be `Windows (Windows Server 2019 Datacenter)`.

Would it be possible to get this info fetched into the inventory? Would make sorting windows servers into their own group a bit easier.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure-rm

##### SOLUTION
Looks like we need to append `$expand=instanceView` to the uri when fetching vm's:
https://github.com/ansible-collections/azure/blob/dev/plugins/inventory/azure_rm.py#L257

**Comment by Fred-sun** [comment]
@jonlarsdizparc Line 257 provides a url to get the virtual machine. We can filter the virtual machines by filtering them through the parameter 'exclude_host_filters' to filter out the virtual machines we don't want to list. In addition, we are going to add the parameter 'include_host_filters' to filter out exactly what kind of virtual machines we need! Please refer to #1130 and #1347 for relevant PR. Thank you!

**Comment by jonlarsdizparc** [comment]
> @jonlarsdizparc Line 257 provides a url to get the virtual machine. We can filter the virtual machines by filtering them through the parameter 'exclude_host_filters' to filter out the virtual machines we don't want to list. In addition, we are going to add the parameter 'include_host_filters' to filter out exactly what kind of virtual machines we need! Please refer to #1130 and #1347 for relevant PR. Thank you!

I think you misunderstood the issue. I understand that we can filter machines using the `exclude_host_filters` parameter. The issue is that not all information is available that we need.

An example is when a machine is imported into Azure and not populated with offer/publisher and so forth, we currently have no way to see if this machine is a Windows Server or Windows Client. This information is available in both the GUI and via API (with the correct parameters).

**Comment by Fred-sun** [comment]
@jonlarsdizparc Thank you for your reply! Do you mean to get the type of VM you want (client or server) directly from the url? If filtering by url, what are your criteria for filtering by API?  Can you help provide a filter condition? Thank you!

**Comment by Fred-sun** [comment]
@jonlarsdizparc Because the azure_rm.py plugin also filters and filters the returned information based on the return value, if you can't directly return the information that distinguishes them, you can't filter as expected. Thank you!

**Comment by Fred-sun** [comment]
@jonlarsdizparc If you have no further questions, I will close this question. Thank you!

**Comment by Fred-sun** [comment]
@jonlarsdizparc I will add the ’license_type‘ field when obtaining host information dynamically, which is used to obtain the host license. Thank you

**Comment by jonlarsdizparc** [comment]
> @jonlarsdizparc I will add the ’license_type‘ field when obtaining host information dynamically, which is used to obtain the host license. Thank you

Sorry for not answering in time, been quite busy. Your solution is much appreciated. Thanks!
