### ISSUE TITLE
azure_rm_virtualmachinescaleset_module: The platform_fault_domain_count parameter cannot be updated!

### ISSUE THREAD

**Issue by deubert-it** [ansible/ansible_collections_azure#1261]
##### SUMMARY
I'm trying to update a VMSS with the azure ansible collection v1.17. The VMSS was created with the azure ansible collection v1.12.
The error I see is ```The platform_fault_domain_count parameter cannot be updated!```.
I think it is related to these changes in the collection v1.13: https://github.com/ansible-collections/azure/pull/779/files

In the azure portal, our existing VMSS has properties like this:
```
Overprovisioning Enabled
Fault domain count -
Single placement group Enabled
```
We also use "Uniform" as orchestration mode.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachinescaleset_module

##### ANSIBLE VERSION
```
ansible 2.10.17
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.17 (main, Jun 13 2023, 16:05:09) [GCC 8.3.0]
```

##### EXPECTED RESULTS
As far as I understand the current documentation, platform_fault_domain_count is only needed when orchestration mode is flexible and Single placement group is false. So with an already existing VMSS in the state described above (orchestration mode uniform, single placement group is true), platform_fault_domain_count should not be tried to update (it seems from the api documentation that this value can never be updated after VMSS creation), and VMSS updates to other writeables values should succeed.

##### ACTUAL RESULTS
The VMSS update call to the api tries to set platform_fault_domain_count, which seems not to be needed in this case, and is not allowed to be upgraded after VMSS creation, so every call fails with ```The platform_fault_domain_count parameter cannot be updated!```.

**Comment by Fred-sun** [comment]
@deubert-it The parameter 'platform_fault_domain_count' cannot be updated in the python SDK. When we manage this resource, we first check whether the resource exists, if it does not exist, create a new resource, if it does exist, compare the parameter, if the parameter is incorrectly configured. We will print the error using the module's 'self.fail' method and do not continue! Thank you!

**Comment by deubert-it** [comment]
@Fred-sun thank you for your response, which I understand, but it would mean I just can't use it with an existing VMSS that was created a long time ago with an older version.

**Comment by Fred-sun** [comment]
@deubert-it Sorry for replying you so late.   The parameter 'platform_fault_domain_count parameter' has been added in #779.   The default value of this parameter is 1.   If you management VMSS by 'azure_rm_virutalmachinescaleset.py', please make sure the 'platform_fault_domain_count' value same with the exsiting VMSS. This will not prompt the 'platform_fault_domain_count parameter' question.   Thank you!
In addition, to make sure my idea is correct, can you provide your VMSS information and use cases? 
```e.g.
Test case:
- name: Create VMSS with I(orchestration_mode=Flexible)
  azure_rm_virtualmachinescaleset:
    resource_group: "{{ resource_group }}"
    name: testVMSS{{ rpfx }}
    vm_size: Standard_A1_v2
    admin_username: testuser
    single_placement_group: false
    platform_fault_domain_count: 2
    public_ip_per_vm: true
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/testuser/.ssh/authorized_keys
        key_data: "ssh-rsa *****************@qq.com"
    virtual_network_name: VMSStestVnet01
    subnet_name: VMSStestSubnet01
    managed_disk_type: Standard_LRS
    orchestration_mode: Flexible
    os_disk_caching: ReadWrite
    image:
      offer: 0001-com-ubuntu-server-focal
      publisher: Canonical
      sku: 20_04-lts
      version: latest
```
```e.g.
VMSS facts:
        "vmss": [
            {
                "id": "/subscriptions/xxxxxxxxxxxxxxx/resourceGroups/v-xisuRG013/providers/Microsoft.Compute/virtualMachineScaleSets/testVMSSfredrpfx01",
                "identity": {
                    "type": "UserAssigned",
                    "user_assigned_identities": {
                        "/subscriptions/xxxxxxx/resourceGroups/AzSecPackAutoConfigRG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/AzSecPackAutoConfigUA-eastus": {}
                    }
                },
                "location": "eastus",
                "name": "testVMSSfredrpfx01",
                "orchestration_mode": "Flexible",
                "platform_fault_domain_count": 1,
                "provisioning_state": "Succeeded",
                "single_placement_group": false,
                "sku": {
                    "capacity": 1,
                    "name": "Standard_A1_v2",
                    "tier": "Standard"
                },
                "tags": {
                    "azsecpack": "nonprod",
                    "platformsettings.host_environment.service.platform_optedin_for_rootcerts": "true"
                }.

        .................................

**Comment by Fred-sun** [comment]
kindly ping!
