### ISSUE TITLE
Add ability to upload blob without using access keys

### ISSUE THREAD

**Issue by ephracis** [ansible/ansible_collections_azure#1283]
##### SUMMARY
Support identity authentication instead of access keys for storage operations.

##### ISSUE TYPE

Right now one must use access keys for the `azure_rm_storageblob` module. However, in the CLI it is possible to instead use

```
az storage blob upload --auth-mode login ...
```

##### COMPONENT NAME
azure_rm_storageblob

##### ADDITIONAL INFORMATION

This request comes from a Red Hat customer who does not allow the use of access keys for storage. Right now they have to use the `command` module because this feature is lacking.

In the documentation, access keys are even mentioned as "legacy".

If it is not too much work (I'm time boxed at 2 days) I might be able to create a pull request with this features, I just need some guidance.

**Comment by donjuanmon** [comment]
Reported in #1255 but happy to have more visibility on this issue!
