### ISSUE TITLE
About the vault name request 

### ISSUE THREAD

**Issue by TomKCTang** [ansible/ansible_collections_azure#1300]
##### SUMMARY
I would like to ask is it possible to add the function to query the configured backup vault name of a VM which already configured?Because I did notice the azure.azcollection.azure_rm_backupazurevm required the "vault name" of the associate VM.

Even the "azure.azcollection.azure_rm_backupazurevm_info" also require a vault name.
And However, I could check from Azure dashboard of a VM.

##### ISSUE TYPE
- Feature Idea
Is it possible to add the function to query the configured backup vault name of a VM which already configured

##### COMPONENT NAME
azure.azcollection.azure_rm_backupazurevm_info

##### ADDITIONAL INFORMATION
as above

**Comment by Fred-sun** [comment]
@TomKCTang In PP#1487, you can get all the vaults information under the resource group, and then you can get other related information from the vaults information. Thank you!

**Comment by Fred-sun** [comment]
@TomKCTang #1487 can get all vault names under the resource group and then reuse the vault name. There is no other better way! Thank you!
