### ISSUE TITLE
Can't install azure-cli because of azure-graphrbac

### ISSUE THREAD

**Issue by Poil** [ansible/ansible_collections_azure#1333]
##### SUMMARY
When trying to install same version of azure-cli (CLI) as azure-cli-core in your requirements file we have an error

```
The conflict is caused by:
    The user requested azure-graphrbac==0.61.1
    azure-cli 2.34.0 depends on azure-graphrbac~=0.60.0
```

**Comment by Fred-sun** [comment]
@Poil The azure-graphrbac will deprecated. It will migrate to msgraph. There is no conflict after updated! Now we are working on migrate.

**Comment by Fred-sun** [comment]
azure-graphrbac has been replaced by msgraph-sdk and is no longer installed! Thank you!
