### ISSUE TITLE
azure_rm_virtualmachine_info serialization fails with empty storageUri 

### ISSUE THREAD

**Issue by timmyreilly** [ansible/ansible_collections_azure#137]
##### SUMMARY

The azure_rm_virtualmachine_info isn't properly deserializing a diagnosticsProfile with an empty storage uri. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine_info

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = None
  configured module search path = ['/home/conductor/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/Users/tireilly/GitHub/Spikes/EITC/ansible/venv/lib/python3.6/site-packages/ansible
  executable location = /mnt/c/Users/tireilly/GitHub/Spikes/ansible/venv/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
'' 
```

##### OS / ENVIRONMENT

Windows 10 -> bash 

##### STEPS TO REPRODUCE

Create a vm, get info on vm. 

```yaml
ansible localhost -m azure_rm_virtualmachine_info -a "tags=environment:dev" -vvv
```

##### EXPECTED RESULTS

Expected to get information about vm's in the target subscription 
With `az vm list` I get this: 

```json
$ az vm list
[
  {
    "additionalCapabilities": null,
    "availabilitySet": {
      "id": "/subscriptions/5c514147-secret-4f7e-8329-625443da4254/resourceGroups/NETWORK-TEST-KA6U7-RG/providers/Microsoft.Compute/availabilitySets/MACHINES-SET",
      "resourceGroup": "NETWORK-TEST-KA6U7-RG"
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": false,
        "storageUri": null
      }
    },
```
##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_azure_rm_virtualmachine_info_payload_o2js5d3j/ansible_azure_rm_virtualmachine_info_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine_info.py", line 355, in get_vm
  File "/tmp/ansible_azure_rm_virtualmachine_info_payload_o2js5d3j/ansible_azure_rm_virtualmachine_info_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine_info.py", line 417, in serialize_vm
localhost | FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "name": null,
            "password": null,
            "profile": null,
            "resource_group": null,
            "secret": null,
            "subscription_id": null,
            "tags": [
                "environment:dev"
            ],
            "tenant": null
        }
    },
    "msg": "Error getting virtual machine None - 'storageUri'"
}
```

**Comment by Fred-sun** [comment]
@timmyreilly Thank you for your report, we will investigate and solve your problems as soon as possible. Thank you!

**Comment by Fred-sun** [comment]
fixes by #208!

**Comment by Fred-sun** [comment]
The #208 merged!

**Comment by Chrysostomus** [comment]
I'm getting this exact same issue with version 1.9. I checked that https://github.com/ansible-collections/azure/pull/208 code is present on the installation. Is there something else that could cause the issue?

**Comment by Fred-sun** [comment]
> I'm getting this exact same issue with version 1.9. I checked that #208 code is present on the installation. Is there something else that could cause the issue?

@Chrysostomus Can you provide what results you return? Thank you very much!

**Comment by vijayreddiar** [comment]
@Fred-sun The code fix in _azure_rm_virtualmachine_info.py_ and _azure_rm_virtualmachine.py_ fixes the error related to empty `storageUri`, but I get a new error as below when the setting is _Enable with managed storage account (recommended)_

`Error getting virtual machine None - 'consoleScreenshotBlobUri'`

**Comment by Fred-sun** [comment]
@vijayreddiar Thanks for your feedback, I will check this parameter again. Thank you very much!

**Comment by vijayreddiar** [comment]
@Fred-sun After updating these two lines of code in _azure_rm_virtualmachine_info.py_ as below, it works fine.

```
new_result['boot_diagnostics']['console_screenshot_uri'] = result['properties']['instanceView']['bootDiagnostics'].get('consoleScreenshotBlobUri', None)
new_result['boot_diagnostics']['serial_console_log_uri'] = result['properties']['instanceView']['bootDiagnostics'].get('serialConsoleLogBlobUri', None)
```

**Comment by Fred-sun** [comment]
@vijayreddiar Thank you for your contribution, welcome to submit PR, thank you!
