### ISSUE TITLE
Option in azure_aks_rm module to enable "Azure AD authentication with Azure RBAC"

### ISSUE THREAD

**Issue by Aaron-von-Awesome** [ansible/ansible_collections_azure#1390]
##### SUMMARY

Currently in the `azure_aks_rm` module, when `enable_rbac` is set to `true` then "Azure AD authentication with **Kubernetes** RBAC" is set.  When `enable_rbac` is set to `false` then "Local accounts with Kubernetes RBAC" is set.  

![2024-01-02_Selection_002](https://github.com/ansible-collections/azure/assets/6528788/208569db-6353-4cc3-ac42-86e5c8753a0a)

This feature request is to allow an option to enable "Azure AD authentication with **Azure** RBAC" when provisioning an AKS Cluster.

![2024-01-02_Selection_001](https://github.com/ansible-collections/azure/assets/6528788/e343b098-c1d1-4f6b-be30-1f02b9901f88)

Maybe instead of `enable_rbac` a different property is introduced, like `rbac_mode` which would then have values like "local_kubernetes_rbac", "azure_kubernetes_rbac", and "azure_azure_rbac".  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Module: `azure_aks_rm`

##### ADDITIONAL INFORMATION

The issue I run into is, when deploying an AKS cluster, I would like to be able to set "Azure AD authentication with Azure RBAC" from the Ansible module instead of having to separately run the command from the Azure CLI.

```yaml

```

**Comment by Fred-sun** [comment]
Added in #1677
