### ISSUE TITLE
Add azure_rm_publicipprefix

### ISSUE THREAD

**Issue by Nothing4You** [ansible/ansible_collections_azure#1398]
##### SUMMARY
Like `azure_rm_publicipaddress`, `azure_rm_publicipprefix` should exist.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_publicipprefix 

##### ADDITIONAL INFORMATION
Public IP prefixes can't currently be created using Ansible.

https://learn.microsoft.com/azure/virtual-network/ip-services/public-ip-address-prefix

**Comment by Fred-sun** [comment]
Added in #1403
