### ISSUE TITLE
azure_rm_adapplication available_to_other_tenants parameter does not work and has incorrect type

### ISSUE THREAD

**Issue by cobbr** [ansible/ansible_collections_azure#1400]
##### SUMMARY
The `available_to_other_tenants` module has a parameter `available_to_other_tenants` with an incorrect type, causing it to not function properly. It is labeled as a bool, but the msgraph APIs expect a `str`.

Further, it does appear that `available_to_other_tenants` should be renamed to a `sign_in_audience` parameter with type `str`, limited to a few choices. The valid choices for `signInAudience` can be found here: https://learn.microsoft.com/en-us/entra/identity-platform/supported-accounts-validation

They are: `AzureADMyOrg`, `AzureADMultipleOrgs`, `AzureADandPersonalMicrosoftAccount`, `PersonalMicrosoftAccount`.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`azure_rm_adapplication`

##### ANSIBLE VERSION
```
ansible [core 2.15.6]
  config file = /path/playbooks/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /path/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /path/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/path/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
$ ansible-galaxy collection list azure.azcollection

# /home/ubuntu/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.1.1
```

##### OS / ENVIRONMENT
Ubuntu 22.04

##### STEPS TO REPRODUCE
```
- name: Create AzureAD applications
  azure.azcollection.azure_rm_adapplication:
    auth_source: cli
    tenant: "{{ tenant }}"
    display_name: TestApp
    available_to_other_tenants: no
```

##### EXPECTED RESULTS
Application will still be available to other tenants or personal microsoft accounts.

##### ACTUAL RESULTS
Application will still be available to other tenants, despite `available_to_other_tenants: no`, because the msgraph API is not expecting a bool and defaults to allowing personal microsoft accounts.

**Comment by Fred-sun** [comment]
@cobbr Fixed by #1401

**Comment by cobbr** [comment]
@Fred-sun Looks great! Just a suggestion, might be worth changing the name of the parameter to `sign_in_audience` with a `available_to_other_tenants` alias for compatibility purposes.

**Comment by Fred-sun** [comment]
@cobbr Sounds great. If we change the name and it has a big impact on our current users, we'll think about it again. Thank you!
