### ISSUE TITLE
azure_rm_keyvaultsecret_info doesn't return secrets value (just list)

### ISSUE THREAD

**Issue by klemen-df** [ansible/ansible_collections_azure#1402]
##### SUMMARY
When using 'azure_rm_keyvaultsecret_info' and not specifying 'name' a list of all of the secrets in the keyvault is returned - but the list does not contain the secrets value.

In the [documentation page](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_keyvaultsecret_info_module.html) there is nothing written that the secrets value isn't/shouldn't be included in the list - is this a bug or a feature?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
azure_rm_keyvaultsecret_info

##### ANSIBLE VERSION

```paste below
2.16.2
```

**Comment by Fred-sun** [comment]
@KlemenDanfoss From your return, it appears that you did not establish a connection with keyvault and obtain secret information, You can refer to connect (https://jd-bots.com/2021/07/27/fixed-the-operation-list-is-not-enabled-in-this-key-vaults-access-policy/), To list your secret. Thank you!
```e.g.
I can obtain all the secrets under keyvault on the local computer
        "secrets": [
            {
                "attributes": {
                    "created": "2024-01-11T10:42:25+00:00",
                    "enabled": true,
                    "expires": "2030-03-04T04:05:06+00:00",
                    "not_before": "2000-01-02T01:02:03+00:00",
                    "recovery_level": "Recoverable+Purgeable",
                    "updated": "2024-01-11T10:42:25+00:00"
                },
                "sid": "https://vaulttest00fre3.vault.azure.net/secrets/testsecret02",
                "tags": {
                    "delete": "on-exit",
                    "testing": "test"
                },
                "version": null
            },
            {
                "attributes": {
                    "created": "2024-01-11T10:43:08+00:00",
                    "enabled": true,
                    "expires": "2030-03-04T04:05:06+00:00",
                    "not_before": "2000-01-02T01:02:03+00:00",
                    "recovery_level": "Recoverable+Purgeable",
                    "updated": "2024-01-11T10:43:08+00:00"
                },
                "sid": "https://vaulttest00fre3.vault.azure.net/secrets/testsecret03",
                "tags": {
                    "delete": "on-exit",
                    "testing": "test"
                },
                "version": null
            }
        ]

**Comment by klemen-df** [comment]
Yes, this works. But the actual value of the secret is not returned here?

**Comment by Fred-sun** [comment]
> Yes, this works. But the actual value of the secret is not returned here?

Yes, We can get all the secrets, and if you want to get the version, you can do it by ‘secret_name’ and  'kevault_uri'. Thank you very much!
