### ISSUE TITLE
Community package requirements: sanity tests

### ISSUE THREAD

**Issue by gotmax23** [ansible/ansible_collections_azure#1417]
# Community package requirements: sanity tests

(Note: This issue was filed in a semi-automated fashion. Let me know if you see errors in this issue.)

As per the [Ansible community package inclusion requirements][ci-testing], collections must pass `ansible-test sanity` tests. Version `1.19.0` of `azure.azcollection`, corresponding to the `v1.19.0` tag in this repo, fails one or more of the required sanity tests.

Please see the errors below and address them. If these issues aren't addressed within a reasonable time period, the collection may be subject to [removal from Ansible][removal].

Thank you for your efforts and for being part of the Ansible package! We appreciate it.

---

## Sanity tests

The following tests were run using `ansible-test` version `2.16.1`:

- ansible-doc
- compile
- validate-modules
- yamllint

Note that this is only a subset of the required sanity tests. Please make sure you run them in all in your CI.

### Results

> **💡 NOTE:**
>
> Check the `[explain]` links below for more information about each test and how to fix failures.
> See [Sanity Tests: Ignores](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ignores.html) in the dev guide if, after reading the test-specific documentation, you still believe an error is a false positive.

*This issue has been truncated. [Click here to read more](https://gist.github.com/gotmax23/3315623a219a0b2a260e8ef44fb37ceb).*

[ci-testing]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#ci-testing
[repo-mgmt]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#repository-management
[removal]: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst

**Comment by Fred-sun** [comment]
@gotmax23 The CI/CD tested  integrated in the pipeline, run and detect all use cases every Friday (https://github.com/ansible-collections/azure/blob/dev/tests/utils/ado/ado.sh), using ansible-test, ansible-playbook, and ansible-lint to detect inheritance tests, use cases, and play formats. Thank you!

**Comment by Fred-sun** [comment]
@gotmax23 Those that were skipped were fixed by #1388 and will be applied in the next release. Thank you!
