### ISSUE TITLE
Allow an OS disk blob URI as source in azure_rm_galleryimageversion

### ISSUE THREAD

**Issue by christianmasopust** [ansible/ansible_collections_azure#1437]
##### SUMMARY
Maybe I'm doing it wrong, but it seems that it is not allowed to specify an OS disk blob URI as source in storage_profile in azure_rm_galleryimageversion. Should work similar as it is implemented in azure_rm_image.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_galleryimageversion

##### ADDITIONAL INFORMATION
We are uploading vhd files to an Azure blob storage and would like to directly use these files when creating a new gallery image version.

**Comment by Fred-sun** [comment]
Added in #1466
