### ISSUE TITLE
version 2.2.0 does not have `Release`

### ISSUE THREAD

**Issue by akira6592** [ansible/ansible_collections_azure#1444]
##### SUMMARY

The collection version [2.2.0 has released](https://galaxy.ansible.com/ui/repo/published/azure/azcollection/?version=2.2.0), but does not have [Release](https://github.com/ansible-collections/azure/releases).

This could mislead visitors to this repository into thinking that 2.2.0 has not yet been released.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
N/A
```

##### COLLECTION VERSION

```paste below
N/A
```

##### CONFIGURATION

```paste below
N/A
```

##### STEPS TO REPRODUCE

```yaml
N/A
```

##### ACTUAL RESULTS

```paste below
N/A
```

**Comment by Fred-sun** [comment]
@akira6592 We are very sorry for the trouble caused to you. We will check as soon as possible why it is not in the release version. Thank you!

**Comment by Fred-sun** [comment]
@xuzhang3 Could you please help check that there is no release in the packaged file? Thank you very much!

**Comment by Fred-sun** [comment]
@akira6592 Already added! Thank you very much!

**Comment by akira6592** [comment]
Thank you!
