### ISSUE TITLE
Support storage account lifecycle management policies

### ISSUE THREAD

**Issue by emanueleaina** [ansible/ansible_collections_azure#1453]
##### SUMMARY
Let users set/update/delete a lifecycle management policy on storage accounts:

* docs: https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-policy-configure?tabs=azure-portal
* API: https://learn.microsoft.com/en-us/rest/api/storagerp/management-policies/create-or-update?view=rest-storagerp-2023-01-01&tabs=Python

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Maybe something like `azure_rm_storageaccountmanagementpolicy`?

##### ADDITIONAL INFORMATION
At the moment we are shelling out to the ` az storage account management-policy create` command line, but it is definitely suboptimal. In particular, it does not support diff mode.

**Comment by Fred-sun** [comment]
@em- There is a life cycle management issue that is not deserializing the response data, and I am trying to figure out why. Thank you!

**Comment by Fred-sun** [comment]
@em- Support in #1536
