### ISSUE TITLE
Return value not available anymore in azure_rm_networkinterface_info

### ISSUE THREAD

**Issue by murdibb** [ansible/ansible_collections_azure#1461]
Hi all,

I wanted to use subnet id from return value ['azure_networkinterfaces '](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_networkinterface_info_module.html#return-azure_networkinterfaces) but it is not available anymore.
For me it seems it was part of predecessor 'azure_rm_networkinterface_facts', and is only added when called from that old module
https://github.com/ansible-collections/azure/blob/9cfb3777de2599066fbacda4881e28d2b2f6248e/plugins/modules/azure_rm_networkinterface_info.py#L342-L347

Please check and add it back or remove from documentation.
https://github.com/ansible-collections/azure/blob/9cfb3777de2599066fbacda4881e28d2b2f6248e/plugins/modules/azure_rm_networkinterface_info.py#L66C1-L66C24

Btw. any recommendation how to get subnet id from this module only? I get it that it can be combined with ['azure_rm_subnet_info'](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_subnet_info_module.html)

Thanks!

**Comment by Fred-sun** [comment]
@murdibb You can obtain the subnet ID in the following two ways, hank you!
```e.g.
Print the subnet ID in the return value from azure_rm_subnet_info.py 
- name: Get subnet facts
  azure_rm_subnet_info:
    name: foobar
    virtual_network_name: My_Virtual_Network
    resource_group: "{{ resource_group }}"
  register: output
- name: Print the subnet ID in the return value from azure_rm_subnet_info.py
  debug:
    var: output.subnets[0].id

Print the subnet ID in the return value from azure_rm_subnet_info.py 
- name: Get virtual network fact
  azure_rm_virtualnetwork_info:
    name: My_Virtual_Network
    resource_group: "{{ resource_group }}"
  register: output

- name: Print the subnet ID in the return value from azure_rm_virtualnetwork_info.py
  debug:
    var: output.virtualnetworks[0].subnets

**Comment by murdibb** [comment]
@Fred-sun thanks for your answer!
To be precise, I want to get the subned id of a NIC so only your first suggestion applies. Yes I knew I can use that module to get subnet information.

Anyways the original issue is that the documentation and actual behaviour are not aligned for azure_rm_networkinterface_info. It would be cool to only use that single module to get subnetinfo, as subnet ID is usually needed on firewalls (keyvault, storage etc)

**Comment by Fred-sun** [comment]
@murdibb Yes, azure_rm_networkinterface_info does not return the subnet ID. However, we can obtain the subnet ID from the virtual network information returned by this module. We will add subnet information to the returned network card information later. Thank you!
