### ISSUE TITLE
azure collection with ansible automation platform giving some errors

### ISSUE THREAD

**Issue by vasiredp** [ansible/ansible_collections_azure#1465]
Using recent azcollection 2.0.0 and servicebustopic module with ansible automation controller giving below error.
also configured credentails section in template . but why getting auth error

{
  "msg": "Error creating or updating topic prasanthtest2 - None",
  "exception": "  File \"/tmp/ansible_azure.azcollection.azure_rm_servicebustopic_payload_gt7kyf91/ansible_azure.azcollection.azure_rm_servicebustopic_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_servicebustopic.py\", line 248, in create_or_update\n  File \"/usr/local/lib/python3.9/site-packages/azure/mgmt/servicebus/v2021_06_01_preview/operations/_topics_operations.py\", line 625, in create_or_update\n    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py\", line 213, in run\n    return first_node.send(pipeline_request)\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py\", line 70, in send\n    response = self.next.send(request)\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py\", line 70, in send\n    response = self.next.send(request)\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py\", line 70, in send\n    response = self.next.send(request)\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py\", line 47, in send\n    response = self.next.send(request)\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py\", line 181, in send\n    response = self.next.send(request)\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py\", line 467, in send\n    response = self.next.send(request)\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py\", line 113, in send\n    self.on_request(request)\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py\", line 90, in on_request\n    self._token = self._credential.get_token(*self._scopes)\n  File \"/usr/local/lib/python3.9/site-packages/azure/identity/_internal/get_token_mixin.py\", line 83, in get_token\n    token = self._acquire_token_silently(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/azure/identity/_internal/decorators.py\", line 84, in wrapper\n    raise auth_error from ex\n",
  "invocation": {
    "module_args": {
      "resource_group": "E2EMonitoring",
      "namespace": "mfcsbusazure",
      "name": "prasanthtest2",
      "auth_source": "auto",
      "cloud_environment": "AzureCloud",
      "api_profile": "latest",
      "state": "present",
      "profile": null,
      "subscription_id": null,
      "client_id": null,
      "secret": null,
      "tenant": null,
      "ad_user": null,
      "password": null,

**Comment by Fred-sun** [comment]
@vasiredp This error occurs when you get your authorization to create a 'service bus topic'. Can you check that the subscritpion you're using has permission to manage the service bus? Also, what kind of 'credentials' do you use? Thank you !

**Comment by vasiredp** [comment]
when i use ansible azure collection in execution environment of version 1.17 my playbook is working fine without any auth errors.
when i use azure collection 2.0 then my playbook is getting auth errors. it means it is not about access issue.
something was changed in azure collection module in ansible from 1.17 to 2.0 in AAP

**Comment by Fred-sun** [comment]
@vasiredp I tested with the latest version of Aze. azcollection and the test results passed. Here are my use cases and test results. Thank you!
```e.g.
azure.azcollection version:
azureuser@fredVM:~/topic$ ansible-galaxy collection list azure.azcollection

# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.14.0

# /home/azureuser/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.2.0

test case:
- name: Create a namespace
  azure_rm_servicebus:
    name: "ns{{ rpfx }}"
    resource_group: "{{ resource_group }}"
    sku: premium
    tags:
      key1: value1
  register: namespace

- name: Create a topic
  azure_rm_servicebustopic:
    name: "topic{{ rpfx }}"
    resource_group: "{{ resource_group }}"
    namespace: "ns{{ rpfx }}"
    duplicate_detection_time_in_seconds: 600
    max_message_size_in_kb: 2048
    max_size_in_mb: 2048
  register: output

result:
TASK [Create a namespace] **********************************************************************************************
changed: [localhost]

TASK [Create a topic] **************************************************************************************************
changed: [localhost]

**Comment by vasiredp** [comment]
Is it tested in Ansible automation controller platform or in opensource ansible .
May i know what about azure collections 2.0 ?

**Comment by Fred-sun** [comment]
@vasiredp The creation is successful. Thank you!
![image](https://github.com/ansible-collections/azure/assets/37327967/51847f81-4ed9-4620-a55d-474fd33165af)

**Comment by vasiredp** [comment]
Thanks Fred.
 we are actually using Automation hub and automation controller in place .
i am suspecting some thing about execution environment configured in ansible automation controller.  will try to check and any suggestions on checking this collections or its dependencies.

**Comment by Fred-sun** [comment]
@vasiredp If there are no further problems, I will shut him down. You are welcome to submit new questions. Thank you!
