### ISSUE TITLE
azure.azcollection.azure_rm_adgroup module Should allow for setting the description of the group

### ISSUE THREAD

**Issue by hematic** [ansible/ansible_collections_azure#1485]
##### SUMMARY
azure.azcollection.azure_rm_adgroup module doesnt allow for specifying a group description which is a key thing for maintainability fo AD groups.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_adgroup module

##### ADDITIONAL INFORMATION
This feature would allow for people to specify things like wqho requested the group, its purpose, its intended lifespan etc.

**Comment by Fred-sun** [comment]
Added in #1492
