### ISSUE TITLE
azure_rm_servicebus_info module return error for Azure service bus where private end point connection IPs are enabled 

### ISSUE THREAD

**Issue by vasiredp** [ansible/ansible_collections_azure#1502]
verified with latest azure collecitons and old collections also . noticed below error when Azure service bus is having private end point connection enabled  azure_rm_servicebus_info is getting below error

47ublq/ansible_azure.azcollection.azure_rm_servicebus_info_payload.zip/ansible/module_utils/common/parameters.py\", line 931, in remove_values\n  File \"/tmp/ansible_azure.azcollection.azure_rm_servicebus_info_payload_f_47ublq/ansible_azure.azcollection.azure_rm_servicebus_info_payload.zip/ansible/module_utils/common/parameters.py\", line 470, in _remove_values_conditions\nTypeError: Value of unknown type: <class 'azure.mgmt.servicebus.v2021_06_01_preview.models._models_py3.PrivateEndpointConnection'>, {'additional_properties': {'location': 'japaneast'}, 'id': '/subscriptions/aa5598d5-ed35-4885-aefb-805c3cca99eb/resourceGroups/JPE-JPIS-UAT-01/providers/Microsoft.ServiceBus/namespaces/mfcsbusjpcompreprodjpe01/privateEndpointConnections/e3fa66c1-0b58-43df-922d-4425e57bbd3e', 'name': 'e3fa66c1-0b58-43df-922d-4425e57bbd3e', 'type': 'Microsoft.ServiceBus/Namespaces/PrivateEndpointConnections', 'system_data': None, 'private_endpoint': <azure.mgmt.servicebus.v2021_06_01_preview.models._models_py3.PrivateEndpoint object at 0x7f46500b61f0>, 'private_link_service_connection_state': <azure.mgmt.servicebus.v2021_06_01_preview.models._models_py3.ConnectionState object at 0x7f46500b6400>, 'provisioning_state': 'Succeeded'}\n",
  "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1710399189.6976047-40-127439816987669/AnsiballZ_azure_rm_servicebus_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1710399189.6976047-40-127439816987669/AnsiballZ_azure_rm_servicebus_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1710399189.6976047-40-127439816987669/AnsiballZ_azure_rm_servicebus_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_servicebus_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_servicebus_info', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_servicebus_info_payload_f_47ublq/ansible_azure.azcollection.azure_rm_servicebus_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_servicebus_info.py\", line 582, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_servicebus_info_payload_f_47ublq/ansible_azure.azcollection.azure_rm_servicebus_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_servicebus_info.py\", line 578, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_servicebus_info_payload_f_47ublq/ansible_azure.azcollection.azure_rm_servicebus_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_servicebus_info.py\", line 435, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_servicebus_info_payload_f_47ublq/ansible_azure.azcollection.azure_rm_servicebus_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 473, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_servicebus_info_payload_f_

**Comment by Fred-sun** [comment]
Fixed by #1503
