### ISSUE TITLE
Add Python 3.12+ ARM support - Blocked by azure-iot-hub > uamqp requirements

### ISSUE THREAD

**Issue by gygitlab** [ansible/ansible_collections_azure#1505]
##### SUMMARY
Currently Python 3.12 is not supported for this collection by proxy due to the requirement of [`azure-iot-hub`](https://github.com/Azure/azure-iot-hub-python/) that in turn [requires `uamqp`](https://github.com/Azure/azure-iot-hub-python/blob/main/setup.py#L80).

[`azure-uamqp-python`](https://github.com/Azure/azure-uamqp-python) is no longer in active development and is planned to be deprecated early in 2025. As such it's not currently possible to install this package with Python 3.12 on ARM systems such as Mac either from source or wheel.

This in turn prevents this whole collection from being installed on ARM systems running with Python 3.12+. Looking forward having a solution in place for 3.12+ systems would be prudent, perhaps adjusting or removing `azure-iot-hub` to be installed by default would be a possible first step.

**Comment by gygitlab** [comment]
Hey @Fred-sun any updates on this (and https://github.com/ansible-collections/azure/issues/1511) or any sort of timeline?

[As discussed](https://github.com/ansible-collections/azure/pull/1512#issuecomment-2020075999) it's not possible to install the Ansible collection's dependencies on both Mac ARM on Python 3.11+ and Linux ARM on Python 3.12.

**Comment by Fred-sun** [comment]
@gygitlab This issue seems to occur only on python version > 3.11, which is still being worked out. Thank you!

**Comment by g3rhard** [comment]
My coin there - for some reasons, I got the same issue with Python 3.10/3.11/3.12.

**Comment by ssbarnea** [comment]
The problem is not not mac specific, reproduces with linux to as long the arch is `aarch64`.

Maybe as temporary measure, in order to allow packaging and installation of this collection on all supported platforms, I suggest making this component optional, basically changing to something like:
```
azure-iot-hub==2.6.1;platform_machine=="x86_64"
```

**Comment by xuzhang3** [comment]
more details https://github.com/Azure/azure-uamqp-python/issues/386
