### ISSUE TITLE
azure_rm_sqldatabase lacks critical functionality

### ISSUE THREAD

**Issue by mrwalters1988** [ansible/ansible_collections_azure#153]
##### SUMMARY

Currently we are: 
    - Unable to specify a SKU
    - Unable to deploy vCores
    - Unable to create an elastic pool
    - Creating elastic pools using azure_rm_resource works, but when we want to add new databases to pool, we have to rerun the deployment
    - Unable to utilize hyperscale

We would like all of these capabilities added. 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_sqldatabase
##### ADDITIONAL INFORMATION

Should be self explanatory from above. These are all values needed to configure a sql database, however there's no documented method of doing so.

**Comment by Fred-sun** [comment]
@mrwalters1988 Thanks for you submit the issue.  we will investigate those feature！ Thank you very much!

**Comment by guyomog78** [comment]
Hello,

I have the same SKU need. The Edition option is not fonctionnal.
I already have started some test to load the SKU class from azure.mgmt.sql.models and added the parameters SKU under the self.parameters object.

Currently, I'm still using the edition définition, Only Basic and Free values are compatible. for other SKU like S0, S1..., it's necessary to replace Edition with sku and, why not the SKU dict...

I have not tested with the Python module azure-mgmt-sql 0.10.0, but with the azure-mgmt-sql 0.21.0

Is there some restriction to stay with the 0.10.0 version?
