### ISSUE TITLE
The `network_profile.outbound_type` property of the `azure_rm_aks` module does not accept `managedNATGateway`/`userAssignedNATGateway`

### ISSUE THREAD

**Issue by emanueleaina** [ansible/ansible_collections_azure#1533]
##### SUMMARY
At the moment [the `network_profile.outbound_type` property of the `azure_rm_aks` module](github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_aks.py#L813) only accepts `userDefinedRouting` and `loadBalancer`, but `managedNATGateway` and `userAssignedNATGateway` should be allowed too, see https://learn.microsoft.com/en-us/azure/aks/nat-gateway.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`azure_rm_aks`

##### COLLECTION VERSION
```
$ ansible-galaxy collection list azure.azcollection

# /usr/share/ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.19.0
```

##### STEPS TO REPRODUCE
Set the the `network_profile.outbound_type` property of the `azure_rm_aks` module to  `userAssignedNATGateway`.

##### EXPECTED RESULTS
No error

##### ACTUAL RESULTS
```
fatal: [cluster_001]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  msg: 'value of outbound_type must be one of: userDefinedRouting, loadBalancer, got: userAssignedNATGateway found in network_profile'
```

**Comment by Fred-sun** [comment]
@em- Added in #1537
