### ISSUE TITLE
azure_rm inventory plugin should populate a `zone` hostvar

### ISSUE THREAD

**Issue by wrprice** [ansible/ansible_collections_azure#161]
##### SUMMARY

The `azure_rm` inventory plugin populates many basic properties about a VM, such as `location`, `resource_group`, `vmss`, etc.  However, **availabilty zone** is a serious oversight (missing on Ansible 2.9.9), and complicates host groupings for playbooks applying rolling updates across zones without resorting to things like (fragile) naming conventions, or running metadata queries on the hosts directly.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm (Azure Resource Manager inventory plugin)

**Comment by Fred-sun** [comment]
@wrprice Thank you very much for submitting this problem. We will investigate it. Thank you very much!

**Comment by ShwetaliBerad** [comment]
I will be working on it

**Comment by Fred-sun** [comment]
fixed by #243
