### ISSUE TITLE
azure_rm_storageaccount_info needed azure.mgmt.datalake

### ISSUE THREAD

**Issue by fentonfentonfenton** [ansible/ansible_collections_azure#1612]
##### SUMMARY

I think https://github.com/ansible-collections/azure/blob/dev/CHANGELOG.md may have had negative effects on `azure_rm_storageaccount_info` also might be user error.

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure_rm_storageaccount_info_payload_xyhqiy5h/ansible_azure_rm_storageaccount_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 254, in <module>
    from azure.mgmt.datalake.store import DataLakeStoreAccountManagementClient
ModuleNotFoundError: No module named 'azure.mgmt.datalake'
``` 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`azure_rm_storageaccount_info` / `azure.mgmt.datalake`

##### COLLECTION VERSION

```paste below
2.4.0
```

##### EXPECTED RESULTS
no regression

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure_rm_storageaccount_info_payload_xyhqiy5h/ansible_azure_rm_storageaccount_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 254, in <module>
    from azure.mgmt.datalake.store import DataLakeStoreAccountManagementClient
ModuleNotFoundError: No module named 'azure.mgmt.datalake'
```

**Comment by Fred-sun** [comment]
@fentonfentonfenton Datalake store gen1 has been abandoned, datalake store gen2 is enabled as a service for storing account namespaces, so we have removed azure-mgmt-datalake-store and related modules(https://github.com/ansible-collections/azure/pull/1555). I suggest you reinstall the latest version to try, thank you!

**Comment by fentonfentonfenton** [comment]
> @fentonfentonfenton Datalake store gen1 has been abandoned, datalake store gen2 is enabled as a service for storing account namespaces, so we have removed azure-mgmt-datalake-store and related modules(#1555). I suggest you reinstall the latest version to try, thank you!

Thanks, we don't pin version (so using latest) so I think this won't solve it for us.

**Comment by Fred-sun** [comment]
@fentonfentonfenton However, azure-mgmt-datalake-store has been abandoned and we are not installing it, so this dependency issue should not arise. Thank you!
