### ISSUE TITLE
[azure_rm_publicipaddress] Add support for setting reverse_fqdn on public IPv4 addresses

### ISSUE THREAD

**Issue by tsmithCmdlnk** [ansible/ansible_collections_azure#1655]
##### SUMMARY

Microsoft supports setting the RDNS or Reverse DNS value for public IPv4 addresses, [docs](https://learn.microsoft.com/en-us/azure/dns/dns-reverse-dns-for-azure-services).
Currently the return values for both `azure_rm_publicipaddress` and `azure_rm_publicipaddress_info` support getting the currently set `reverse_dns` value via the `dns_settings` object but there is no way to actually set that field without resorting to `azure_rm_resource`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`azure_rm_publicipaddress`

**Comment by Fred-sun** [comment]
Add by #1655
