### ISSUE TITLE
snapshot_info module

### ISSUE THREAD

**Issue by Michandrz** [ansible/ansible_collections_azure#1658]
##### SUMMARY
Info version of the snapshot module. To be able to pull information on snapshots without a change similar to the vm_info and disks_info etc.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure.azcollection.azure_rm_snapshot_info

##### ADDITIONAL INFORMATION
I am using it to identify information about snapshots.

```
- name: Load all Snapshots in RG
   azure.azcollection.azure_rm_snapshot_info:
   register: loaded_snapshot_info
 
- name: example
  debug:
    msg: make logical choices and verify states etc.
```

**Comment by Fred-sun** [comment]
Added by #1659
