### ISSUE TITLE
azure_rm_virtualmachine_info - need Object ID - Type SystemAssigned

### ISSUE THREAD

**Issue by pc-dok** [ansible/ansible_collections_azure#1671]
Hi all

I can not retrieve from a Azure Virtual Machine the azure_rm_virtualmachine module - vm identity type - when i try to find out this information with the azure_rm_virtualmachine_info module. i am not sure how to find out this ID in general. i setup it in the vm module but i am not able to retrieve this id in any why in a ansible playbook. can you add the vm_identity also into the vm info module? is sometimes needed when you try to get certificates from a azure key vault etc...

regards
franco

**Comment by Fred-sun** [comment]
@pc-dok Do you mean to get identity information in azure_rm_virtualmachine_info.py? Like the following?
```e.g.
 "idenity": {
                    "principal_id": "xxxxxxxxxxxxx",
                    "tenant_id": "xxxxxxxxxxxxxxxx",
                    "type": "SystemAssigned, UserAssigned",
                    "user_assigned_identities": {
                        "/subscriptions/xxxxxxxxxxxxxx/resourceGroups/testRG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test": {
                            "client_id": "xxxxxxxxxx",
                            "principal_id": "xxxxxxxxxxxxxx"
                        }
                    }
                }

**Comment by pc-dok** [comment]
yes exactly this is what i need, the principal id, to assign with this ID later a role assignment for the keyvault. is that possible for the info module?

regards
franco
