### ISSUE TITLE
Agent Pool should allow setting a Taint

### ISSUE THREAD

**Issue by kbocock-krg** [ansible/ansible_collections_azure#1684]
[ ]

##### SUMMARY

AKS node pools have the ability to test a list of taints but this parameter seems to be missing from the azure.azcollection.azure_rm_aksagentpool
##### ISSUE TYPE
- Feature Idea
support this setting with a list of string similar to TF. 
##### COMPONENT NAME

azure.azcollection.azure_rm_aksagentpool
##### ADDITIONAL INFORMATION

When creating the aks agent pool the user can specify n or n+1 taints

```yaml

taints: 
   - "nodeType=testy:NoSchedule"

```

**Comment by Fred-sun** [comment]
Added in #1685
