### ISSUE TITLE
Any plan to add parameters network_access_policy and public_network_network_access to azure_rm_manageddisk ?

### ISSUE THREAD

**Issue by cmasopust** [ansible/ansible_collections_azure#1778]
##### SUMMARY
One of our policies is that managed disks must not allow public network access. So it would be great to be able to specify this during creation of such managed disk.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- azure_rm_manageddisk
- azure_rm_multiplemanageddisks

##### ADDITIONAL INFORMATION
if that would be able during creation of the managed disks it would simplify our use case. currently we need to modify the created disk manually (or by a native azure API call)

**Comment by Fred-sun** [comment]
Added in #1782
