### ISSUE TITLE
InvalidApiVersionParameter\nMessage: The api-version '2017-05-01-preview' is invalid

### ISSUE THREAD

**Issue by nac-sn** [ansible/ansible_collections_azure#188]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

ansible 2.9.7
  config file = None
  configured module search path = [u'/home/kaveri/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]

##### OS / ENVIRONMENT

ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml

- hosts: localhost
  vars:
    resource_group: xxx
    providers: Microsoft.ApiManagement
    diagnostic: xxx
  tasks:
    - name: samople
      azure_rm_resource_info:
        api_version: '2017-05-01-preview'
        resource_type: resourcegroups/xxx/providers/Microsoft.ApiManagement/service
        resource_name: xxx
        subresource:
          - type: microsoft.insights/diagnosticSettings
            name: "{{ diagnostic }}"


##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
expected to get diagnostic setting list

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

InvalidApiVersionParameter\nMessage: The api-version '2017-05-01-preview' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1

**Comment by Fred-sun** [comment]
@nac-sn This is not a Bug, and the actual information returned shows that the api-version you defined is not supported. The version currently supported is: 2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04. Please update the api-version and try again, thank you!

**Comment by Fred-sun** [comment]
kinldy ping!

**Comment by Fred-sun** [comment]
not a bug! parameter error!
