### ISSUE TITLE
azure_rm_securitygroup should support attaching to a virtual network

### ISSUE THREAD

**Issue by aardbol** [ansible/ansible_collections_azure#191]
##### SUMMARY

See title. There's no current way to do so on creation of the NSG.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_securitygroup

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by Fred-sun** [comment]
@aardbol Thank you for reporting this question. This is a new feature requirement and I will investigate it. Thank you very much!

**Comment by aardbol** [comment]
I was mistaken. A NSG can only be attached to a subnet, next to a NIC, and it's already supported by this module. I confused the subnet with the VNET.
