### ISSUE TITLE
Inventory azure_rm should populate subnet of VMs

### ISSUE THREAD

**Issue by Tomelin** [ansible/ansible_collections_azure#206]
SUMMARY
The azure_rm inventory plugin populates many basic properties about a VM, such as location, resource_group, vmss, etc. However, the subnet is a serious oversight (missing on Ansible 2.9.9), and complicates host groupings for playbooks applying rolling updates across subnet without resorting to things like (fragile) naming conventions, or running metadata queries on the hosts directly.

ISSUE TYPE
Feature Idea
COMPONENT NAME
azure_rm (Azure Resource Manager inventory plugin)

**Comment by Fred-sun** [comment]
@Tomelin Thank you for submitting this question, we will investigate. Thank you!

**Comment by Fred-sun** [comment]
@Tomelin  Added in #1422
