### ISSUE TITLE
azure_rm_virtualmachine: Unable to delete all components even if remove_on_absent set to all

### ISSUE THREAD

**Issue by Udayendu** [ansible/ansible_collections_azure#222]
##### SUMMARY
**remove_on_absent** parameter is set to `all` in **azure_rm_virtualmachine** module but still ansible is unable to delete all the components. Security group is not removed. Its able to delete only the managed disk, network interface, public_ip and the vm.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- azure_rm_virtualmachine

##### ANSIBLE VERSION
```
 # ansible --version
ansible 2.9.11
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### OS / ENVIRONMENT
- Ubuntu 20.04 LTS

##### STEPS TO REPRODUCE
- Make sure to have a fully configured instance on azure platform with managed hdd, nsg and public_ip.
- Then use the below playbook to delete the instance
- It will delete everything except the security group

```
---
- name: Delete the Web Server
  hosts: localhost
  connection: local
  vars_files:
    - azure-vars.yaml

  tasks:
  - name: Delete "{{ web_server }}" virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ web_server }}"
      remove_on_absent: all
      state: absent
```

##### EXPECTED RESULTS
It should delete all the components of the instance along with it.

##### ACTUAL RESULTS
Its not able to delete the security group but removing everything else.
Debug out put of playbook:

```
changed: [localhost] => {
    "ansible_facts": {
        "azure_vm": null
    },
    "changed": true,
    "deleted_managed_disk_ids": [
        "/subscriptions/xxxxxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Compute/disks/Web-Server-01"
    ],
    "deleted_network_interfaces": [
        {
            "name": "webnic",
            "resource_group": "xxxxxxxxx"
        }
    ],
    "deleted_public_ips": [
        {
            "name": "websrv-public-ip",
            "resource_group": "xxxxxxxxx"
        }
    ],
    "deleted_vhd_uris": [],
    "invocation": {
        "module_args": {
            "accept_terms": false,
            "ad_user": null,
            "adfs_authority_url": null,
            "admin_password": null,
            "admin_username": null,
            "allocated": true,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "availability_set": null,
            "boot_diagnostics": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "custom_data": null,
            "data_disks": null,
            "generalized": false,
            "image": null,
            "license_type": null,
            "location": null,
            "managed_disk_type": null,
            "name": "Web-Server-01",
            "network_interface_names": null,
            "open_ports": null,
            "os_disk_caching": "ReadOnly",
            "os_disk_name": null,
            "os_disk_size_gb": null,
            "os_type": "Linux",
            "password": null,
            "plan": null,
            "profile": null,
            "public_ip_allocation_method": "Static",
            "remove_on_absent": [
                "all"
            ],
            "resource_group": "xxxxxxxxx",
            "restarted": false,
            "secret": null,
            "short_hostname": null,
            "ssh_password_enabled": true,
            "ssh_public_keys": null,
            "started": true,
            "state": "absent",
            "storage_account_name": null,
            "storage_blob_name": null,
            "storage_container_name": "vhds",
            "subnet_name": null,
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "virtual_network_name": null,
            "virtual_network_resource_group": null,
            "vm_identity": null,
            "vm_size": null,
            "winrm": null,
            "zones": null
        }
    },
    "powerstate_change": null
}
META: ran handlers
META: ran handlers
```

**Comment by Fred-sun** [comment]
@Udayendu Because some resources are Shared with other virtual machines or services, it is not possible to force deletion in one direction. The temporary design logic is such that changes may be made as required later. So it's not a Bug. Thank you very much!

**Comment by Udayendu** [comment]
> @Udayendu Because some resources are Shared with other virtual machines or services, it is not possible to force deletion in one direction. The temporary design logic is such that changes may be made as required later. So it's not a Bug. Thank you very much!

Okey. In that case we should validate if the disk is shared with other resources or not. If shared, skip with a message. Else delete it.

**Comment by Fred-sun** [comment]
> > @Udayendu Because some resources are Shared with other virtual machines or services, it is not possible to force deletion in one direction. The temporary design logic is such that changes may be made as required later. So it's not a Bug. Thank you very much!
> 
> Okey. In that case we should validate if the disk is shared with other resources or not. If shared, skip with a message. Else delete it.

@Udayendu Please refer issue https://github.com/ansible/ansible/issues/30392 . Referring to Yuwzho's comments, she explains why there is no need to delete the NSG. If you have no other questions. I'm going to close the question. Thank you very much!
