### ISSUE TITLE
async status returns false evenif job is finished

### ISSUE THREAD

**Issue by KrishnaG-MSFT** [ansible/ansible_collections_azure#227]
I have an ansible code written to execute vm extensions(powershell code) in an async fashion.I was able to execute the block,but async status is always returning not finished status even though vm extensions are installed successfully.Is there any thing am doing wrong here about polling the async job or Do i need to return anything from the powershell code which vm extension is executing?  Note- ansible version is 2.9, powershell v5.1 . Sample input-> var_vmArray: [vmname1,vmname2] and  var_jumpboxVmCount: 2
```
  - name: Configure VM block 
    block:
    - name: Create VM Extension
      azure_rm_virtualmachineextension:
       name: "{{ var_extensionName | default('Extension') }}"
       location: "{{ var_location  }}"
       resource_group: "{{ var_ResourceGroup }}"
       virtual_machine_name: "{{ item }}"
       publisher: Microsoft.Compute
       state: present
       virtual_machine_extension_type: CustomScriptExtension
       type_handler_version: "1.9"
       auto_upgrade_minor_version: true
       settings: '{"fileUris": ["{{ VM_TEMPLATEREPOURL+var_scriptFileName+VM_TEMPLATESASTOKEN }}"]}'
       protected_settings: 
        commandToExecute: "powershell -ExecutionPolicy Unrestricted -File {{ var_scriptFileName }} "      
      loop: "{{ var_vmArray|default(var_vmNameList.split(',')) }}"
      register: extension  
      async: 3600
      poll: 0
    - name: Wait for asynchronous jobs to end
      async_status:
        jid: '{{ extension.results[item|int-1].ansible_job_id }}'
      register: job_result
      until: job_result.finished
      delay: 120
      retries: 90
      with_sequence: start=1 end={{ var_jumpboxVmCount|default(1) }}
    rescue:
    - name: rescue block
      debug: 
       msg: extension failed to install !
    always:
    - debug:
         msg: "Executing extension cleanup tasks"
    - name: Delete VM Extension
      azure_rm_virtualmachineextension:
        name: "Extension"
        location: "{{ var_location }}"
        resource_group: "{{ var_ResourceGroup }}"
        virtual_machine_name: "{{ item }}"
        state: absent  
      loop: "{{ var_vmArray|default(var_vmNameList.strip(',').split(',')) }}"  
```

Error

"ansible_job_id": "653009376139.1262", "ansible_loop_var": "item", "attempts": 90, "changed": false, "finished": 0, "item": "2", "started": 1

##### ISSUE TYPE
polling the async job - async status is always returning not finished status even though vm extensions are installed successfully

##### COMPONENT NAME
azure_rm_virtualmachineextension

##### ANSIBLE VERSION
2.9

**Comment by Fred-sun** [comment]
@KrishnaG-MSFT Thank you for submitting this question. Can you share your complete playbooK and execution results? Thank you!

**Comment by Fred-sun** [comment]
Kindly ping!

**Comment by Fred-sun** [comment]
@KrishnaG-MSFT This should not be a Bug, because some resources are created after the background service to do some specific Settings, resulting in the state can not be immediately converted, thank you!
