### ISSUE TITLE
Version 0.4.0 Tag Missing?

### ISSUE THREAD

**Issue by dmlb2000** [ansible/ansible_collections_azure#228]
##### SUMMARY
The repository changelog seems to contain a v0.4.0 release, but the tag for the repo is missing?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Package management
##### ANSIBLE VERSION
N/A
##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Github

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
Expected to be able to checkout v0.4.0 as a tag from the git repo?

##### ACTUAL RESULTS
Seems like github doesn't have the tag...

**Comment by Fred-sun** [comment]
@dmlb2000 Yes, @haiyuazhang  will add this tags! Thank you very much!

**Comment by Fred-sun** [comment]
@dmlb2000 It has been changed from v0.4.0 to v1.0.0, please check, if confirmed, I will close this question. Thank you!

**Comment by Fred-sun** [comment]
Has been fixed!
