### ISSUE TITLE
azure_rm_containerinstance doesn't support Volume parameter

### ISSUE THREAD

**Issue by ash007osh** [ansible/ansible_collections_azure#232]
azure_rm_containerinstance doesn't support Volume parameter:

In order to mount any File Volume from Azure Files to Container Instance this option is required.

ISSUE TYPE
Feature Idea
COMPONENT NAME
azure_rm_containerinstance

ADDITIONAL INFORMATION
Without support of this parameter we have to use AZ command line, which defeats the purpose of Configuration Management.

@zikalino

**Comment by aparna-patil** [comment]
Hi @Fred-sun, I have started working on this issue..
