### ISSUE TITLE
Back up an Azure VM using Azure Backup

### ISSUE THREAD

**Issue by suyeb786** [ansible/ansible_collections_azure#234]
##### SUMMARY

Currently, there is no module available for back up an Azure VM using Azure Backup 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_backupAzureVM
azure_rm_backupAzureVM_info

##### ADDITIONAL INFORMATION

This module will introduce backup feature for azure vm and will be offering feature listed below
1. Enabling protection for the Azure VM
2. Trigger an on-demand backup for a protected Azure VM
3. Modify the backup configuration for a protected Azure VM
4. Stop protection but retain existing data
5. Stop protection and delete data

I am planning on writing the modules myself, but wanted to post an Issue ahead of time to solicit feedback and comments and to make sure no one else is already working on it

```yaml

```

**Comment by Fred-sun** [comment]
@suyeb786 Thanks for your submit this issue! We will investigate and feedback to you! Welcome your add this module!

**Comment by suyeb786** [comment]
Hello, @Fred-sun Thank you for your acknowledgment and for assigning the labels.
We have forked the branch and started working on it.

**Comment by iaingblack** [comment]
I believe this does not work when VM and Vault are in different Resource Groups. Using latest version as of posting, 1.2.0. Seems similar to issue Terraform had - https://github.com/terraform-providers/terraform-provider-azurerm/issues/2215

```
The full traceback is:
  File "/tmp/ansible_azure.azcollection.azure_rm_backupazurevm_payload_2p41dcfd/ansible_azure.azcollection.azure_rm_backupazurevm_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_backupazurevm.py", line 283, in enable_update_protection_for_azure_vm
  File "/tmp/ansible_azure.azcollection.azure_rm_backupazurevm_payload_2p41dcfd/ansible_azure.azcollection.azure_rm_backupazurevm_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common_rest.py", line 87, in query
    raise exp

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "auto",
            "backup_policy_id": "/subscriptions/REDACTED",
            "cert_validation_mode": null,
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "cloud_environment": "AzureCloud",
            "password": null,
            "profile": null,
            "recovery_vault_name": "REDACTED",
            "resource_group": "AzureBackupRG_northeurope_1",
            "resource_id": "/subscriptions/REDACTED",
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "create",
            "subscription_id": "REDACTED",
            "tags": null,
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "Error in creating/updating protection for Azure VM Azure Error: BMSUserErrorInvalidInput\nMessage: Input provided for the call is invalid\r\nPlease check the required inputs"
}
```

**Comment by suyeb786** [comment]
Hello @iaingblack ,
Yes, that's correct but it's a kind of a different usecase where the user needs to discover VM's in recovery vault where recovery vault and VM's belong to the different resource groups before enabling the protection.



**Please find more details below**
Discover unprotected Azure VMs

First, the vault should be able to identify the Azure VM. This is triggered using the refresh operation. It's an asynchronous POST operation that makes sure the vault gets the latest list of all unprotected VM in the current subscription and 'caches' them. Once the VM is 'cached', Recovery services will be able to access the VM and protect it.
