### ISSUE TITLE
Allow Certificate Based Authentication for Azure RM Modules and Plugins

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible_collections_azure#235]
##### SUMMARY

Allow [certificate based authentication](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest#certificate-based-authentication) with azure_rm_* modules

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_*

##### ADDITIONAL INFORMATION

Currently, there is no authentication method using certificate based auth as outlined in the [Azure Guide: Providing Credentials to Azure Modules](https://docs.ansible.com/ansible/latest/scenario_guides/guide_azure.html#providing-credentials-to-azure-modules)

Attempting to utilize azure-cli with cert based authentication also results in errors when using azure_rm_* modules

**Comment by Fred-sun** [comment]
@jamesmarshall24 Thanks for your report this issue! Could you help provide the playbook and the fail log? It will helpful to resolve the issue! Thank you very much!

**Comment by emilbra** [comment]
Is there any news on this feature? My team and i need to use Certificate based authentication, and azure cli is not a valid workaround.

**Comment by georgyous** [comment]
Is there any news on this one?

**Comment by Fred-sun** [comment]
@georgyous @jamesmarshall24 Already added (related PR https://github.com/ansible-collections/azure/pull/902), for example, you can add the following in.azure/credentials as a mode of authentication. Thank you!
```e.g.
[default]
subscription_id=XXXXXXXXXXXXXXXXXXXXXXX
client_id=XXXXXXXXXXXXXXXXXXXXXXX
tenant=XXXXXXXXXXXXXXXXXXXXXXX
thumbprint=2E9B1DADXXXXXXXXXXXXXXXXXXXXXXX
x509_certificate_path=/home/home/.azure/cert2.pem
