### ISSUE TITLE
Azure Recovery Services backup policies

### ISSUE THREAD

**Issue by suyeb786** [ansible/ansible_collections_azure#255]
##### SUMMARY

This feature will introduce a provision for following
1. Creating/Updating Backup Policies
2. Deleting Backup Policies
3. Listing All Backup Policies from Resouce Group
4. Get Details of a Backup Policies
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_backuppolicies
azure_rm_backuppolicies_info
##### ADDITIONAL INFORMATION

With this module, user can create custom backup policies using ansible and the same can be used for VM backup at the time of VM deployment.

```yaml

```

**Comment by Fred-sun** [comment]
@suyeb786 Thank you for submitting this question, and you are welcome to submit a PR to add these two modules!

**Comment by suyeb786** [comment]
@Fred-sun  
FYI, 
I have started working on it.

**Comment by Fred-sun** [comment]
Fixed by #271
