### ISSUE TITLE
Azure Host Group

### ISSUE THREAD

**Issue by ShwetaliBerad** [ansible/ansible_collections_azure#262]
##### SUMMARY
This feature will introduce a provision for following
   1. Creating/Updating Host Group
   2. Deleting Host Group
   3. Listing All Host Group from Resource Group
   4. Get Details of a Host Group

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_hostgroup
azure_rm_hostgroup_info

##### ADDITIONAL INFORMATION
With this module, user can create host group using Ansible. User can create a host group in a region and an availability zone and add hosts to it.

**Comment by Fred-sun** [comment]
@ShwetaliBerad @ShwetaliBerad Thank you for your new request? But can you elaborate on the needs and purpose of this module? He will help to add this new module. In addition, azure_rm_resourcegroup/ azure_rm_resourcegroup_info is a module for resourcegroup  management. Does it meet your needs? Thank you!

**Comment by ShwetaliBerad** [comment]
@Fred-sun This module will create host group. Host group is not required any changes in resource group module. Host group is associated with Dedicated Host and dedicated host is associated to VM. so dependency is like : Host Group -> Dedicated Host -> VM. Host group is collection of multiple dedicated hosts, and dedicated host will give flexibility to user to created VM in specified host. More information is here : https://docs.microsoft.com/en-us/azure/virtual-machines/windows/dedicated-hosts#groups-hosts-and-vms

**Comment by ShwetaliBerad** [comment]
> @ShwetaliBerad @ShwetaliBerad Thank you for your new request? But can you elaborate on the needs and purpose of this module? He will help to add this new module. In addition, azure_rm_resourcegroup/ azure_rm_resourcegroup_info is a module for resourcegroup management. Does it meet your needs? Thank you!

@Fred-sun This module will create host group. Host group is not required any changes in resource group module. Host group is associated with Dedicated Host and dedicated host is associated to VM. so dependency is like : Host Group -> Dedicated Host -> VM. Host group is collection of multiple dedicated hosts, and dedicated host will give flexibility to user to created VM in specified host. More information is here : https://docs.microsoft.com/en-us/azure/virtual-machines/windows/dedicated-hosts#groups-hosts-and-vms 

I am planning to write this module.

**Comment by Fred-sun** [comment]
@ShwetaliBerad Got it, welcome to contribute these two modules， I will push forward the review and merger of this PR!
