### ISSUE TITLE
azure_rm_dnsrecordset does not support private dnszones

### ISSUE THREAD

**Issue by briansok** [ansible/ansible_collections_azure#265]
##### SUMMARY
`azure_rm_dnsrecordset` Does not support the creating of records in private dns zones. When you try to add records with `azure_rm_dnsrecordset` you get a error: `The Resource 'Microsoft.Network/dnszones/<zone_name>' under resource group '<resource_group>' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\n"`. Since there is no other supported option to add records to private dns zones and this was supported before this is unwanted functionality.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`azure_rm_dnsrecordset`

##### ANSIBLE VERSION

```paste below
2.9.13
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OSX Catalina, python 3.7, pip 20.2.2. 

##### STEPS TO REPRODUCE

- Try to add records with `azure_rm_dnsrecordset` to a private dns zone.

```yaml

```

##### EXPECTED RESULTS

Succesfull recordset creation within a private dnszone

##### ACTUAL RESULTS

```paste below
`The Resource 'Microsoft.Network/dnszones/<zone_name>' under resource group '<resource_group>' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\n"`
```

##### POSSIBLE SOLUTION
I think the API is called at Microsoft.Network/dnszones and should be called at Microsoft.Network/privateDnsZones for private dns zones. See Azure API doc here: https://docs.microsoft.com/en-us/rest/api/dns/privatedns/recordsets/createorupdate

**Comment by Fred-sun** [comment]
@briansok Thank you for raising this question, we will review and add this feature as soon as possible. Thank you!

**Comment by aparna-patil** [comment]
Hi @Fred-sun, I have started working on this issue..
