### ISSUE TITLE
Private AKS cluster via Ansible

### ISSUE THREAD

**Issue by david-freistrom** [ansible/ansible_collections_azure#298]
##### SUMMARY
AKS module should have a flag to create a private cluster

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_aks

##### ADDITIONAL INFORMATION
The current up to date version of that moculde do not provide a private flag to set. Only public AKS cluster can be created.
The API Server is public.

```yaml
azure.azcollection.azure_rm_aks:
  private: true|false
```

**Comment by Fred-sun** [comment]
@david-freistrom Thank you for reporting this to us. We will look into it. Thank you very much!

**Comment by Fred-sun** [comment]
#651 has fixed
