### ISSUE TITLE
AKS Outbound via User Defined Routing not possible

### ISSUE THREAD

**Issue by david-freistrom** [ansible/ansible_collections_azure#303]
##### SUMMARY
It's not possible to define userDefinedRouting as an outbound type at the AKS module to control outbound traffic through a firewall in front of the aks cluster.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_aks

##### ADDITIONAL INFORMATION
At that moment ansible aks module is useless for production environments with a security standard

**Comment by Fred-sun** [comment]
@david-freistrom Thank you for reporting this to us. We will look into it. Thank you very much!

**Comment by Fred-sun** [comment]
add in #651
