### ISSUE TITLE
Typo in azure_rm_autoscale example

### ISSUE THREAD

**Issue by el-memer** [ansible/ansible_collections_azure#313]
##### SUMMARY

Little typo in azure_rm_autoscale, paramter `Time_aggregation:` shloud be lowercase

##### ISSUE TYPE
- Documentation Report

**Comment by Fred-sun** [comment]
@el-memer Thank you for pointing out this mistake, I will push forward the PR merger as soon as possible!

**Comment by el-memer** [comment]
Thanks for merging ! I was wondering, is it possible for me to add some other examples ? :)

**Comment by Fred-sun** [comment]
> Thanks for merging ! I was wondering, is it possible for me to add some other examples ? :)

Of course! Welcome you add examples!

**Comment by el-memer** [comment]
Nice! I'll make an other PR with some examples then !
