### ISSUE TITLE
Support for managing virtual network links for private dnszones

### ISSUE THREAD

**Issue by GerbenWelter** [ansible/ansible_collections_azure#318]
##### SUMMARY

Currently there is no support for managing the virtual network links of a private dnszone.

##### ISSUE TYPE
- Feature Idea
- Guidance

##### COMPONENT NAME

The new component could be named: azure_rm_privatednszone_vnetlink

##### ADDITIONAL INFORMATION

I'm willing to write the code but I'm unsure how to go about it. In the API for the public dns zones Microsoft has made the virtual network links a subresource of the dns zone: https://docs.microsoft.com/en-us/rest/api/dns/zones/get#zone

For the private dns zone there is no such subresource: https://docs.microsoft.com/en-us/rest/api/dns/privatedns/privatezones/get#privatezone
But instead it has made separate entry for it: https://docs.microsoft.com/en-us/rest/api/dns/privatedns/virtualnetworklinks

Confusingly, the Azure SDK code suggests that the virtual network links are a subresource of the private dns zone: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/network/azure-mgmt-privatedns/azure/mgmt/privatedns/operations/virtual_network_links_operations.py#L518

So if I were to add code for managing the virtual network links of a private dns zone should it be added to the current azure_rm_privatednszone module or should there be a separate new module (e.g. azure_rm_privatednszone_vnetlink)?

Please advise on a way forward.

**Comment by Fred-sun** [comment]
@GerbenWelter Thank you for reporting this issue, we will review it as soon as possible, thank you!

**Comment by ghost** [comment]
Hi @Fred-sun , @GerbenWelter I would like to contribute on this issue. Please let me know if I can take it up. Thank you!!

**Comment by Fred-sun** [comment]
@techcon65 Wonderful. Welcome you to contribution!

**Comment by ghost** [comment]
> @techcon65 Wonderful. Welcome you to contribution!

Thanks @Fred-sun for confirmation. I am working on it, will open a PR soon.
