### ISSUE TITLE
Add instance_id to host vars in azure_rm inventory plugin.

### ISSUE THREAD

**Issue by edikmkoyan** [ansible/ansible_collections_azure#324]
##### SUMMARY
In [this](https://docs.microsoft.com/en-us/azure/developer/ansible/vm-scale-set-update-image?tabs=ansible) doc a process of updating azure VMs to the latest model is described. As we can see, the instance_id is in the instances dict returned by the azure_rm_virtualmachinescalesetinstance_facts module. However the azure_rm inventory plugin provides only the id field in the host variables, forcing users to use jinja2 tricks to cut the instance_id off to use in the azure_rm_virtualmachinescalesetinstance module where the instance_id is mandatory. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm inventory plugin.

**Comment by Fred-sun** [comment]
@edikmkoyan Thank you for reporting this issue, we will review it as soon as possible, thank you!

**Comment by Fred-sun** [comment]
@edikmkoyan It should have been fixed by #105 and #261, can you try it? If success, I'll close it! Thank you very much!
