### ISSUE TITLE
Authenticate to Azure with app password

### ISSUE THREAD

**Issue by l3ender** [ansible/ansible_collections_azure#343]
##### SUMMARY
I can use the collection and authentication with an Azure Active Directory credential, but I am not able to use an [App Password](https://account.activedirectory.windowsazure.com/AppPasswords.aspx).

##### ISSUE TYPE
- Authentication/support

##### COMPONENT NAME
Authentication

##### ADDITIONAL INFORMATION
I configured the following environment variables to use app password:
```bash
AZURE_AD_USER=username of account with app password
AZURE_PASSWORD=app password value
AZURE_SUBSCRIPTION_ID=xxx
```

Running the playbook, I see the following in output:
```bash
"error":"invalid_grant","error_description":"AADSTS50126: Error validating credentials due to invalid username or password.
```

**Note 1**: I am trying to use app passwords because our organization enforces MFA. If I try using my normal user+password on this account, I receive the following error:
```bash
"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'xxx'.
```

**Note 2**: Using an app password is sometimes preferable to [creating a service principal](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal), because creating a service principal requires "User Access Administrator role" in the subscription (in order to map roles/RBAC to service principal). If a developer wants to use the Ansible Azure collection with only the permissions their user has, they are currently unable to do so once MFA is enabled for their account.

**Comment by Fred-sun** [comment]
@l3ender Thank you for reporting this issue, we will review it as soon as possible, thank you!

**Comment by mnhat3896** [comment]
Hi, @Fred-sun 
I've already met this issue, is there anything news to resolve this? 

My company used multi-factor authentication when we log in to the Azure portal. Is it a problem?
One more thing is I have no privilege to create a service principal, so I used ad_user and password for testing.
I have tried to `az login`, export variable and even create `/.azure/credentials` but it didn't work

<img width="1006" alt="Screen Shot 2021-04-21 at 18 33 47" src="https://user-images.githubusercontent.com/29061708/115547651-b47e3780-a2d0-11eb-8f75-20ce57b92e2c.png">

**Comment by WolfoDev** [comment]
Are there any news on this issue?

I'm required to log into azure through automation with an MFA-enabled account, and using App Password doesn't work.
Is there another way to `az login` bypassing MFA?

**Comment by Fred-sun** [comment]
@l3ender The problem you are experiencing is similar to #548. Using the Using Active Directory Username/Password credential failed. This seems to be a known Issue and we are trying to confirm the problem. Thank you very much!

**Comment by Fred-sun** [comment]
@l3ender This Issue is the same as the new Issue, and the problem is caused by its dependent package, so for easier tracking, it will be closed and the latest Issue will continue to be tracked. Thank you very much!
