### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.mgmt.storage.version'

### ISSUE THREAD

**Issue by ipvirg** [ansible/ansible_collections_azure#347]
##### SUMMARY

Executing playbook to create an RG fails with the following error:
ModuleNotFoundError: No module named 'azure.mgmt.storage.version'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.mgmt.storage.version

##### ANSIBLE VERSION

```paste below
 ansible --version
ansible 2.10.3
  config file = None
  configured module search path = ['/Users/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Apr 24 2020, 18:51:23) [Clang 11.0.3 (clang-1103.0.32.62)]

```

##### CONFIGURATION

```paste below
none, this is a new install
```

##### OS / ENVIRONMENT

macOS Catalina 
Version 10.15.7

##### STEPS TO REPRODUCE

playbook will create an RG and it is verified working when run on CentOS 7/ansible environment

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: creating RG
      azure_rm_resourcegroup:
        name: test-rg
        location: uksouth
      register: rg
    - debug:
        var: rg
```

##### EXPECTED RESULTS

Successfully creates an RG in Azure

##### ACTUAL RESULTS

Playbook fails with the following error  -
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/z2/rrnxqnsd4nxddct_ptqgptbw0000gp/T/ansible_azure_rm_resourcegroup_payload_f9zy6jj5/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 223, in <module>
    from azure.mgmt.storage.version import VERSION as storage_client_version
ModuleNotFoundError: No module named 'azure.mgmt.storage.version'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "force_delete_nonempty": false,
            "location": "uksouth",
            "name": "test-rg",
            "password": null,
            "profile": null,
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on mac-0's Python /Library/Developer/CommandLineTools/usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```paste below

```

**Comment by ipvirg** [comment]
Anyone encounter this issue? If anyone has macosx catalina with ansible/azure environment working, I appreciate if you could share the ansible/azure/python releases. thanks!

**Comment by next-davidduquehernandez** [comment]
Hi @ipvirg,

Review that you have the correct pip package versions installed. You can find [here](https://github.com/ansible-collections/azure/blob/v1.2.0/requirements-azure.txt)

Regards!

**Comment by ipvirg** [comment]
Thanks @next-davidduquehernandez, that resolved the issue.
