### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by howardjones** [ansible/ansible_collections_azure#357]
##### SUMMARY

"Did you know the documentation has an "Edit on GitHub" link on every page ?"
There is no link to documentation in the README.md (and therefore the Galaxy page).

(I was actually looking for guidance on using this collection with awx, which is causing me problems with dependencies)

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by Fred-sun** [comment]
@howardjones Thank you for your interest in this repo. Can you elaborate on the problem you encountered? I am not sure what kind of problem you have encountered? Thank you!

**Comment by howardjones** [comment]
Sure! Go to the [front page of this github repository](https://github.com/ansible-collections/azure). There is no link to any documentation. There is a "Contributing" item for _reviewing_ the documentation, but no documentation.

Go to the Galaxy page for this collection, and there is just a copy of the README, so also no documentation.

The "website" link on the the Galaxy page just goes to the front of azure.microsoft.com

**Comment by Fred-sun** [comment]
Do you want get ansible doc info? 
```e.g.
https://docs.ansible.com/ansible/latest/index.html

**Comment by haiyuazhang** [comment]
Has been fixed in PR376.
