### ISSUE TITLE
azure.azcollection.azure_rm_virtualmachine_info Error getting virtual machine - 'consoleScreenshotBlobUri

### ISSUE THREAD

**Issue by romangallego** [ansible/ansible_collections_azure#371]
##### SUMMARY

I created a playbook that uses the collection azure.azcollection with no issues in most of the tasks but when using the module azure_rm_virtualmachine_info
The module is expecting consoleScreenshotBlobUri as the VM has boot diagnostic enabled with storage account.
However, microsoft documentation https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get states clearly that 
**
Name | Type | Description
--        | --      | --
consoleScreenshotBlobUri | string | The console screenshot blob URI. NOTE: This will not be set if boot diagnostics is currently enabled with managed storage.
**

If I disable boot diagnostic in the VM using portalazure I can run the task without problem.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_virtualmachine_info
##### ANSIBLE VERSION

```
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venvaz/azcollection/lib/python3.6/site-packages/ansible
  executable location = /opt/venvaz/azcollection/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

STEP1 Create a playbook and role task
----playbook-----
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - azure.azcollection
  tasks:
    - include_role:
        name: vmsbuild
---role's taks---
- name: Get facts of a virtual machine
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
  register: vmjson

STEP 2 RUN THE PLAYBOOK. ERROR IS RAISED.
TASK [vmsbuild : Get facts of a virtual machine] *******************************
task path: /tmp/awx_523_opw2egx4/project/ansible-azure/playbooks/roles/vmsbuild/tasks/main.yml:33
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1608551562.6149426-193487-228045815119855 `" && echo ansible-tmp-1608551562.6149426-193487-228045815119855="` echo /root/.ansible/tmp/ansible-tmp-1608551562.6149426-193487-228045815119855 `" ) && sleep 0'
Using module file /tmp/awx_523_opw2egx4/requirements_collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-193412vrb_c7ez/tmpm4wcusbq TO /root/.ansible/tmp/ansible-tmp-1608551562.6149426-193487-228045815119855/AnsiballZ_azure_rm_virtualmachine_info.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1608551562.6149426-193487-228045815119855/ /root/.ansible/tmp/ansible-tmp-1608551562.6149426-193487-228045815119855/AnsiballZ_azure_rm_virtualmachine_info.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1608551562.6149426-193487-228045815119855/AnsiballZ_azure_rm_virtualmachine_info.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1608551562.6149426-193487-228045815119855/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_9samg7x8/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 355, in get_vm
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_9samg7x8/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 420, in serialize_vm
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "name": "SCDRAWX",
            "password": null,
            "profile": null,
            "resource_group": "SmileCDR_PABLO",
            "secret": null,
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "msg": "Error getting virtual machine SCDRAWX - 'consoleScreenshotBlobUri'"
}
PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0

STEP 3. DISABLE BOOT DIAGNOSTIC IN AZURE PORTAL
STEP 4. RERUN THE PLAYBOOK THIS TIME WITH NO ERROR
TASK [vmsbuild : Get facts of a virtual machine] *******************************
task path: /tmp/awx_525_p16536pq/project/ansible-azure/playbooks/roles/vmsbuild/tasks/main.yml:33
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1608553103.3871593-193746-28772224648226 `" && echo ansible-tmp-1608553103.3871593-193746-28772224648226="` echo /root/.ansible/tmp/ansible-tmp-1608553103.3871593-193746-28772224648226 `" ) && sleep 0'
Using module file /tmp/awx_525_p16536pq/requirements_collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-1936716g_z0415/tmpoj2x42n_ TO /root/.ansible/tmp/ansible-tmp-1608553103.3871593-193746-28772224648226/AnsiballZ_azure_rm_virtualmachine_info.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1608553103.3871593-193746-28772224648226/ /root/.ansible/tmp/ansible-tmp-1608553103.3871593-193746-28772224648226/AnsiballZ_azure_rm_virtualmachine_info.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1608553103.3871593-193746-28772224648226/AnsiballZ_azure_rm_virtualmachine_info.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1608553103.3871593-193746-28772224648226/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "name": "SCDRXXXX",
            "password": null,
            "profile": null,
            "resource_group": "SmileCDR_XXXXX",
            "secret": null,
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "vms": [
        {
            "admin_username": "XXXXXX",
            "boot_diagnostics": {
                "enabled": false,
                "storage_uri": null
            },
            "data_disks": [],
            "id": "/subscriptions/<THE SUBSCRIPTION>/resourceGroups/SmileCDR_XXXX/providers/Microsoft.Compute/virtualMachines/SCDRXXXX",
            "image": {
                "offer": "w9ansible",
                "publisher": "websoft9inc",
                "sku": "ansible-awx130-centos",
                "version": "latest"
            },
            "location": "canadacentral",
            "name": "SCDRXXXX",
            "network_interface_names": [
                "scdrawx986"
            ],
            "os_disk_caching": "ReadOnly",
            "os_type": "Linux",
            "power_state": "deallocated",
            "resource_group": "SmileCDR_XXXX",
            "state": "present",
            "tags": {
                "BUILD_MODE": "AUTOMATION"
            },
            "vm_size": "Standard_D2s_v3"
        }
    ]
}
META: ran handlers
META: ran handlers
PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued

```yaml

```

##### EXPECTED RESULTS

The module to manage not value returned for consoleScreenshotBlobUri as azure API states.
and therefore obtain the vm info.

##### ACTUAL RESULTS

task run:
- name: Get facts of a virtual machine
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
  register: vmjson
output with -vvv
TASK [vmsbuild : Get facts of a virtual machine] *******************************
task path: /tmp/awx_527__0dorb5w/project/ansible-azure/playbooks/roles/vmsbuild/tasks/main.yml:33
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1608553452.2962027-194007-229427077206443 `" && echo ansible-tmp-1608553452.2962027-194007-229427077206443="` echo /root/.ansible/tmp/ansible-tmp-1608553452.2962027-194007-229427077206443 `" ) && sleep 0'
Using module file /tmp/awx_527__0dorb5w/requirements_collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-193930e4cw30_n/tmp84npedtn TO /root/.ansible/tmp/ansible-tmp-1608553452.2962027-194007-229427077206443/AnsiballZ_azure_rm_virtualmachine_info.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1608553452.2962027-194007-229427077206443/ /root/.ansible/tmp/ansible-tmp-1608553452.2962027-194007-229427077206443/AnsiballZ_azure_rm_virtualmachine_info.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1608553452.2962027-194007-229427077206443/AnsiballZ_azure_rm_virtualmachine_info.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1608553452.2962027-194007-229427077206443/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_qufo5asc/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 355, in get_vm
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_qufo5asc/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 420, in serialize_vm
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "name": "SCDRXXX",
            "password": null,
            "profile": null,
            "resource_group": "SmileCDR_XXX",
            "secret": null,
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "msg": "Error getting virtual machine SCDRXXX - 'consoleScreenshotBlobUri'"
}
PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```paste below

```

**Comment by Fred-sun** [comment]
Already fixed by #208
