### ISSUE TITLE
Add support for UltraSSD to azure_rm_virtualmachine and azure_rm_virtualmachinescaleset modules

### ISSUE THREAD

**Issue by jfrazee** [ansible/ansible_collections_azure#382]
##### SUMMARY
Add support for including UltraSSD disks to azure_rm_virtualmachine and azure_rm_virtualmachinescaleset modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
* azure_rm_virtualmachine
* azure_rm_virtualmachinescaleset

##### ADDITIONAL INFORMATION
Right now the azure_rm_virtualmachine and azure_rm_virtualmachinescaleset modules don't include UltraSSD in the inclusion list for data disks provisioned alongside a VM or VMSS.

In order to make it easier to use UltraSSD disks it'd be convenient to be able to enable UltraSSD and specify UltraSSD_LRS as a managed_disk_type in the list of data_disks when using azure_rm_virtualmachine and azure_rm_virtualmachinescaleset (instead of separately using azure_rm_manageddisk).

**Comment by Fred-sun** [comment]
@jfrazee I don't think this is a bug! Ultra disks can only be used as data disks. We recommend using premium SSDs as OS disks.   Please refer to link as https://docs.microsoft.com/en-us/azure/virtual-machines/disks-types. If you don't have other question, I will close it!
```e.g.
 Azure ultra disks deliver high throughput, high IOPS, and consistent low latency disk storage for Azure IaaS VMs. Some additional benefits of ultra disks include the ability to dynamically change the performance of the disk, along with your workloads, without the need to restart your virtual machines (VM). Ultra disks are suited for data-intensive workloads such as SAP HANA, top tier databases, and transaction-heavy workloads. Ultra disks can only be used as data disks. We recommend using premium SSDs as OS disks.

**Comment by jfrazee** [comment]
@Fred-sun The ask isn't about Ultra for the OS disk, it's about supporting it for additional non-OS disks included in the data_disks parameter of the modules. Does that make sense?
