### ISSUE TITLE
Add "type" field to azure_rm_keyvaultsecret

### ISSUE THREAD

**Issue by pramos84** [ansible/ansible_collections_azure#390]
##### SUMMARY

The "type" field in Azure KeyVault resource is like a description of secret or password. I think that add this field to ansible module is a usefull mod that maybe requires a few lines of code. Thanks in advance for all work in this way. 

##### COMPONENT NAME

azure_rm_keyvaultsecret

```yaml

```

**Comment by Fred-sun** [comment]
@pramos84 Thank you for reporting this request. Could you tell me more details? If so, you want to add a parameter of 'type' to the azure_rm_keyvaultsecret module to describe whether it is a password or a secret? Like this?

**Comment by pramos84** [comment]
Hi, Fred-sun. Thanks for your reply. When creating secrets in Azure KeyVault, the Azure Portal shows some fields, like in this example:

![image](https://user-images.githubusercontent.com/17599917/104144386-c8490200-53a1-11eb-8457-81a3c59f7bac.png)

The "content type" is an optional field, used to describe the secret content. Would be very usefull if we could set the vaule of this field using ansible module. Thanks for helping on this.

**Comment by Fred-sun** [comment]
@pramos84 I submitted a PR #392  that added the content_type parameter to azure_rm_keyvaultsecret. Please check to see if you can compound your requirements. Thank you very much!

**Comment by Fred-sun** [comment]
duplicate with #116
