### ISSUE TITLE
Add support for spot instances

### ISSUE THREAD

**Issue by frival** [ansible/ansible_collections_azure#397]
##### SUMMARY

Add support for creating spot instances in AWS and would like to be able to do the same in Azure rather than having to spin up only full-price instances.  In the CLI this is done by adding a "--priority spot" to the VM instance creation command.  See: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/spot-cli

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachine

##### ADDITIONAL INFORMATION

For instances that are (relatively) short-lived and/or have workloads that can be easily restarted on a new instance using spot instances is a way to reduce overall cloud spend.  In my group we use this for running benchmarks that can be restarted but there are many other possible use cases.

```yaml

```

**Comment by ElPrincidente** [comment]
I also needed this feature so I've submitted a PR that supports Spot instance for both VM and VMSS. Waiting for review.
