### ISSUE TITLE
Question about new SDK authentication through azure-identity package

### ISSUE THREAD

**Issue by next-davidduquehernandez** [ansible/ansible_collections_azure#410]
##### SUMMARY
Azure starts to release new components, like Stream Analytics, and SDK changed how to authenticate against it. Stream Analytics only allows Azure Identity to be authenticated and I can't create my module with actual azure/azcollections authentication.

Can someone tell me how can I bypass this problem or there are some plan to allow new Azure SDK authentication?

Thank you very much!

##### ISSUE TYPE
- Just question.

##### COMPONENT NAME
 - Ansible Azure Authentication
 - azure-identity

##### ANSIBLE VERSION
- Ansible 2.10

**Comment by Fred-sun** [comment]
@next-davidduquehernandez Half of the modules already support the new SDK, such as (network, compute, storage, etc.), the others are still in the process of updating! Thank you very much!
