### ISSUE TITLE
Python hell since Ansible 2.10

### ISSUE THREAD

**Issue by Borrelworst** [ansible/ansible_collections_azure#417]
##### SUMMARY
General issue with pip/azure collections, when using CentOS 8, RedHat 8 or Ubuntu 20.

##### ISSUE TYPE
Don't know where to start:
- for pip3, ansible[azure] does work exist anymore (which was convenient)
- pip3 install azure does not work
- when using pip3 install -r https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt, when trying deploy an AKS cluster with azure_rm_aks I get: `The error was: ImportError: cannot import name 'PageBlobService'`, but it could be any error (at this moment it happened to be this error). Also happens when deploying other components (NICs, VMs)
- When using virtualenv I get this error: `Failed to get credentials. Either pass as parameters, set environment variables, define a profile in ~/.azure/credentials, or install Azure CLI and log in ( az login )` while I am logged in via the CLI
- All documentation is for Ansible 2.10, with yum and apt you can only download 2.9, which is missing a lot of functionality. This means you have to download Ansible with pip. You also don't want to mess up your system, so preferably you would run it in a venv, but this gives the errors as stated above. 

##### COMPONENT NAME
All components, in different order I get errors on them

##### ANSIBLE VERSION

```
ansible 2.10.5
  config file = None
  configured module search path = ['/home/jasper/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Dec 22 2020, 19:04:08) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```
##### OS / ENVIRONMENT
CentOS 8 in Virtualbox

##### STEPS TO REPRODUCE
Issue 1:
- Install Ansible
- Create virtualenv
- Install requirements with pip3 in virtualenv
- Upgrade ansible within venv to use Ansible 2.10
- Login with az login
- Try to deploy somehting, error wil be `Failed to get credentials`

Issue2:
- Install ansible with pip3
- Install requirements with pip3 (Directly on your system)
- Try to run anything, error will be `ImportError: cannot import name 'xxxxxxxxxxx'`

##### EXPECTED RESULTS
Be able to run ansible 2.10 in a virtualenv without any issues. 

##### ACTUAL RESULTS
Multiple errors, couple of them:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'PageBlobService'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on localhost.localdomain's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.monitor.version'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on localhost.localdomain's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

##### COMMENT
This used to work just fine. I am not sure where this got bad, but from version 2.10 and collections it looks like the python3 packages are not in sync anymore with the ones they got developed on, causing multiple issues on multiple platforms. This also means I have to fall back to the azure-cli to complete some workloads, which is a bummer. 

If there could be just a basic installation document which works for every platform it will be just fine, but even on this site:
https://docs.ansible.com/ansible/latest/scenario_guides/guide_azure.html

First line is:
`pip install 'ansible[azure]'`
Which gives:
`ansible 2.10.6 does not provide the extra 'azure'`

So please fix this and make it work smooth again. I would preferably have all python packages come in with yum instead of pip to prevent dependency issues, but then you should make 2.10 available via yum/apt as well.

**Comment by Borrelworst** [comment]
When installing the azure-cli also with pip instead of ms preferred way via yum:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.network.version'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on localhost.localdomain's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}`

**Comment by Fred-sun** [comment]
@Borrelworst Thank you for reporting this problem. I have tested Ansible 2.10, and there is no problem. Can you share your Playbook? I'll run it locally. In addition, after installing Ansible, you also need to follow this link --(https://github.com/ansible-collections/azure) to install Azure - Collection and add Collections definition, so as to execute correctly. Could you please try again? Thank you very much!
```e.g.
sudo pip3 install ansible[azure] -I
sudo pip3 install -r requirements-azure.txt
ansible-galaxy collection install azure.azcollection
```
```e.g.
---
- name: Using Azure collection
  hosts: localhost
  collections:
    - azure.azcollection
  tasks:
    - azure_rm_******:

**Comment by haiyuazhang** [comment]
@Fred-sun  Using ansible2.10 + collection,  the azure dependencies is supposed to be installed via
`pip install -r requirements-azure.txt`
We need to investigate more.

**Comment by Borrelworst** [comment]
I think the most important thing is to not have installed ansible at all before you run this. But the actual situation is that most of the times, you already have ansible installed (via yum or apt that will be 2.9). After running these 3 commands, you will get into all of the issues as I showed. 

Doing a fresh install with only the commands you shared looks to be working fine (I did a fresh CentOS8 installation and am able to run the playbook), but that is not a real world situation. The workflow looks to be: Remove all ansible packages including deps with yum and apt, and then reinstall according to the github page.

**Comment by jodrisb** [comment]
I am having the same issue.I posted also in stackoverflow https://stackoverflow.com/questions/68345685/ansible-playbook-error-was-modulenotfounderror-no-module-named-azure-mgmt-mon
Help...ansiblev2.10 is hell for us also.

**Comment by Fred-sun** [comment]
@jodrisb Please update all your dependency packages, which will help resolve the problem you are encountering. Thank you very much!
```e.g.
sudo pip3 install -Ir https://github.com/ansible-collections/azure/blob/dev/requirements-azure.txt

**Comment by jodrisb** [comment]
Thanks Fred-sun for replying, am getting an error when running that command

ERROR: Invalid requirement: '<!DOCTYPE html>' (from line 7 of https://github.com/ansible-collections/azure/blob/dev/requirements-azure.txt)

**Comment by jodrisb** [comment]
actually changed that url to this https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt and was able to get the pip packages but am still getting the module not found error as in this link that I described in https://stackoverflow.com/questions/68345685/ansible-playbook-error-was-modulenotfounderror-no-module-named-azure-mgmt-mon

**Comment by jodrisb** [comment]
also is it possible to reopen this issue as this issue only happens on v2.10-Thanks Fred-sun in advance.

**Comment by Fred-sun** [comment]
> also is it possible to reopen this issue as this issue only happens on v2.10-Thanks Fred-sun in advance.

@jodrisb It is not recommended that you reopen the problem, as the ansible_collection automated test was using V2.10 and did not encounter any problems. Can you uninstall all the packages and reinstall them? Thank you very much!

**Comment by jodrisb** [comment]
ok, I uninstalled and reinstalled and all is working now-Thanks
