### ISSUE TITLE
ERROR! couldn't resolve module/action 'azure_rm_backupazurevm'

### ISSUE THREAD

**Issue by barto90** [ansible/ansible_collections_azure#418]
##### SUMMARY
ERROR! couldn't resolve module/action 'azure_rm_backupazurevm' when using the azure_rm_backupazurvm module

I've checked the module path and can confirm that the 
azure_rm_backupazurevm_info.py
azure_rm_backupazurevm.py

Are both available.

Also tried manually referring the collection by using;
    collections:
    - "~/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_backupazurevm

With running verbose I got the following error (when using the collection definition as mentioned above)
[WARNING]: errors were encountered during the plugin load for gather_facts:
['~/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_backupazurevm.gather_facts is not a valid collection reference']

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_backupazurvm

##### ANSIBLE VERSION

```
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bpas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bpas/.local/lib/python3.8/site-packages/ansible
  executable location = /home/bpas/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### STEPS TO REPRODUCE
- name: Add the virtual machine to the vault
  vars:
    doNotBackup: "{{ do_not_backup }}"
  azure_rm_backupazurevm:
    resource_group: "xxxxxxxxxxxxxxxx"
    recovery_vault_name: 'xxxxxxxxxxxxxxxxxxxxx'
    resource_id: "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/{{ resourcegroup }}/{{ virtualmachine_name }}"
    backup_policy_id: "/subscriptions/xxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxx/providers/microsoft.recoveryservices/vaults/xxxxxxxxxxxxx/backupPolicies/DefaultPolicy"

##### EXPECTED RESULTS
VM is added to the backup (or the role is being refered too without issued.

##### ACTUAL RESULTS
ERROR! couldn't resolve module/action 'azure_rm_backupazurevm' when using the azure_rm_backupazurvm module

**Comment by Fred-sun** [comment]
@barto90 I have tested this module on the local virtual machine and have not encountered any errors. Could you please provide your complete PlayBook and error log? In order to solve the problem? Thank you very much!

**Comment by fepere** [comment]
Hello,
I think I´m trying to have the same issue, the variables are not working, so I changed the names on the playbook and still not working.
Do you know if the issue to add a VM into backup vault, due the resources are on a different 'resourcegroup' ?

the playbook
azureuser@myvm:~/test-azcli$ cat enable_backup_vm.yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: Enabling/Updating protection for the Azure VM
      azure.azcollection.azure_rm_backupazurevm:
     #azure_rm_backupazurevm:
        resource_group: DEMO-VM-RG
        recovery_vault_name: azc-demo-bkupvlt01
        resource_id: '/subscriptions/<removed subscriptionid info>/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/server1'
        backup_policy_id: '/subscriptions/<removed subscriptionid info>/resourceGroups/DEMO-VM-RG/providers/Microsoft.RecoveryServices/vaults/azc-demo-bkupvlt01/backupPolicies/testpolicy'
        state: create
        register: enablebackupvm
    - debug:
        var: enablebackupvm
azureuser@myvm:~/test-azcli$



fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup_policy_id": "/subscriptions/<removed subscriptionid info>/resourceGroups/DEMO-VM-RG/providers/Microsoft.RecoveryServices/vaults/azc-demo-bkupvlt01/backupPolicies/testpolicy",
            "recovery_vault_name": "azc-demo-bkupvlt01",
            "register": "enablebackupvm",
            "resource_group": "DEMO-VM-RG",
            "resource_id": "/subscriptions/<removed subscriptionid info>/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/server1",
            "state": "create"
        }
    },
    "msg": "Unsupported parameters for (azure.azcollection.azure_rm_backupazurevm) module: register Supported parameters include: ad_user, adfs_authority_url, api_profile, append_tags, auth_source, backup_policy_id, cert_validation_mode, client_id, cloud_environment, password, profile, recovery_vault_name, resource_group, resource_id, secret, state, subscription_id, tags, tenant"
}

**Comment by Fred-sun** [comment]
@fepere It seem your paramter error! should be as follow, please take a try! Thank you very much!
```e.g.
---
- hosts: localhost
  connection: local
  tasks:
    - name: Enabling/Updating protection for the Azure VM
      azure.azcollection.azure_rm_backupazurevm:
      #azure_rm_backupazurevm:
        resource_group: DEMO-VM-RG
        recovery_vault_name: azc-demo-bkupvlt01
        resource_id: '/subscriptions//resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/server1'
        backup_policy_id: '/subscriptions//resourceGroups/DEMO-VM-RG/providers/Microsoft.RecoveryServices/vaults/azc-demo-bkupvlt01/backupPolicies/testpolicy'
        state: create
      register: enablebackupvm
    - debug:
          var: enablebackupvm

**Comment by Fred-sun** [comment]
@barto90 From the error log you provided, you can see that your parameters were miswritten, as described above. Thank you very much!
