### ISSUE TITLE
Ansible support enable VM Disk Encryption

### ISSUE THREAD

**Issue by andyliddle** [ansible/ansible_collections_azure#425]
##### SUMMARY
Ansible support for Azure Disk Encryption for virtual machines and virtual machine scale sets.

https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Most probably a new Ansible module

https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-cli-quickstart

**Comment by Fred-sun** [comment]
@andyliddle Thank you for asking this question. I will investigate and add this Feature! Thank you very much!

**Comment by AzureStackNerd** [comment]
I'd like this feature very much too. Since it's best practise

**Comment by Fred-sun** [comment]
@AzureStackNerd You are welcome to contribute your PR. Thank you very much!

**Comment by lm-sig** [comment]
This issue can now be closed. Version 2.0.0 added support for VM disk encryption.
