### ISSUE TITLE
Ansible module to manage Azure Private Endpoint

### ISSUE THREAD

**Issue by KortexSys** [ansible/ansible_collections_azure#442]
##### SUMMARY
We manage several Azure Private Endpoint and except if I'm wrong there is no module to manage them.

##### ISSUE TYPE
- to have an Ansible module to manage Azure Private Endpoint

##### COMPONENT NAME
azure_rm_privateendpoint

##### ADDITIONAL INFORMATION
The module must announce a change if:
  - the resource does not exist
  - the requested resource is different from the existing one

The module must say "no change" if the remote resource is exactly similar to the demand on Ansible side.

When we use the module we need to define all parameters needed to create a private endpoint:
- name
- at which resource to attach the private endpoint
- etc

**Comment by Fred-sun** [comment]
Added by #593
