### ISSUE TITLE
azure_rm does not honor 'subscription_id' or 'AZURE_SUBSCRIPTION_ID'

### ISSUE THREAD

**Issue by victorbrca** [ansible/ansible_collections_azure#445]
##### SUMMARY

When using 'cli' as the authentication method, setting `subscription_id` in the inventory file (`azure_rm`) or exporting the variable `AZURE_SUBSCRIPTION_ID` does not work as expected (the default subscription in `az cli` is used instead of the specified one).

This was fixed/added on #195 and #53

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

[azure.azcollection.azure_rm](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html) 

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /media/sf_MENDONVI/Git/Development/Ansible/Azure/ansible.cfg
  configured module search path = ['/home/mendonvi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/media/sf_MENDONVI/Git/Development/Ansible/Azure/ansible.cfg) = True
DEFAULT_HOST_LIST(/media/sf_MENDONVI/Git/Development/Ansible/Azure/ansible.cfg) = ['/media/sf_MENDONVI/Git/Developmen>
DEFAULT_ROLES_PATH(/media/sf_MENDONVI/Git/Development/Ansible/Azure/ansible.cfg) = ['/media/sf_MENDONVI/Git/Developme>
DEFAULT_TIMEOUT(/media/sf_MENDONVI/Git/Development/Ansible/Azure/ansible.cfg) = 10
HOST_KEY_CHECKING(/media/sf_MENDONVI/Git/Development/Ansible/Azure/ansible.cfg) = False
RETRY_FILES_ENABLED(/media/sf_MENDONVI/Git/Development/Ansible/Azure/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 20.04 (VM)

```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

##### STEPS TO REPRODUCE

+ Configure a dynamic inventory file using the `azure_rm` plugin and cli authentication source

```
# required for all azure_rm inventory plugin configs
plugin: azure_rm

# forces this plugin to use a CLI auth session instead of the automatic auth source selection (eg, prevents the
# presence of 'ANSIBLE_AZURE_RM_X' environment variables from overriding CLI auth)
auth_source: cli
```

+ Login with `az cli` to an account with multiple subscriptions
+ Set a default subscription

```
az account set --subscription [sub id]
```

+ Now add another subscription to the inventory file

```
subscription_id: [###]
```

+ Run `ansible-inventory` with the inventory file

```
ansible-inventory -i  azure_rm.yml --graph
```

##### EXPECTED RESULTS

You should see all the VMs from the subscription ID in the inventory file instead of the default subscription set on cli.  

##### ACTUAL RESULTS

 VMs from the default subscription set on cli are shown.

**Comment by Fred-sun** [comment]
@victorbrca Yes, when it gets the 'az login' credential, it will also get the subscription_id, which will work according to the subscription_id of the credential. We pass either the parameter or the environment variable, credentials_file, if we can get the credential, it works depend on these info. Thank you!

**Comment by Fred-sun** [comment]
The relevant PR has been merged. Shut it down for now.
