### ISSUE TITLE
Enable azure_rm_virtualnetwork module to set more than 2 custom dns servers

### ISSUE THREAD

**Issue by rmeichsner** [ansible/ansible_collections_azure#461]
##### SUMMARY
I would like the azure_rm_virtualnetwork module to be able to configure more than 2 DNS Servers for a vnet.
At Azure Portal, there is no such limitation of 2 DNS Servers per vnet.

I found the the corresponding lines in the code (s. below), where this limitation is set, but without any documented reason why the limitation is set.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_virtualnetwork 

##### ADDITIONAL INFORMATION

azure/plugins/modules/azure_rm_virtualnetwork.py (line 259):
```
            if self.dns_servers and len(self.dns_servers) > 2:
                self.fail("Parameter error: You can provide a maximum of 2 DNS servers.")
```

**Comment by Fred-sun** [comment]
@rmeichsner Thank you for asking this question. Perhaps the previous API did not support multiple DNS servers when self.purge_address_prefixes=true. Now that it is supported, I will remove these two lines by send PR!
