### ISSUE TITLE
Add support for expressRouteCircuits

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#475]
##### SUMMARY
we would also like to create our expressRouteCircuits with ansible. It seems currently there is no module for that.
https://docs.microsoft.com/en-us/azure/expressroute/quickstart-create-expressroute-vnet-template

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
None as of now, most likely something like azure_rm_expressroutecircuits

**Comment by praveenghuge** [comment]
Hi @Klaas- @Fred-sun 
we want to contribute to this module. 
can you please assign this issue?

**Comment by Fred-sun** [comment]
> Hi @Klaas- @Fred-sun
> we want to contribute to this module.
> can you please assign this issue?

@praveenghuge Welcome to you contribution. You can fork this repo and submit PR to add this module! I will push for review and merge! Thank you very much!
