### ISSUE TITLE
azure_rm_appgateway - App Gateway module fails on autoscale enabled gateways

### ISSUE THREAD

**Issue by dromanGH** [ansible/ansible_collections_azure#478]
##### SUMMARY

There is currently no way to define an autoscale configuration for the app gateway module. Attempting to update an autoscaling app gateway will result in an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_appgateway 

##### STEPS TO REPRODUCE

Attempt to update any aspect of an app gateway which is configured with autoscaling.

##### EXPECTED RESULTS

The app gateway is updated.

##### ACTUAL RESULTS

The app gateway fails to update

**Comment by Fred-sun** [comment]
@dromanGH Thanks for your submit this issue! Could you help share your error log and playbook? It will helpful to resolve this problem! Thank you very much!

**Comment by Fred-sun** [comment]
Related PR has merged! closed it!
