### ISSUE TITLE
Issue with azure_rm_dnsrecordset: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by stefanpinter** [ansible/ansible_collections_azure#479]
##### SUMMARY
Hi!
I get the following Issue

msrestazure.azure_exceptions.CloudError: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/e23cf4ad-2d71-446f-9864-82961ad66ae7/resourceGroups/mv-dns-rg/providers/Microsoft.Network/dnsZones/?api-version=2018-05-01\n",

my task:
---
- name: Setze A-Record in Azure
  become: false
  hosts: localhost

  tasks:
    - name: A-Record erstellen
      azure_rm_dnsrecordset:
        resource_group: mv-dns-rg
        relative_name: "{{ inventory_hostname }}"
        zone_name: "{{ ansible_facts.domain }}"
        record_type: A
        records:
          - entry: "{{ publicipaddresse }}"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_dnsrecordset

##### ANSIBLE VERSION
AWX 17.0.1
azure.azcollection:1.5.0

##### CONFIGURATION
nothing

##### OS / ENVIRONMENT
nothing

##### STEPS TO REPRODUCE
add azure credentials in AWX
run playbook/template
get error

(i tried re-creating the service principal - the same worked a week or two ago)

##### EXPECTED RESULTS
creating A record on azure DNS zone

##### ACTUAL RESULTS
receive error:
msrestazure.azure_exceptions.CloudError: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/e23cf4ad-2d71-446f-9864-82961ad66ae7/resourceGroups/mv-dns-rg/providers/Microsoft.Network/dnsZones/?api-version=2018-05-01\n",

**Comment by Fred-sun** [comment]
@stefanpinter Thanks for you submit this issue! I check it in my local environment and create successfully. Seem to be due your credentials? Could you help check you credentials? thank you very much!

**Comment by stefanpinter** [comment]
@Fred-sun 
Hello!
Thank you for looking at it. In fact Ansible used the wrong URL because i made an error. Sorry!
