### ISSUE TITLE
Add support for expressRouteCircuits Peering

### ISSUE THREAD

**Issue by praveenghuge** [ansible/ansible_collections_azure#483]
**SUMMARY**
we would also like to create our expressRouteCircuitsPeering with ansible. It seems currently there is no module for that.
https://docs.microsoft.com/en-us/azure/expressroute/expressroute-circuit-peerings#privatepeering

dependent on https://github.com/ansible-collections/azure/issues/475

**ISSUE TYPE**

- Feature Idea

**COMPONENT NAME**
None as of now, most likely something like azure_rm_expressroute_peering

**Comment by ikarldasan** [comment]
Hi @Fred-sun @praveenghuge   would like to contribute to this.

**Comment by Fred-sun** [comment]
@ikarldasan @praveenghuge I will review and push for this merge! Thank you very much!

**Comment by Fred-sun** [comment]
fixes by #484
