### ISSUE TITLE
Update README in community.azure

### ISSUE THREAD

**Issue by Andersson007** [ansible/ansible_collections_azure#487]
##### SUMMARY
https://github.com/ansible-collections/community.azure/blob/master/README.md should be updated (and maybe README of `azure` as well) to describe the current relationship between the `azure` and `community.azure` repositories (e.g., the purpose of keeping those info modules there, if it should be made readonly one day, etc).

Now `community.azure` says "Provides modules for Ansible for various Azure operations." but I see only _info modules there.

As community.azure seems to be pretty inactive, I created the issue here.

**Comment by l3ender** [comment]
I am also unsure of the difference between the two.

**Comment by Fred-sun** [comment]
@Andersson007 What is the purpose of your issue? Could you be a little more specific? If not, it will be closed next week, thanks!

**Comment by Andersson007** [comment]
@Fred-sun the https://github.com/ansible-collections/community.azure repo was archived and the info about its deprecated status is already in its README (it wasn't clear to me at the moment i created the issue), so the issue is irrelevant and I'll close it now. Thanks for pinging!
