### ISSUE TITLE
[Feature Idea] Upgrade Managed Cluster Client Api Version To 2020-04-01

### ISSUE THREAD

**Issue by MarcGi** [ansible/ansible_collections_azure#489]
##### SUMMARY

Upgrade Managed Cluster Client Api Version To 2020-04-01 From The Current 2019-04-01

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Components related to azure_rm_aks (Including info, upgrade_versions, etc.)

##### ADDITIONAL INFORMATION

This would allow for newer AKS features to be supported by this Galaxy Module

https://github.com/ansible-collections/azure/pull/336 currently relies on this API version to be upgraded

**Comment by MarcGi** [comment]
I will start working on this under https://github.com/MarcGi/azure/tree/update_aks_api_version

**Comment by Fred-sun** [comment]
@MarcGi Thank for you submit this issue! I will push for #336 to be resolved!
