### ISSUE TITLE
Ansible module support for Network Watcher and Flow Logs

### ISSUE THREAD

**Issue by paultaiton** [ansible/ansible_collections_azure#491]
##### SUMMARY

I do not see any method for setting up Network Watchers or Flow Logs in azcollection. It would be nice for this to be available.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_networkwatcher
azure_rm_networkwatcher_info
azure_rm_flowlog
azure_rm_flowlog_info

##### ADDITIONAL INFORMATION

These are two related resources in Azure that are used for recording traffic data from Network Security Groups.

```yaml

```

I have a requirement to automate the provisioning of these resources. From a basic look, it appears that the azure.mgmt.network  package (and NetworkManagementClient) provides network_client.network_watcher and netwrok_client.flow_log  objects manage. However the API version for NetworkManagementClient, 2019-06-01, does not support flow logs. The earliest version that does is 2019-11-01 . The question I have is around the level of testing needed to update the NetworkManagementClient API version? This package in particular is used in a LOT of modules, so I don't want to be the one to break anything by updating the azure_rm_common API version.

**Comment by Fred-sun** [comment]
@paultaiton Thanks for you submit this issue! I will check and push for solved!

**Comment by sodds-eq** [comment]
Any status on this  one?

**Comment by Fred-sun** [comment]
@sodds-eq We are processing these related modules, thank you!

**Comment by Fred-sun** [comment]
Add support by #1576
