### ISSUE TITLE
Add support for DDoS Protection Plan

### ISSUE THREAD

**Issue by ikarldasan** [ansible/ansible_collections_azure#492]
**SUMMARY**
we would also like to create our DDoS protection plan with ansible. It seems currently there is no module for that.
https://docs.microsoft.com/en-us/azure/ddos-protection/ddos-protection-overview

**ISSUE TYPE**
- Feature Idea

**COMPONENT NAME**
None as of now, most likely something like azure_rm_ddos_protection_plan

**Comment by ikarldasan** [comment]
Hi @Fred-sun will like to contribute to this

**Comment by Fred-sun** [comment]
> Hi @Fred-sun will like to contribute to this

@ikarldasan Great! Welcome to you contribution!
