### ISSUE TITLE
Add instructions for testing changes to CONTRIBUTING.md

### ISSUE THREAD

**Issue by tfmark** [ansible/ansible_collections_azure#508]
##### SUMMARY

I would like to submit a PR for a change, however I would like to test my change first (ideally writing a test case that fails, highlighting the bug, that will then pass once I've fixed the problem). How do I do that? the `ado.sh` script seems impractical for this task.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
CONTRIBUTING.md

##### ANSIBLE VERSION
n/a

**Comment by paultaiton** [comment]
Duplicate of #476 

@tfmark  I am in the process of working on this already.

**Comment by tfmark** [comment]
Ah sorry for the dupe, looking forward to it!
