### ISSUE TITLE
Source does not match Galaxy's released 0.1.1 version

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible_collections_azure#55]
##### SUMMARY
The tags and galaxy metadata here have version `0.1.0`, but there is a version on Galaxy with `0.1.1`

![Screen Shot 2020-03-11 at 9 06 39 AM](https://user-images.githubusercontent.com/1385596/76420064-e441d880-6377-11ea-881b-87064f8f8c46.png)

https://github.com/ansible-collections/azure/blob/c9d470cbb9f70c05e918490d0b17d7bd82e8e57e/galaxy.yml#L12

##### ISSUE TYPE
- Bug Report

**Comment by Fred-sun** [comment]
@AlanCoding Azure /galaxy. Yml has been updated to [version 0.1.2](https://github.com/ansible-collections/azure/blob/5e90c764cb708f44dcf2ad79573ef2ad60662e6d/galaxy.yml#L12), could you please confirm whether there is still this problem? Thank you very much!

**Comment by AlanCoding** [comment]
thanks, that looks good, I will re-test with 0.1.2 but do not anticipate problems
