### ISSUE TITLE
azure_rm_aks: Aks managed aad integration

### ISSUE THREAD

**Issue by tschechniker** [ansible/ansible_collections_azure#568]
##### SUMMARY
Currently only the Legacy AAD integration is available in the AKS module. The AKS managed aad integration should be used.

##### ISSUE TYPE
- Add the "new" managed aad integration: https://docs.microsoft.com/de-de/azure/aks/managed-aad

##### COMPONENT NAME

azure_rm_aks

**Comment by Fred-sun** [comment]
@tschechniker Thank you for your interest in Ansible_Collections. We will review and add new requirements as soon as possible. You are also welcome to contribute this feature! Thank you very much!

**Comment by Fred-sun** [comment]
Added in #654 and #1677
