### ISSUE TITLE
Feature Request Tracking

### ISSUE THREAD

**Issue by AerisG222** [ansible/ansible_collections_azure#576]
I am a new user of Ansible and this Azure collection, and want to first say thank you for all your work to allow for automating Azure resource management with Ansible!

##### SUMMARY
I am trying to understand the status of different modules in the Azure collection and how best to request functionality that is not yet exposed via these modules.  For example, I am trying to use  azure_rm_functionapp and would like to do things like:
- enable always on (similar to #439)
- configure functions version ~3
- enable vnet integration
- assign managed identity
- add app insights

Given the example above:
- Are these things being tracked / prioritized somewhere that is not available on github (and therefore github feature requests are not needed/wanted) [apologies if if this exists somewhere, I have not come across this yet]?
- Is it preferable to create an issue per module and update the single issue with a table of features and their status? (for example, azure_rm_functionapp would have the list above that could be added to / checked off over time)?
- Is it preferable to create many small feature requests for each module (perhaps on a case by case basis to allow for discussion for specific features in the checklist as needed)?

I am coming from custom scripts using the Azure CLI, and the related docs highlight other capabilities that would be great to support in this collection [https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az_functionapp_create].  

What is the best way to help identify missing features?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Issues

##### ADDITIONAL INFORMATION
I think this could be helpful for people to understand where there are gaps, what is being focused on, and where contributors might best help pitch in.

Thanks again for your time!

**Comment by Fred-sun** [comment]
@AerisG222 Yes, some parameters of this module are not added relative to azure-cli. Maybe they were forgotten to be added or not supported when the module was designed at that time. We will investigate as soon as possible what parameters need to be added. Other contributors are also welcome to add these features. Thank you!

**Comment by AerisG222** [comment]
@Fred-sun Thanks for the reply.  Trying to keep up with all the changes in Azure is a huge task!

It sounds like the preferred approach is to create a ticket per module.  As this addresses the primary question, feel free to close this issue unless it is helpful to have the list above related to functionapps.

Otherwise, thanks again for such a great project.  I hope to be able to contribute in a more substantial way in the future.

**Comment by Fred-sun** [comment]
@AerisG222 Thank you for your attention. We will do our best.

**Comment by srivatsan-nagarajan** [comment]
I don't see the above options got added to the module yet. I've included this app_settings in my function app

`  app_settings:`
`    APPINSIGHTS_INSTRUMENTATIONKEY: "{{ appai.instrumentationKey }}"`
`    APPLICATIONINSIGHTS_CONNECTION_STRING: "{{ appai.connectionString }}"`
`    SCM_DO_BUILD_DURING_DEPLOYMENT: 1`
`    BUILD_FLAGS: "UseExpressBuild"`
`    ENABLE_ORYX_BUILD: "true"`
`    ftpsState: "Disabled"`
`    FUNCTIONS_EXTENSION_VERSION: "~4"`
`    FUNCTIONS_WORKER_RUNTIME: "python"`
`    linuxFxVersion: "Python|3.11"`
`    alwaysOn: true`
`    sqlserver_connection_string: "{{ odbc_conn_string }}"`
`    WEBSITE_ENABLE_SYNC_UPDATE_SITE: "true"`

Though linuxFxversion, alwaysOn, runtime env and version not picking up and also scm local git not able to disable. Any help is appreciated @Fred-sun

**Comment by Fred-sun** [comment]
@srivatsan-nagarajan I am working on this Issue, you can make a new issue, the update will link to your new issue. Thank you!
