### ISSUE TITLE
Add tags to galaxy.yml 

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/ansible_collections_azure#591]
##### SUMMARY

The collection does not contain tags so adding some tags that are relevant to the collection would be good to better improve search results/show use case.
The list of tags are found on AH but also pasted below. 
```
    cloud
    linux
    networking
    storage
    security
    windows
    infrastructure
    monitoring
    tools
    database
    application
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

galaxy.yml
##### ANSIBLE VERSION

```paste below
n/a
```

**Comment by Fred-sun** [comment]
Has fixed!
