### ISSUE TITLE
Add ProximityPlacementGroup to azure_rm_virtualmachine azure_rm_virtualmachine

### ISSUE THREAD

**Issue by vdvelde** [ansible/ansible_collections_azure#602]
##### SUMMARY

Add ProximityPlacementGroup as a parameter to azure_rm_virtualmachine in order set it correctly upon creation. 

##### ISSUE TYPE
- component enhancement

##### COMPONENT NAME

It should be added to the module azure_rm_virtualmachine

##### ADDITIONAL INFORMATION
Test if proximity group is present then include the parameter while creating.
It should be similar to the powershell below but as parameter in Ansible.
```
$vmName = "myVM"

New-AzVm `
  -ResourceGroupName $resourceGroup `
  -Name $vmName `
  -Location $location `
  -OpenPorts 3389 `
  -ProximityPlacementGroup $ppg.Id
```

**Comment by Fred-sun** [comment]
fixes by #611
