### ISSUE TITLE
Power On/Power Off not working

### ISSUE THREAD

**Issue by stefanpinter** [ansible/ansible_collections_azure#632]
##### SUMMARY
Hi!
I can't power on/off my Azure VM. It gives an error  "Parameter error: admin_username required when creating a virtual machine." even though I don't want to create a virtual machine, as it is already there!

According to https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_virtualmachine_module.html I can start, stop and restart VMs by using this example:

- name: Power On
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: testvm002

In fact my playbook looks like this:
---
- name: Fährt eine Azure VM herunter
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    rg: ressourcegroupname
    vm: vmname

  tasks:

    - name: Power OFF
      azure_rm_virtualmachine:
        resource_group: "{{ rg }}"
        name: "{{ vm }}"
        started: no

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine:

##### ANSIBLE VERSION
AWX 19.3.0

##### COLLECTION VERSION
i don't know, I use AWX 19.3.0 so I have no ansible-galaxy command, but I added azure.azcollection to collections/requirements.yml today, so I guess it is the most recent version

##### CONFIGURATION
shrug... its basically AWX 19.3.0

##### OS / ENVIRONMENT
AWX 19.3.0 on kubernetes

##### STEPS TO REPRODUCE
added azure.azcollection to collections/requirements.yml 

##### EXPECTED RESULTS
VM shuts down

##### ACTUAL RESULTS
I get an error when running the playbook and the VM does NOT shut down
 "Parameter error: admin_username required when creating a virtual machine.",

{
  "msg": "Parameter error: admin_username required when creating a virtual machine.",
  "invocation": {
    "module_args": {
      "resource_group": "rgname",
      "name": "vmname",
      "started": false,
      "auth_source": "auto",
      "cloud_environment": "AzureCloud",
      "api_profile": "latest",
      "append_tags": true,
      "state": "present",
      "max_price": -1,
      "ssh_password_enabled": true,
      "storage_container_name": "vhds",
      "os_type": "Linux",
      "public_ip_allocation_method": "Static",
      "remove_on_absent": [
        "all"
      ],
      "allocated": true,
      "restarted": false,
      "generalized": false,
      "accept_terms": false,
      "profile": null,
      "subscription_id": null,
      "client_id": null,
      "secret": null,
      "tenant": null,
      "ad_user": null,
      "password": null,
      "cert_validation_mode": null,
      "adfs_authority_url": null,
      "log_mode": null,
      "log_path": null,
      "tags": null,
      "custom_data": null,
      "location": null,
      "short_hostname": null,
      "vm_size": null,
      "priority": null,
      "eviction_policy": null,
      "admin_username": null,
      "admin_password": null,
      "ssh_public_keys": null,
      "image": null,
      "availability_set": null,
      "storage_account_name": null,
      "storage_blob_name": null,
      "os_disk_caching": null,
      "os_disk_size_gb": null,
      "managed_disk_type": null,
      "os_disk_name": null,
      "open_ports": null,
      "network_interface_names": null,
      "virtual_network_resource_group": null,
      "virtual_network_name": null,
      "subnet_name": null,
      "data_disks": null,
      "plan": null,
      "zones": null,
      "license_type": null,
      "vm_identity": null,
      "winrm": null,
      "boot_diagnostics": null,
      "ephemeral_os_disk": null
    }
  },
  "warnings": [
    "Module did not set no_log for ssh_password_enabled"
  ],
  "_ansible_no_log": false,
  "changed": false
}

**Comment by stefanpinter** [comment]
ok, looks like it needs a few more permissions... I added Microsoft.ClassicCompute/virtualMachines/ permissions, but it needs stuff from Microsoft.Compute/virtualMachines
now it asks for more stuff like "read public IP info"-permissions...

**Comment by stefanpinter** [comment]
yep, working now :)
maybe it can tell us here about missing permissions as well instead of just assuming that the VM isn't in existance :)

**Comment by Fred-sun** [comment]
@stefanpinter Thank you for reporting this problem, this should be your VM does not exist, you can not restart or stop the VM. It is recommended that you create a VM and try again. Thank you very much!
