### ISSUE TITLE
Support azure automation runbooks

### ISSUE THREAD

**Issue by tschechniker** [ansible/ansible_collections_azure#637]
##### SUMMARY
Add support to create runbooks for azure automations

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Currently you are only able to create automation accounts with azure_rm_automationaccount. Would be nice to also add some content to them (e.g. creating runbooks)

##### ADDITIONAL INFORMATION
This would solve manual steps after ansible run.

**Comment by Fred-sun** [comment]
@tschechniker Thank you for reporting this problem, we will consider adding this feature. Thank you!

**Comment by KrishnaG-MSFT** [comment]
@Fred-sun Any update on this please? Do we have any ETA by when plugin to create runbook under azure.azcollection collection will be available to use?

**Comment by Fred-sun** [comment]
@KrishnaG-MSFT We are adding. Thank you very much!

**Comment by Fred-sun** [comment]
fixed in #797
