### ISSUE TITLE
azure_rm_appgateway

### ISSUE THREAD

**Issue by nergalex** [ansible/ansible_collections_azure#652]
##### SUMMARY
In azure_rm_appgateway.py, add a parameter to configure a Web Application Firewall.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Python SDK reference: [web_application_firewall_configuration](https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2020_06_01.models.applicationgateway?view=azure-python)

**Comment by Fred-sun** [comment]
@nergalex Added in #1725

**Comment by Fred-sun** [comment]
@nergalex Already add new module (#1783). Thanks!

**Comment by nergalex** [comment]
Thx
