### ISSUE TITLE
Add AKS Azure AD Configuration

### ISSUE THREAD

**Issue by tman5** [ansible/ansible_collections_azure#653]
##### SUMMARY
Add ability to provision an AKS cluster with managed Azure AD enabled and be able to specify admin groups https://docs.microsoft.com/en-us/azure/aks/managed-aad#create-an-aks-cluster-with-azure-ad-enabled

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
AKS

##### ADDITIONAL INFORMATION
Currently there is no way to provision or modify an existing AKS cluster to enable managed Azure AD via Ansible

**Comment by Fred-sun** [comment]
Add by #654
