### ISSUE TITLE
Azure inventory plugin fails with status code 429

### ISSUE THREAD

**Issue by myselfgagandeep** [ansible/ansible_collections_azure#659]
##### SUMMARY
azure_rm inventory plugin throttles Azure API and fails to retrieve the list of VMs against specific subscriptions with HTTP error 429.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm

##### ANSIBLE VERSION

```paste below
2.9.20
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list azure.azcollection
```

##### CONFIGURATION

```paste below
---
plugin: azure_rm
conditional_groups:
  azure: true

```

##### STEPS TO REPRODUCE

```yaml
plugin: azure_rm
include_vm_resource_groups:
- my_rg
exclude_host_filters:
- ...
```

##### EXPECTED RESULTS

I expect the plugin to populate the inventory with list of hosts from all Azure subscriptions.

##### ACTUAL RESULTS

I have a master inventory, which contains multiple inventory sources pointed to several Azure subscriptions and using azure_rm as the inventory plugin to retrieve the hosts from these subscriptions.

Recently, one of the subscriptions have started to get throttled by this inventory sync with the error as below:
```paste below
[WARNING]:  * Failed to parse
/tmp/bwrap_61603_n5iqi5sz/awx_61603_b6it8vva/azure_rm.yml with auto plugin: a batched request failed with status code 429, 
 rl https://management.azure.com/s ubscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/providers/Microsoft.Compute/v irtualMachines?api-version=2017-03-30&%24skiptoken=xxxxxxxxxxxxxxxxxxxx
```

Also, the plugin tries to reach out to an older version of Azure API i.e api-version=2017-03-30 in the API call as depicted in the warning.

We have ansible tower installation and i have tried both the plugins below but they yield the same result.
plugin: azure_rm
plugin: azure.azcollection.azure_rm

The problem seems to be on the Microsoft Azure end since the API when throttled beyond accepted limit caps the requests coming further from ansible.

Default limits for Resource manager API reads is 12000 per hour and Resource manager API writes is 1200 per hour and upon running the inventory sync using azure_rm plugin, we are hitting this limit leading to sync failure.

**Comment by Fred-sun** [comment]
@myselfgagandeep Thank you for submitting this question, but I created two VMS locally but got dynamic host information and did not encounter the problem you encountered. Thank you very much!
```e.g.
fred@DESKTOP-RUEHQGC:~/inventory$ ansible-inventory -i myazure_rm.yml --graph
@all:
  |--@ungrouped:
  |  |--win-vm02_dce8
  |  |--win-vm_5e5b
fred@DESKTOP-RUEHQGC:~/inventory$ vi myazure_rm.yml
fred@DESKTOP-RUEHQGC:~/inventory$ ansible-inventory -i myazure_rm.yml --graph
@all:
  |--@ungrouped:
fred@DESKTOP-RUEHQGC:~/inventory$ vi myazure_rm.yml ^C
fred@DESKTOP-RUEHQGC:~/inventory$ cat myazure_rm.yml
plugin: azure.azcollection.azure_rm
include_vm_resource_groups:
  - ansible-inventory-test-rg
    #auth_source: aut
exclude_host_filters:
  - "powerstate == \"running\""

**Comment by myselfgagandeep** [comment]
@Fred-sun: azure_rm plugin works as you specified. The problem is sporadic and occurs when other applications are also consuming the management API to a certain extent and thus throttling the API even before ansible has started inventory sync using the plugin. Since automation in ansible relies on dynamic inventory to populate first and discover the host, having a throttled API blocking the API call fails the complete play. It is a known limitation on Azure end where they limit the amount of read requests per hour.

From Azure end, we should have a retry-after specified in the playbook or at plugin level. Any solution around that we can implement on ansible end since we have exponential growth in the amount of servers we deploy in Azure on enterprise level ?

**Comment by Fred-sun** [comment]
@myselfgagandeep I'll check again, thanks for your reply!

**Comment by Fred-sun** [comment]
@myselfgagandeep Ansible azure_rm inventory plugin  does not have any retry mechanism, if request failed, an error will raise. For batch APIs sender(msrestazure SDK), the request will retry every 30s if not finished, I don’t think the request can keep retrying, if the request not finished in a fixed time, the server should interrupt it.

**Comment by Fred-sun** [comment]
@myselfgagandeep When we use each host, we will send 5 requests and get response. If many hosts are used at the same time, the number of requests sent will exceed 12000/hour, resulting in too many requests and errors. thank you！
```e.g.
Solutions:
1. Process hosts in batches
2. Increase the number of requests per hour.

**Comment by lucas-benedito** [comment]
@Fred-sun As per inventory plugin documentation, the option batch_fetch is set to true by default. Is that what you mean with the suggested solution 1?
As for the suggested solution 2, how can this be achieved from a module standpoint? If that is not possible, how can a customer achieve this?
