### ISSUE TITLE
AZ collection tries to connect to localhost 5985 winrm port instead of microsoft.com

### ISSUE THREAD

**Issue by kTipSSIoYv** [ansible/ansible_collections_azure#663]
Why does az collection try to connect to localhost to create VM's on azure portal?

```
TASK [azure_vms : Create Network Security Group that allows SSH] *******************************************************************
task path: /home/ansible/azure_ansible/azure_vms/tasks/main.yml:3
Using module file /home/ansible/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: azureuser on PORT 5985 TO 127.0.0.1
fatal: [localhost]: UNREACHABLE! => {
    "changed": false,
    "msg": "ntlm: HTTPConnectionPool(host='127.0.0.1', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa88d76d430>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "unreachable": true
}
```

**Comment by kTipSSIoYv** [comment]
If I don't use collections then I have the following error:
`The module azure_rm_securitygroup was redirected to azure.azcollection.azure_rm_securitygroup`. But this issue exists only if I roles. I tested without using roles and created a playbook with just tasks and host details and it works fine. I have installed `https://github.com/Azure/azure_modules` too but it doesn't work when using roles.

    cat azure_playbook.yaml
    ---
    -
      hosts: localhost
      connection: local
      gather_facts: false
    
      roles:
        - azure_vms

I get the following error:

    TASK [azure_vms : Create Network Security Group that allows SSH] *************************************************************************************************************************************************************************************************************
    task path: /home/ansible/azure_ansible/azure_vms/tasks/main.yml:3
    redirecting (type: modules) ansible.builtin.azure_rm_securitygroup to azure.azcollection.azure_rm_securitygroup
    fatal: [localhost]: FAILED! => {
        "msg": "The module azure_rm_securitygroup was redirected to azure.azcollection.azure_rm_securitygroup, which could not be loaded."
    }


https://stackoverflow.com/questions/69687631/ansible-azure-tries-to-connect-to-localhost-when-trying-to-create-vms

**Comment by Fred-sun** [comment]
@jinsu88 Ansible has migrated to AZCollection. Some of the new features will have to be used in future releases. Please refer to the link --https://github.com/ansible-collections/azure. Thank you very much!
