### ISSUE TITLE
Azure SQL auto failover group

### ISSUE THREAD

**Issue by mdicerbo** [ansible/ansible_collections_azure#665]
Hi Everyone,

I'm trying to configure an azuresql auto failover group using ansible but i've not find any useful documentation
to enable this option, is it supported?

Regards

Massimo

**Comment by Fred-sun** [comment]
@mdicerbo This feature is not supported at the moment, we will fix the current problem after we upgrade the SDK. Thank you very much!

**Comment by mdicerbo** [comment]
thank you @Fred-sun !
