### ISSUE TITLE
azure_rm_cosmosdbaccount module should support setting the MongoDB API server version and other capabilities

### ISSUE THREAD

**Issue by jpposteuca** [ansible/ansible_collections_azure#666]
##### SUMMARY
I am using the `azure_rm_cosmosdbaccount` module to provision an Azure CosmosDB instance with a MongoDB API.  Currently the module documentation and the code show no way to control the server version of the MongoDB API.  By default, version `3.6` is selected.  I would like to select the latest server version, which is `4.0`.  Additionally, I would like to be able to configure additional features, such as the `Serverless` capacity mode.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`azure_rm_cosmosdbaccount`

##### ADDITIONAL INFORMATION
The module parameters for `azure_rm_cosmosdbaccount` seem to mirror the Azure CosmosDB properties, so my idea would be to add parameters mirroring the `apiProperties` and `capabilities` properties.  Here are property examples from an Azure CosmosDB JSON response:

```json
"apiProperties": {
    "serverVersion": "4.0"
}
...
"capabilities": [
    {
        "name": "EnableMongo"
    },
    {
        "name": "EnableServerless"
    }
 ]
```

Based on this, here is an example of the module parameters that could be added:
```yaml
api_properties
  server_version: 4.0
...
capabilities:
  - name: EnableMongo
  - name: EnableServerless
```

**Comment by l3ender** [comment]
I have added ability to specify server version in https://github.com/ansible-collections/azure/pull/675. I did not take a look at `capabilities` feature at this point.
