### ISSUE TITLE
1.10.0 release not on Galaxy

### ISSUE THREAD

**Issue by l3ender** [ansible/ansible_collections_azure#668]
##### SUMMARY

I see the [1.10.0 release](https://github.com/ansible-collections/azure/blob/b8dce08bbd16619f41f533d0012abdcae7042546/CHANGELOG.md#v1100-2021-10-22) on Github but it is not available on [Ansible Galaxy](https://galaxy.ansible.com/azure/azcollection).

##### ISSUE TYPE
- Bug Report

**Comment by l3ender** [comment]
And a reminder to publish to Ansible documentation when doing the release as well! Thank you!

https://docs.ansible.com/ansible/latest/collections/azure/azcollection/index.html

**Comment by Fred-sun** [comment]
@l3ender The v1.10.0 version of release is still being tested and will be released as soon as it is completed. Thank you very much!

**Comment by l3ender** [comment]
I now see the 1.10.0 release on both galaxy and documentation site. Thank you!
