### ISSUE TITLE
Integrate Microsoft API Managements modules

### ISSUE THREAD

**Issue by Emmanuel35** [ansible/ansible_collections_azure#722]
##### SUMMARY
Microsoft as writen modules for API Management in labs. 
It is possible to integrate them ?

##### ISSUE TYPE
- Add API Management modules

##### COMPONENT NAME
components: apimanagement

##### ADDITIONAL INFORMATION
Modules are in projet [microsoft/AnsibleLabs/lab-08-apimanagement/modules](https://github.com/microsoft/AnsibleLabs/tree/master/lab-08-api-management/modules)

Exemples in [microsoft/AnsibleLabs/lab-08-apimanagement/](https://github.com/microsoft/AnsibleLabs/tree/master/lab-08-api-management/)

**Comment by Fred-sun** [comment]
Already added , https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_apimanagement.py
