### ISSUE TITLE
Feature Request: azure_rm_keyvault RBAC

### ISSUE THREAD

**Issue by adthorn** [ansible/ansible_collections_azure#723]
##### SUMMARY
Enable RBAC for Key vaults

##### ISSUE TYPE
enable_rbac_authorization: true/false since it's in terraform and ARM/Bicep

##### COMPONENT NAME
azure_rm_keyvault

##### ADDITIONAL INFORMATION
    - name: Create instance of Key Vault
      azure_rm_keyvault:
        resource_group: "{{azr_rg_name}}"
        vault_name: "{{azr_kv_name}}"
        enable_soft_delete: true
        enabled_for_deployment: true
        enabled_for_disk_encryption: true
        enable_rbac_authorization: true
        vault_tenant: "{{azr_aad_tenant_id}}"
        access_policies:       
          - tenant_id: "{{azr_aad_tenant_id}}"
            object_id: "{{azr_aad_object_id}}"
            keys:
              - get
              - list
        sku:
          name: "{{azr_kv_sku}}"
        subscription_id: "{{azr_subid}}"
        auth_source: auto
        tags:

**Comment by adthorn** [comment]
@Fred-sun - Any way we can get this option added to the module?

**Comment by Fred-sun** [comment]
> @Fred-sun - Any way we can get this option added to the module?

@adthorn I will check and complete the addition as soon as possible. Thank you very much!

**Comment by adthorn** [comment]
@Fred-sun  - Thank you

**Comment by adthorn** [comment]
Any update? RBAC has been around for 3 years now @Fred-sun

**Comment by Fred-sun** [comment]
@adthorn The old SDK currently does not support this parameter "enable-rbac-authorization ". We will consider adding it after we upgrade the SDK. Thank you very much!

**Comment by watsonb** [comment]
Any update on this?  I'm upgraded to azure.azcollection v1.15.0 and the keyvault module complains if `access_policies` is omitted.  But you shouldn't need to define any `access_policies` if RBAC is enabled (which is what we do by default).

**Comment by michie1** [comment]
While you are [checking the latest SDK ](https://github.com/ansible-collections/azure/issues/1026#issuecomment-2398913496), could you also take a look at the rbac setting, please? @Fred-sun

**Comment by Fred-sun** [comment]
@michie1 Thanks for your feedback! I will look at it!

**Comment by Fred-sun** [comment]
Added in #1737
