### ISSUE TITLE
azure_rm_privateendpointdnszonegroup - Private DNS Zone in different subscription

### ISSUE THREAD

**Issue by adthorn** [ansible/ansible_collections_azure#734]
@l3ender - Is there a way to call a remote private DNS zone and configure it there? We're in a landing zone configuration with our subscriptions, with centralized private dns zones for these private endpoints. I see private_dns_zone_id being called out in your python module. Allow the use of private_dns_zone_id so we can specify a different subscription for the DNS zone.

Something like this:
![image](https://user-images.githubusercontent.com/51236046/150852812-60294c86-4428-411e-941a-eaa348539f2e.png)

_Originally posted by @adthorn in https://github.com/ansible-collections/azure/issues/725#issuecomment-1020471641_

**Comment by Fred-sun** [comment]
@adthorn I added "private_dns_zone_id" to another pull request. Can you try it -- #735 ? Does it meet your needs? Thank you very much!

**Comment by adthorn** [comment]
Yep, it looks correct.

**Comment by adthorn** [comment]
Looks like there's an issue with this.

"msg": "Error creating or updating DNS zone group privatelink_vaultcore_azure_net for private endpoint pve-xx-xx-xx-xx-xxxx-004-vault-004: Azure Error: InvalidPrivateDnsZoneIds\nMessage: Private Dns Zone group /subscriptions/xxx/resourceGroups/rg-xxx/providers/Microsoft.Network/privateEndpoints/pve-xxx-xx-xx-x-xx-004-vault-004/privateDnsZoneGroups/privatelink_vaultcore_azure_net has invalid private dns zone ids ."
345
}
346
345



    - name: Create zone group for private endpoint
      azure_rm_privateendpointdnszonegroup:
        name: "default"
        tenant: "{{tenant}}"
        secret: "{{secret}}"
        client_id: "{{client_id}}"
        private_endpoint: "{{azr_pve_name}}"
        resource_group: "{{azr_rg_name}}"
        subscription_id: "{{azr_subid}}"
        private_dns_zone_configs:
          - name: "{{azr_pve_dns_zone | regex_replace('.', '_')}}"
            private_dns_zone_id: "/subscriptions/{{azr_subid_net}}/resourceGroups/{{azr_vnet_hub_name}}/providers/Microsoft.Network/privateDnsZones/{{azr_pve_dns_zone}}"
            #private_dns_zone: "{{azr_pve_dns_zone}}"      
      when: azr_create_kv == 'yes'

**Comment by Fred-sun** [comment]
fixes by #735
