### ISSUE TITLE
Feature Request: Virtual Wan Network Connection (vHub Network Connection)

### ISSUE THREAD

**Issue by adthorn** [ansible/ansible_collections_azure#737]
##### SUMMARY
Create module to allow Virtual WAN Network Connections to the Virtual WAN Hub. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_virtualwan_connection

##### ADDITIONAL INFORMATION

Here's how to do it in Powershell
Select-AzSubscription -SubscriptionId "{{azr_remote_subid}}"
$remote = Get-AzVirtualNetwork -Name "{{azr_remote_vnet_name}}" -ResourceGroupName "{{azr_remote_rg_name}}"
Select-AzSubscription -SubscriptionId "{{azr_subid}}"
New-AzVirtualHubVnetConnection -ResourceGroupName "{{azr_rg_name}}" -VirtualHubName "{{azr_vhub_name}}" -Name "con-{{azr_remote_vnet_name}}" -RemoteVirtualNetwork $remote

Ansible:
    - name: Create a Virtual Wan Network Connection to a Virtual Hub (Like vNET Peering but different)
      azure_rm_vwan_connection:
        subscription_id: "{{azr_subid}}"
        resource_group: "{{azr_rg_name}}"
        virtual_network_name: "{{azr_vnet_name}}"
        name: "{azr_vwan_con_name}}"
        virtual_wan_name: "{{azr_vwan_name"
        remote_network_id: "/subscriptions/{{azr_subid}}/resourceGroups/{{azr_rg_name}}/providers/Microsoft.Network/virtualNetworks/{{azr_remote_vnet_name}}"
        #Optional Items
        associated_route_table_id: 
        "/subscriptions/MySub/resourceGroups/MyRG/providers/Microsoft.Network/virtualHubs/MyHub/hubRouteTables/RouteTable1"
        propagated_route_tables_ids: 
        - 
        -  
     "/subscriptions/MySub/resourceGroups/MyRG/providers/Microsoft.Network/virtualHubs/MyHub/hubRouteTables/RouteTable1"
        - 
        -  
    "/subscriptions/MySub/resourceGroups/MyRG/providers/Microsoft.Network/virtualHubs/MyHub/hubRouteTables/RouteTable2"
               labels:
                 - "label1"
                 - "label2"
        route_name: "route1"
        next_hop: "70.0.0.2"
        address_prefixes: 
           - "10.80.0.0/16"
           - "10.90.0.0/16"

**Comment by Fred-sun** [comment]
@adthorn Thank you for your new requirements, we will add them one by one, and welcome more community or contribution. Thank you very much!

**Comment by adthorn** [comment]
Any update on this? Would rather see this as a module instead of using the CLI.

**Comment by Fred-sun** [comment]
added by #939
