### ISSUE TITLE
ansible-builder: ModuleNotFoundError: No module named 'azure.mgmt.monitor.version'

### ISSUE THREAD

**Issue by howardjones** [ansible/ansible_collections_azure#742]
##### SUMMARY
I am building a custom AWX Execution Environment using ansible-builder, with azure.azcollection as one of the collection dependencies. Build completes OK, but when I try to use this EE inside awx, I get this error:

```
  "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_azure_rm_storageaccount_payload_qsc3bowu/ansible_azure_rm_storageaccount_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 225, in <module>\n    from azure.mgmt.monitor.version import VERSION as monitor_client_version\nModuleNotFoundError: No module named 'azure.mgmt.monitor.version'\n",
```

I have seen #715 which talks about the order of installation between the collection and its dependencies, but (as far as I know) I don't have control of that with ansible-builder. This build will be happening inside a CI pipeline, so manual steps aren't really an option.

I have the azure cli installed inside the EE too, but that is the packaged version, installing into its own environment in /lib64/az

I have opened a shell inside the EE container, and confirmed that from /usr/bin/python, I can import azure.mgmt.monitor with no issues. I'm a little confused that line 225 of azure_rm_common.py doesn't reflect the error, too. The only line in azure_rm_common.py that mentions azure.mgmt.monitor is line 250:

```
    from azure.mgmt.monitor import MonitorManagementClient
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure/azcollection/plugins/module_utils/azure_rm_common.py

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.8rc1.post0] 
```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.11.0 
```

##### CONFIGURATION

```paste below
blank
```

##### OS / ENVIRONMENT

ansible-builder default environment (CentOS Stream 8?)

##### STEPS TO REPRODUCE

The first command that uses azure_rm_* in an existing, working playbook triggers this issue. In this case it was
azure_rm_storageaccount.

##### EXPECTED RESULTS

Playbook runs as usual.

##### ACTUAL RESULTS

```
  "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_azure_rm_storageaccount_payload_qsc3bowu/ansible_azure_rm_storageaccount_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 225, in <module>\n    from azure.mgmt.monitor.version import VERSION as monitor_client_version\nModuleNotFoundError: No module named 'azure.mgmt.monitor.version'\n",
```

**Comment by adthorn** [comment]
When trying to create a resource group, I too get
"{
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_jum2815e/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 235, in <module>\n    from azure.mgmt.monitor.version import VERSION as monitor_client_version\nModuleNotFoundError: No module named 'azure.mgmt.monitor.version'\n",
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on xxx's Python /opt/venv/azure/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter",
    "invocation": {
        "module_args": {
            "name": "xx-xxx-xxx-xxx-xxx-xxx",
            "subscription_id": "xxx",
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "location": "eastus",
            "tags": {
                "Description": "Resource Group: Container of Resources for xx- xx",
                "Subscription": "xxx,
                "AppCode": "xxx",
                "AppOwner": "xx",
                "Environment": "lab",
                "Location": "eastus",
                "Instance": "002",
                "ResourceType": "rg"
            },
            "auth_source": "auto",
            "cloud_environment": "AzureCloud",
            "api_profile": "latest",
            "append_tags": true,
            "state": "present",
            "force_delete_nonempty": false,
            "profile": null,
            "ad_user": null,
            "password": null,
            "cert_validation_mode": null,
            "adfs_authority_url": null,
            "log_mode": null,
            "log_path": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}"

I've tried it two ways now. Looked at the requirements.txt file and it matches the dev requirements for 1.11.0. I'm getting this when creating a Resource Group.

@l3ender or @Fred-sun - Any ideas why people are having this issue? I looked at the other one and my venv has the correct requirements.

**Comment by adthorn** [comment]
So I was able to go into my virtual Python environment. Rename azcollection, git clone the current repo, chmod 755 it and then run my jobs and they work properly. Basically Galaxy wasn't correctly updating the collection. So I had the latest Python modules for Azure and the ansible module was the other version.

**Comment by adthorn** [comment]
###Azure venv
cd /your/path/to/python/venv/lib/python3.6/site-packages/ansible_collections/azure/
sudo mv azcollection azcollection.old
sudo git clone https://github.com/ansible-collections/azure.git azcollection
sudo chmod -Rf 755 azcollection
source /your/path/to/python/venv/bin/activate
umask 0022
pip3 install --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --trusted-host=pypi.python.org -r ./azcollection/requirements-azure.txt
deactivate

**Comment by Fred-sun** [comment]
@adthorn Your problem is caused by the default Python editor. It is recommended that you uninstall it and follow it again. Thank you very much!

**Comment by Fred-sun** [comment]
@howardjones Normally this should not be dependent because this module is being used all the time. It should be your environment. Can you install and retry by following the link below? Thank you very much!
```e.g.
https://github.com/ansible-collections/azure
