### ISSUE TITLE
azure_rm_virtualmachine_info fails to get VM, gives the error APIVersion 2019-07-01 is not available

### ISSUE THREAD

**Issue by karishma-kohli** [ansible/ansible_collections_azure#748]
My ansible version is:

ansible [core 2.12.1]
  config file = None
  configured module search path = ['/Users/karishmakohli/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/5.2.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/karishmakohli/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.1 (main, Dec  6 2021, 22:18:20) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3

List of Azure modules installed with versions:

        "azure==4.0.0",
        "azure-applicationinsights==0.1.0",
        "azure-batch==4.1.3",
        "azure-common==1.1.27",
        "azure-core==1.21.1",
        "azure-cosmosdb-nspkg==2.0.2",
        "azure-cosmosdb-table==1.0.6",
        "azure-datalake-store==0.0.52",
        "azure-eventgrid==1.3.0",
        "azure-eventhub==5.7.0",
        "azure-graphrbac==0.40.0",
        "azure-identity==1.7.1",
        "azure-keyvault==1.1.0",
        "azure-loganalytics==0.1.1",
        "azure-mgmt==4.0.0",
        "azure-mgmt-advisor==1.0.1",
        "azure-mgmt-applicationinsights==0.1.1",
        "azure-mgmt-authorization==0.50.0",
        "azure-mgmt-automation==1.0.0",
        "azure-mgmt-batch==5.0.1",
        "azure-mgmt-batchai==2.0.0",
        "azure-mgmt-billing==0.2.0",
        "azure-mgmt-cdn==3.1.0",
        "azure-mgmt-cognitiveservices==3.0.0",
        "azure-mgmt-commerce==1.0.1",
        "azure-mgmt-compute==4.4.0",
        "azure-mgmt-consumption==2.0.0",
        "azure-mgmt-containerinstance==1.5.0",
        "azure-mgmt-containerregistry==2.8.0",
        "azure-mgmt-containerservice==4.4.0",
        "azure-mgmt-core==1.3.0",
        "azure-mgmt-cosmosdb==0.4.1",
        "azure-mgmt-datafactory==0.6.0",
        "azure-mgmt-datalake-analytics==0.6.0",
        "azure-mgmt-datalake-nspkg==3.0.1",
        "azure-mgmt-datalake-store==0.5.0",
        "azure-mgmt-datamigration==1.0.0",
        "azure-mgmt-devspaces==0.1.0",
        "azure-mgmt-devtestlabs==2.2.0",
        "azure-mgmt-dns==2.1.0",
        "azure-mgmt-eventgrid==1.0.0",
        "azure-mgmt-eventhub==2.6.0",
        "azure-mgmt-hanaonazure==0.1.1",
        "azure-mgmt-iotcentral==0.1.0",
        "azure-mgmt-iothub==0.5.0",
        "azure-mgmt-iothubprovisioningservices==0.2.0",
        "azure-mgmt-keyvault==1.1.0",
        "azure-mgmt-loganalytics==0.2.0",
        "azure-mgmt-logic==3.0.0",
        "azure-mgmt-machinelearningcompute==0.4.1",
        "azure-mgmt-managementgroups==0.1.0",
        "azure-mgmt-managementpartner==0.1.1",
        "azure-mgmt-maps==0.1.0",
        "azure-mgmt-marketplaceordering==0.1.0",
        "azure-mgmt-media==1.0.1",
        "azure-mgmt-monitor==0.5.2",
        "azure-mgmt-msi==0.2.0",
        "azure-mgmt-network==2.7.0",
        "azure-mgmt-notificationhubs==2.1.0",
        "azure-mgmt-nspkg==3.0.2",
        "azure-mgmt-policyinsights==0.1.0",
        "azure-mgmt-powerbiembedded==2.0.0",
        "azure-mgmt-privatedns==1.0.0",
        "azure-mgmt-rdbms==1.9.0",
        "azure-mgmt-recoveryservices==0.3.0",
        "azure-mgmt-recoveryservicesbackup==0.3.0",
        "azure-mgmt-redis==5.0.0",
        "azure-mgmt-relay==0.1.0",
        "azure-mgmt-reservations==0.2.1",
        "azure-mgmt-resource==2.2.0",
        "azure-mgmt-scheduler==2.0.0",
        "azure-mgmt-search==2.1.0",
        "azure-mgmt-servicebus==0.5.3",
        "azure-mgmt-servicefabric==0.2.0",
        "azure-mgmt-signalr==0.1.1",
        "azure-mgmt-sql==0.9.1",
        "azure-mgmt-storage==2.0.0",
        "azure-mgmt-subscription==0.2.0",
        "azure-mgmt-trafficmanager==0.50.0",
        "azure-mgmt-web==0.35.0",
        "azure-nspkg==3.0.2",
        "azure-schemaregistry==1.0.0b2",
        "azure-schemaregistry-avroserializer==1.0.0b2",
        "azure-servicebus==0.21.1",
        "azure-servicefabric==6.3.0.0",
        "azure-servicemanagement-legacy==0.20.7",
        "azure-storage==0.36.0",
        "azure-storage-blob==1.5.0",
        "azure-storage-common==1.4.2",
        "azure-storage-file==1.4.0",
        "azure-storage-queue==1.4.0",
        "azure==0.6.4"

**ERROR:**

TASK [Calling azure_rm_virtualmachine_info] *************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": **"Error getting virtual machine _vmname_ - APIVersion 2019-07-01 is not available"**}

Please help me with this error. The above job modifies the size of an existing VM. The size exists in the API version. I don't know what am I doing wrong!!

**Comment by adthorn** [comment]
Are you doing this in a virtual environment? Make sure you have the correct python versions for the version. If you installed the DEV version of the requirements.txt, then you will need the DEV versions of these modules. 

There's a requirements file installed from galaxy for 1.11.0: ansible collection location = /Users/karishmakohli/.ansible/collections:/usr/share/ansible/collections - Most likely there. If you want to use the DEV versions of the modules, rename that directory for azure in your collections, git clone the DEV repo to azcollection, chmod -Rf 755 the directory for the collection and it should work.

**Comment by Fred-sun** [comment]
@karishma-kohli From your "pip3 list" it shows that the dependency version you are using is too low, resulting in error, you are advised to update below. Thank you very much!
```e.g.
azure-cli-core==2.26.1
azure-common==1.1.11
azure-identity==1.7.0
azure-mgmt-apimanagement==0.2.0
azure-mgmt-authorization==0.51.1
azure-mgmt-batch==5.0.1
azure-mgmt-cdn==3.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.0.0
azure-mgmt-containerservice==9.1.0
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==2.1.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-monitor==3.0.0
azure-mgmt-managedservices==1.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-network==19.1.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-privatedns==0.1.0
azure-mgmt-redis==5.0.0
azure-mgmt-resource==10.2.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-search==3.0.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-sql==0.10.0
azure-mgmt-storage==11.1.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.41.0
azure-nspkg==2.0.0
azure-storage==0.35.1
msrest==0.6.21
msrestazure==0.6.4
azure-keyvault==1.0.0a1
azure-graphrbac==0.61.1
azure-mgmt-cosmosdb==0.5.2
azure-mgmt-hdinsight==0.1.0
azure-mgmt-devtestlabs==3.0.0
azure-mgmt-loganalytics==1.0.0
azure-mgmt-automation==0.1.1
azure-mgmt-iothub==0.7.0
azure-mgmt-recoveryservices==0.4.0
azure-mgmt-recoveryservicesbackup==0.6.0
azure-mgmt-notificationhubs==2.0.0
azure-mgmt-eventhub==2.0.0
