### ISSUE TITLE
Add MySQL flexible server

### ISSUE THREAD

**Issue by x4FF3** [ansible/ansible_collections_azure#760]
##### SUMMARY
Add flexible as an option for mysql server.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_mysql*

##### ADDITIONAL INFORMATION
As we are switching from standalone to flexible servers, it would be very useful to be able to deploy these servers via ansible.
@Fred-sun

**Comment by Fred-sun** [comment]
@x4FF3 Thank you for submitting this question, it is a very useful feature, we will review it as soon as possible. Thank you very much!

**Comment by feiyan-gh** [comment]
I also would like this feature

**Comment by Fred-sun** [comment]
Is doing！

**Comment by x4FF3** [comment]
Hi, any ETA on this?

**Comment by x4FF3** [comment]
@Fred-sun any update on this?

**Comment by feiyan-gh** [comment]
In the end I had to use direct call to azure cli to provision flexible servers. @x4FF3 you could try do the same.

**Comment by x4FF3** [comment]
Hi,

yes i also used the command module now...

**Comment by x4FF3** [comment]
@Fred-sun could you please add this feature? as of 16 jan 2023, only flexible servers can be created...

**Comment by Fred-sun** [comment]
@x4FF3 Ok， I will!

**Comment by Fred-sun** [comment]
@x4FF3 The SDK on which MySQL Server depends does not support the "flexible" parameter and cannot be added. Thanks!

**Comment by x4FF3** [comment]
@Fred-sun is the SDK also open source?

**Comment by Fred-sun** [comment]
@x4FF3 Open resource, relate link https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/rdbms. Thank you very much!

**Comment by x4FF3** [comment]
the mysql sdk does not support flexible server, but https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/rdbms/azure-mgmt-rdbms/azure/mgmt/rdbms/mysql_flexibleservers should be usable for an azure module?

**Comment by Fred-sun** [comment]
@x4FF3 Yes, it should be a new module support. Thanks!

**Comment by YanekR** [comment]
Hello, do we have any update on this. Would be good to have this feature as Single Servers are going to be shutdown soon.

**Comment by sicet7** [comment]
Hello, 
Any update on this? :sweat_smile:
Because as far as my google searching gets me, September 16, 2024 is the retirement date for the single server, we're getting awfully close :sweat_smile:

@x4FF3 You mentioned you mentioned something about using the "command module" do you have an example of how one would do that? Thanks :smile:

**Comment by Fred-sun** [comment]
Added by #1586
