### ISSUE TITLE
azure_rm_virtualmachine loads only one image (-> top=1), therefore the "version" option does not work

### ISSUE THREAD

**Issue by pgmgb** [ansible/ansible_collections_azure#766]
https://github.com/ansible-collections/azure/blob/63388fc08b659e05d7e40412ec2a395d0db36197/plugins/modules/azure_rm_virtualmachine.py#L2029

The implementation of `top=1` makes the option `version` obsolete because the executed request returns every time one result.

**Executed request at the moment:**
`https://management.azure.com/subscriptions/{subscription-id}/providers/Microsoft.Compute/locations/switzerlandnorth/publishers/SUSE/artifacttypes/vmimage/offers/sles-sap-15-sp2-byos/skus/gen2/versions?$top=1&$orderby=name%20desc&api-version=2019-07-01`

```json
[
  {
    "location": "SwitzerlandNorth",
    "name": "2022.01.28",
    "id": "/Subscriptions/{subscription-id}/Providers/Microsoft.Compute/Locations/SwitzerlandNorth/Publishers/suse/ArtifactTypes/VMImage/Offers/sles-sap-15-sp2-byos/Skus/gen2/Versions/2022.01.28"
  }
]
```

**Expected request**
`https://management.azure.com/subscriptions/{subscription-id}/providers/Microsoft.Compute/locations/switzerlandnorth/publishers/SUSE/artifacttypes/vmimage/offers/sles-sap-15-sp2-byos/skus/gen2/versions?&api-version=2019-07-01`

```json
[
  {
    "location": "SwitzerlandNorth",
    "name": "2021.06.05",
    "id": "/Subscriptions/{subscription-id}/Providers/Microsoft.Compute/Locations/SwitzerlandNorth/Publishers/suse/ArtifactTypes/VMImage/Offers/sles-sap-15-sp2-byos/Skus/gen2/Versions/2021.06.05"
  },
  {
    "location": "SwitzerlandNorth",
    "name": "2022.01.28",
    "id": "/Subscriptions/{subscription-id}/Providers/Microsoft.Compute/Locations/SwitzerlandNorth/Publishers/suse/ArtifactTypes/VMImage/Offers/sles-sap-15-sp2-byos/Skus/gen2/Versions/2022.01.28"
  }
]
```

**Comment by Fred-sun** [comment]
@pgmgb Thank you for your questions. We will check and promote the merger of relevant PR as soon as possible. Thank you very much!
