### ISSUE TITLE
Impossible to add authorized_ip_ranges if it's not already set in existing AKS cluster

### ISSUE THREAD

**Issue by nuclear0wl** [ansible/ansible_collections_azure#768]
##### SUMMARY

Attempt to set `authorized_ip_ranges` for cluster where ranges weren't set before fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module **azure_rm_aks** in **azure.azcollection** >= 1.11.0

##### ANSIBLE VERSION

```paste below
ansible 2.10.17
  python version = 3.8.12 (default, Oct 13 2021, 06:42:42) [Clang 13.0.0 (clang-1300.0.29.3)]
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 1.11.0 
```

##### STEPS TO REPRODUCE

1. Create AKS Cluster with Authorized IP Ranges disabled
2. In module define some value for `authorized_ip_ranges`
```yaml
api_server_access_profile:
  authorized_ip_ranges:
    - "0.0.0.0/0"
```
3. Try to run Ansible task

##### EXPECTED RESULTS

Authorized IP Ranges are successfully applied.

##### ACTUAL RESULTS
Module tries to fetch actual `authorized_ip_ranges`:
 https://github.com/ansible-collections/azure/blob/63388fc08b659e05d7e40412ec2a395d0db36197/plugins/modules/azure_rm_aks.py#L813
As there is no `authorized_ip_ranges` (there won't be any in ARM template if option wasn't set), it causes the error below.

```paste below
TypeError: object of type 'NoneType' has no len()
```

**Comment by Fred-sun** [comment]
@nuclear0wl Thank you for submitting this question, I will check whether "authorized_ip_ranges" can be set for the existing cluster, thank you!

**Comment by verhyppo** [comment]
Hi @Fred-sun it is possible during the whole lifetime of the AKS instance both via az cli and Portal.
You can actually create a cluster that does not have any during creation but get updated to set the authorised ip ranges or viceversa.
Please have a look [here](https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges#update-a-clusters-api-server-authorized-ip-ranges)
