### ISSUE TITLE
Add require-infrastructure-encryption azure_rm_storageaccount

### ISSUE THREAD

**Issue by sully68** [ansible/ansible_collections_azure#773]
##### SUMMARY
Current options do not allow you to encrypt your storage account. It would be a welcome addition to this module, as it is unusable for any org that requires higher standards of encryption 
##### ISSUE TYPE
- Feature Idea
https://docs.microsoft.com/en-us/azure/storage/common/infrastructure-encryption-enable?tabs=azure-cli
##### COMPONENT NAME
azure_rm_storageaccount

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by Fred-sun** [comment]
@sully68 This is a good suggestion and we will discuss and add this feature as soon as possible! Thank you very much!

**Comment by Fred-sun** [comment]
@sully68 Try to add this attribute, but the account is not supported, we will upgrade to the sdK2 version and try to add it again. Thank you very much!
```e.g.
msg": "Failed to create account: Azure Error: FeatureNotSupportedForAccount\nMessage: Infrastructure encryption is not supported for the account

**Comment by Fred-sun** [comment]
Added in #937
