### ISSUE TITLE
containerregistry_info ('packaging' module not found)

### ISSUE THREAD

**Issue by CGHoussem** [ansible/ansible_collections_azure#795]
##### SUMMARY

Once Irun a playbook that has this task '_azure.azcollection.azure_rm_containerregistry_info_',I get a **ModuleNotFoundError**, the module name is '_packaging_'.
I've verified the existence of this module using a python interpreter (python2 & python3) and it does exist!
I've tried to change the ansible_python_interpreter option to both python2 & python3 directories and I still got the same issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_containerregistry_info

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/home/houssem/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/houssem/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/houssem/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/houssem/.local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/houssem/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.12.0
```

##### CONFIGURATION

```paste below
no changes.
```

##### OS / ENVIRONMENT

OS: Linux LFR046916 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```yaml
- name: Get instance of Registry
  azure_rm_containerregistry_info:
    resource_group: RG_DEV_POC_PLATFORM_TEST
    name: arcDEV
```

##### ACTUAL RESULTS

https://gist.github.com/CGHoussem/a78df976ae2c9d9c70d836adaea9c0c0

**Comment by iwt-cmd** [comment]
Good morning, apologies for commenting on a closed issue but I'm having the same error (ModuleNotFoundError "packaging") and I did the same steps to verify the module was installed/working using the python REPL.  Was a resolution found?
