### ISSUE TITLE
Ansible support to create disk encryption set

### ISSUE THREAD

**Issue by shannawaz** [ansible/ansible_collections_azure#81]
##### SUMMARY

Ansible support  to create disk encryption set. This feature is required for another feature request.
https://github.com/ansible-collections/azure/issues/80

https://docs.microsoft.com/en-us/cli/azure/disk-encryption-set?view=azure-cli-latest#az-disk-encryption-set-create

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Most probably a new Ansible module
https://docs.microsoft.com/en-us/cli/azure/disk-encryption-set?view=azure-cli-latest#az-disk-encryption-set-create

##### ADDITIONAL INFORMATION

Is  anyone working on this feature currently? If yes what is the ETA?

```yaml

```

**Comment by Fred-sun** [comment]
@shannawaz Thank you for taking the time to report this problem, we will deal with it as soon as possible! Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang Can you help to add this new module? Thank you very much!

**Comment by techcon65** [comment]
Hi @Fred-sun @haiyuazhang Can you confirm if I can pick up this issue if its not already being worked upon? Thanks!

**Comment by ghost** [comment]
Hi @Fred-sun @haiyuazhang Can you confirm if I can pick up this issue if its not already being worked upon?
[Apologies for spamming - You might be getting second notification for same comment as previous comment by mistakenly got deleted while editing]

**Comment by Xiuxi-Sun** [comment]
@techcon65 Thank you for your attention, welcome to help solve this problem! Thank you very much!

**Comment by ghost** [comment]
> @techcon65 Thank you for your attention, welcome to help solve this problem! Thank you very much!

Thank you @Xiuxi-Sun  working on it!
