### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.core'

### ISSUE THREAD

**Issue by cloudengineers** [ansible/ansible_collections_azure#815]
Hi Team, 

I have followed this URL and installed the 2.9.0 ansible version 

https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm?tabs=azure-cli

My Python version: 
Python 3.9.12

Ansible version: 
ansible 2.9.0
  config file = /home/jenkins/ansible.cfg
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jenkins/.local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.12 (main, Mar 24 2022, 16:21:12) [GCC 7.5.0]

I am getting the below error any suggestion much appreciated?

TASK [vmcreation : Delete Azure Blob Storage.] ***
task path: /home/jenkins/workspace/azure/roles/vmcreation/tasks/main.yaml:3
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jenkins
<127.0.0.1> EXEC /bin/sh -c 'echo ~jenkins && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jenkins/.ansible/tmp `"&& mkdir "` echo /home/jenkins/.ansible/tmp/ansible-tmp-1649305444.6796155-21188-99786380181723 `" && echo ansible-tmp-1649305444.6796155-21188-99786380181723="` echo /home/jenkins/.ansible/tmp/ansible-tmp-1649305444.6796155-21188-99786380181723 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.azure_rm_storageblob to azure.azcollection.azure_rm_storageblob
Using module file /home/jenkins/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py
<127.0.0.1> PUT /home/jenkins/.ansible/tmp/ansible-local-21065qckyyaj6/tmp20mvfyfe TO /home/jenkins/.ansible/tmp/ansible-tmp-1649305444.6796155-21188-99786380181723/AnsiballZ_azure_rm_storageblob.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/jenkins/.ansible/tmp/ansible-tmp-1649305444.6796155-21188-99786380181723/ /home/jenkins/.ansible/tmp/ansible-tmp-1649305444.6796155-21188-99786380181723/AnsiballZ_azure_rm_storageblob.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/jenkins/.ansible/tmp/ansible-tmp-1649305444.6796155-21188-99786380181723/AnsiballZ_azure_rm_storageblob.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/jenkins/.ansible/tmp/ansible-tmp-1649305444.6796155-21188-99786380181723/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure_rm_storageblob_payload_0fpji53s/ansible_azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 235, in <module>
    from azure.mgmt.network import NetworkManagementClient
  File "/usr/local/lib/python3.9/dist-packages/azure/mgmt/network/__init__.py", line 9, in <module>
    from ._network_management_client import NetworkManagementClient
  File "/usr/local/lib/python3.9/dist-packages/azure/mgmt/network/_network_management_client.py", line 14, in <module>
    from azure.mgmt.core import ARMPipelineClient
  File "/usr/local/lib/python3.9/dist-packages/azure/mgmt/core/__init__.py", line 29, in <module>
    from ._pipeline_client import ARMPipelineClient
  File "/usr/local/lib/python3.9/dist-packages/azure/mgmt/core/_pipeline_client.py", line 30, in <module>
    from azure.core import PipelineClient
ModuleNotFoundError: No module named 'azure.core'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "auto",
            "batch_upload_dst": null,
            "batch_upload_src": null,
            "blob": null,
            "blob_type": "block",
            "cache_control": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "container": "apps",
            "content_disposition": null,
            "content_encoding": null,
            "content_language": null,
            "content_md5": null,
            "content_type": null,
            "dest": null,
            "force": false,
            "log_mode": null,
            "log_path": null,
            "password": null,
            "profile": null,
            "public_access": "container",
            "resource_group": "rg-test-01",
            "secret": null,
            "src": null,
            "state": "absent",
            "storage_account_name": "azstoragetest",
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on test's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by Fred-sun** [comment]
@cloudengineers It seems that the dependency you installed is incomplete（sudo pip3 install -r requirements-azure.txt -I）. Can you reinstall it in the following way? Thank you.
```e.g.
1. sudo apt update
2. pip3 install ansible[azure]
3. ansible-galaxy collection install azure.azcollection
4. sudo pip3 install -r requirements-azure.txt  ( all dependec package)

**Comment by Fred-sun** [comment]
kindly ping!

**Comment by cloudengineers** [comment]
Hi @Fred-sun 

it didn't work for me, still the same error.

Thank you

**Comment by Fred-sun** [comment]
@cloudengineers I have never been able to reproduce the problem you encountered, but according to your error log, it is your environment. The installed dependency is no longer in the Python3 environment. Can you do that? Uninstall all, reinstall, plus the latest version of Ansible. Another, Create an environment and try again. Ansible ver > 2.9 Thank you very much!

**Comment by Fred-sun** [comment]
@cloudengineers I have encountered the above problem in centos 7.7, so far I have not found the cause of the problem! But I can test it on centos 7.9. Can you try it on Centos 7.9? Thank you very much!
```e.g. 
 az vm create --resource-group QuickstartAnsible-rg --name QuickstartAnsible-vm85 --image OpenLogic:CentOS:8.0:latest --admin-username azureuser --admin-password **************

**Comment by xuzhang3** [comment]
@cloudengineers  This root issue is the python dependencies installed to two different location:
`/usr/local/lib/python3.6/site-packages` and `/home/azureuser/.local/lib/python3.6/site-packages` this is why ansible cannot find the dependency modules. Recommend run ansible in an virtual environment.
1. create new virtual environment: `python3 -m venv test`
2. Active the virtual env: `. ./test/bin/actionve`
3. Follow the steps in the doc install ansible, collection, dependencies etc.
