### ISSUE TITLE
MIBEGNAM

### ISSUE THREAD

**Issue by DragonearinLBro** [ansible/ansible_collections_azure#820]
https://github.com/ncosentino/DevLeader/blob/master/EventHandlerLeak/EventHandlerLeak.sln

**Comment by Fred-sun** [comment]
@DragonearinLBro Thank you for submitting the problem in this Repo. Can you help provide a detailed problem description? This helps to analyze and solve the problem. Thank you very much!

**Comment by Fred-sun** [comment]
kinldy ping!

**Comment by Fred-sun** [comment]
@DragonearinLBro Do not know the purpose of this Issue, close it temporarily, and open it again if necessary! Thanks!
