### ISSUE TITLE
`azure_rm_virtualmachine_info` throw error on missing `config` attribute

### ISSUE THREAD

**Issue by Lunik** [ansible/ansible_collections_azure#827]
##### SUMMARY

The module doesn't work anymore when updating the collection from `1.11` to `1.12`.
Seems related to the upgrade of the `azure-mgmt-compute` dependency. [SDK changelog](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/CHANGELOG.md#1700b1-2020-06-17) notify that : 

The config attribute no longer exists on a client, configuration should be passed as kwarg. Example: MyClient(credential, subscription_id, enable_logging=True). For a complete set of supported options, see the [parameters accept in init documentation of azure-core](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#available-policies)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- `azure_rm_virtualmachine_info`

##### ANSIBLE VERSION

```paste below
5.6.0
```

##### COLLECTION VERSION

```paste below
v1.12.0
```

##### STEPS TO REPRODUCE

```yaml
  - name: VM status
    azure.azcollection.azure_rm_virtualmachine_info:
      resource_group: "{{ YYYYYY }}"
      name: "{{ XXXXXX }}"
    register: VMState
```

##### EXPECTED RESULTS

The module should return data without error

##### ACTUAL RESULTS

Got an `AttributeError`

```paste below
Traceback (most recent call last):
  File \"<stdin>\", line 107, in <module>
  File \"<stdin>\", line 99, in _ansiballz_main
  File \"<stdin>\", line 47, in invoke_module
  File \"/usr/local/lib/python3.10/runpy.py\", line 209, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/local/lib/python3.10/runpy.py\", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_g3r3__bs/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 493, in <module>
  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_g3r3__bs/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 489, in main
  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_g3r3__bs/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 310, in __init__
  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_g3r3__bs/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 465, in __init__
  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_g3r3__bs/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 326, in exec_module
  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_g3r3__bs/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 339, in get_item
  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_g3r3__bs/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 379, in get_vm
  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_g3r3__bs/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1096, in compute_client
  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_g3r3__bs/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 936, in get_mgmt_svc_client
AttributeError: 'ComputeManagementClient' object has no attribute 'config'. Did you mean: '_config'?

```

**Comment by Fred-sun** [comment]
@Lunik I have tested in my local VM, get pass result. Could you help to retry it? Another, please check your 'azure-mgmt-compute' version! It has upgrade to "26.1.0"! Thank you very much!

**Comment by Lunik** [comment]
The version of `azure-mgmt-compute` dependency provided with the release `1.12.0` of this collection is `23.1.0` : https://github.com/ansible-collections/azure/blob/v1.12.0/requirements-azure.txt#L11

If you say that we should use the version `26.1.0` your requirement in version `1.12.0` is invalid then ?

**Comment by Fred-sun** [comment]
@Lunik Sorry, v1.12.0 is 23.1.0, our latest support is 26.1.0 and will be released in the next release. Thank you very much!

https://github.com/ansible-collections/azure/blob/7deb8ee3914601a48629b625ad18e2928cc9c3d6/requirements-azure.txt#L11

**Comment by Lunik** [comment]
When should we expect the next release of the collection ? Will it be included in the next release of ansible `5.7.0` ?

**Comment by Fred-sun** [comment]
It is released independently of ansible and is generally updated once a month. Thank you very much!

**Comment by Lunik** [comment]
`AZURE_CERT_VALIDATION_MODE` was set with `ignore` value. I think it may be releated ...

**Comment by Fred-sun** [comment]
@Lunik Did your upgrade resolve the current problem? If not, I will close the problem! Do you have any other questions? Welcome to put forward, we will try our best to solve. Thank you very much!

**Comment by Lunik** [comment]
Upgrading didn't solve the issue. However, as mentioned in my previous message, removing the environment variable `AZURE_CERT_VALIDATION_MODE` solve it.
