### ISSUE TITLE
azure_rm_manageddisk has missing parameters for Azure Snapshot disk creation

### ISSUE THREAD

**Issue by smfredolme06** [ansible/ansible_collections_azure#831]
##### SUMMARY

Azure Snapshot Restore - add missing parameters to create the disk from snapshot
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Add missing parameters to create the disk from snapshot
1. source_type
Selection: 
snapshot
storage blob
disk
disk restore point
2. source_snapshot
source_snapshot - when snapshot is selected
source_storage_blob - when storage blob is selected
source_disk - when disk is selected
source_disk_restore_point - when disk restore point is selected
##### ADDITIONAL INFORMATION

https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_manageddisk_module.html - this module only has source_uri as parameter. We are not able to create the disk from snapshot using this module. 

```yaml

```

Fields from Azure
![image](https://user-images.githubusercontent.com/104122106/164382282-0c8675d8-dbbc-4904-9b44-cd523a9c77bc.png)
![image](https://user-images.githubusercontent.com/104122106/164382660-bee89194-eda0-43a9-b8ef-63baef87399a.png)

Documentation for azure_rm_manageddisk module
![image](https://user-images.githubusercontent.com/104122106/164381887-35652321-ec81-42d4-b358-c83fb6f45afc.png)

Code
![image](https://user-images.githubusercontent.com/104122106/164382094-d441633d-de50-45e1-b3a8-4fabdec6134e.png)

**Comment by Fred-sun** [comment]
@smfredolme06 I'm glad you asked for it. We'll check and add it, and contributors are welcome to add it. Thank you very much!

**Comment by Fred-sun** [comment]
@smfredolme06 When we manage resources, we create managed disks of the corresponding type using the provided source_uri, so both parameters are implemented using source_uri. Thank you very much!
```e.g.
 - name: Create managed disk from disk snapshot
   azure_rm_manageddisk:
     name: "my{{ rpfx }}"
     resource_group: "{{ resource_group }}"
     create_option: copy
     source_uri: "/subscriptions/*****/resourceGroups/testRG/providers/Microsoft.Compute/snapshots/fred-snapshot"
     os_type: linux
     storage_account_type: Premium_LRS

 - name: Create managed disk from disk
   azure_rm_manageddisk:
     name: "my{{ rpfx }}"
     resource_group: "{{ resource_group }}"
     create_option: copy
     source_uri: "/subscriptions/xxxxx/resourceGroups/testRG/providers/Microsoft.Compute/disks/testdisk"
     os_type: linux
     storage_account_type: Premium_LRS

**Comment by smfredolme06** [comment]
Thank you! It works now

Regards,

Sheila

From: Fred-sun ***@***.***>
Sent: Thursday, May 12, 2022 10:41 AM
To: ansible-collections/azure ***@***.***>
Cc: Sheila Marie Redolme ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL EMAIL: Re: [ansible-collections/azure] azure_rm_manageddisk has missing parameters for Azure Snapshot disk creation (Issue #831)


@smfredolme06<https://clicktime.symantec.com/3SA3BdA4CNB9acvVoTFm9xf6xU?u=https%3A%2F%2Fgithub.com%2Fsmfredolme06> When we manage resources, we create managed disks of the corresponding type using the provided source_uri, so both parameters are implemented using source_uri. Thank you very much!

 - name: Create managed disk from disk snapshot

   azure_rm_manageddisk:

     name: "my{{ rpfx }}"

     resource_group: "{{ resource_group }}"

     create_option: copy

     source_uri: "/subscriptions/*****/resourceGroups/testRG/providers/Microsoft.Compute/snapshots/fred-snapshot"

     os_type: linux

     storage_account_type: Premium_LRS



 - name: Create managed disk from disk

   azure_rm_manageddisk:

     name: "my{{ rpfx }}"

     resource_group: "{{ resource_group }}"

     create_option: copy

     source_uri: "/subscriptions/xxxxx/resourceGroups/testRG/providers/Microsoft.Compute/disks/testdisk"

     os_type: linux

     storage_account_type: Premium_LRS

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3PL1NK1dpKcizyKwmuju6a26xU?u=https%3A%2F%2Fgithub.com%2Fansible-collections%2Fazure%2Fissues%2F831%23issuecomment-1124471484>, or unsubscribe<https://clicktime.symantec.com/33kFLNtcuw9GQjpzPcRsMQi6xU?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAY2MN6Q3JSQQDUX24DGT2FTVJRVSNANCNFSM5T6CP3CA>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

________________________________
Warning: All e-mail sent to this address will be received by the corporate e-mail system, and is subject to archival and review by someone other than the recipient. This e-mail may contain proprietary information and is intended only for the use of the intended recipient(s). If the reader of this message is not the intended recipient(s), you are notified that you have received this message in error and that any review, dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify the sender immediately.
________________________________
