### ISSUE TITLE
Sanity tests failing in azure.azcollection

### ISSUE THREAD

**Issue by dmsimard** [ansible/ansible_collections_azure#838]
##### SUMMARY
We are running sanity tests across every collection included in the Ansible community package (as part of [this issue](https://github.com/ansible-community/community-topics/issues/96)) and found that ``ansible-test sanity --docker`` against azure.azcollection 1.12.0 fails with ansible-core 2.13.0rc1 in ansible 6.0.0a2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
n/a

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.0rc1]
```

##### COLLECTION VERSION

```paste below
1.12.0
```

##### STEPS TO REPRODUCE

```yaml
ansible-test sanity --docker
```

##### EXPECTED RESULTS

Tests are either passing or ignored.

##### ACTUAL RESULTS

List of failures is too long to be included in the issue, see this gist: https://gist.githubusercontent.com/dmsimard/3b9c14aec15f8410b66621291643ca87/raw/1a4f0d1d7f8dceb775a96c90de05a8a6de52c0c9/output.txt

**Comment by Fred-sun** [comment]
@dmsimard Thank you for reporting this problem. According to your error log, the file's newline character is changed to  Windows format. Are you open in Windows system etc? Suggest you change the format, or delete reinstall. Thank you very much!
