### ISSUE TITLE
azure_rm_dnszone_info does not support Private DNS zones

### ISSUE THREAD

**Issue by bit4man** [ansible/ansible_collections_azure#86]
##### SUMMARY
The azure_rm_dnszone_info ansible module does not return data from Private DNS Zones.  There are no parameters when you query to specify if you want public or private zones.  This results in issues if subscription contains private DNS - at best you get empty results back. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_dnszone_info

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.9.6
  config file = /home/ocp/azure/ansible/ansible.cfg
  configured module search path = ['/home/ocp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)
```

##### CONFIGURATION

```
COMMAND_WARNINGS(/home/ocp/azure/ansible/ansible.cfg) = False
DEFAULT_FILTER_PLUGIN_PATH(/home/ocp/azure/ansible/ansible.cfg) = ['/home/ocp/azure/ansible/filter_plugins']
DEFAULT_HOST_LIST(/home/ocp/azure/ansible/ansible.cfg) = ['/home/ocp/azure/ansible/inventory']
DEPRECATION_WARNINGS(/home/ocp/azure/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/ocp/azure/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/ocp/azure/ansible/ansible.cfg) = auto
```

##### OS / ENVIRONMENT
Fedora 31

##### STEPS TO REPRODUCE

```
ansible -i inventory localhost -m azure_rm_dnszone_info -a "resource_group=rg"
```
This fails to return any private DNS zones. 

##### EXPECTED RESULTS

As the documentation states, I expect private DNS zones to returned with zoneType set to Private. 

##### ACTUAL RESULTS

Empty result set - or when trying to use the zone to add record sets you get errors.

**Comment by Fred-sun** [comment]
@bit4man Thank you for taking the time to report this problem. We will deal with it as soon as possible. Thank you very much!

**Comment by Fred-sun** [comment]
@bit4man Dns zones and private Dns are two different modules, in which Dns zones(type: public and private). You can refer to the following two links, thank you!
private Dns: https://docs.microsoft.com/en-us/rest/api/dns/privatedns/privatezones
Dns zones: https://docs.microsoft.com/en-us/rest/api/dns/zones

**Comment by Fred-sun** [comment]
@bit4man This issue are duplicates with #87 , the new module will be used for Private DNS zones. It is recommended to close this. Thank you!

**Comment by Fred-sun** [comment]
@bit4man PR #122 has provided the module azure_rm_privatednszone, if you have no other problems, I will close this issue within a week. Thank you!
