### ISSUE TITLE
azure_rm_manageddisk managed_by does not support list

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible_collections_azure#861]
_From @feiyan-gh on May 25, 2022 03:00_

### Summary

I am trying to create a managed disk and attach to multiple VMs by share (see https://docs.microsoft.com/en-us/azure/virtual-machines/disks-shared). However I cannot find a way to achieve this with ansible playbook.

### Issue Type

Feature Idea

### Component Name

azure

### Additional Information

Please let me know if there's already way of achieving attach one managed disk to multiple VMs. When I try to specify an array in the azure_rm_manageddisk.managed_by entry ansible does not recognize it.

I also tried link to vm with data_disks entry however I'm getting this error: "Error creating or updating virtual machine qait1-web - (OperationNotAllowed) Addition of a blob based disk to VM with managed disks is not supported."

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

_Copied from original issue: ansible/ansible#77902_

**Comment by Fred-sun** [comment]
fixes by #867
