### ISSUE TITLE
Credentials did not include a subscription_id value

### ISSUE THREAD

**Issue by fjmartinperez** [ansible/ansible_collections_azure#869]
Hi all,

I am trying to use this module: [azure_rm_adgroup_info module](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_adgroup_info_module.html#ansible-collections-azure-azcollection-azure-rm-adgroup-info-module) – Get Azure Active Directory group info

But looks like subscription_id is mandatory to connect to AAD. My AAD Admin told to me that AAD doesn´t have any subscription_id.

I´m using  a service principal credential witch contains:

        client_id: "{{ lookup('env','AZURE_CLIENT_ID') }}"
        secret: "{{ lookup('env','AZURE_SECRET') }}"
        tenant: "{{ lookup('env','AZURE_TENANT') }}"

Is there any way to login to AAD without subsctiption_id or is a issue on the collection?

I am using AAP21 with azcollection 1.12.0

Thank you.

Greetings.

**Comment by Fred-sun** [comment]
@fjmartinperez If service principal credential is used, subscription_id must be provided. If subscription_id is not provided, ad_user and ad_password can be used to access it! Thank you very much!

**Comment by Fred-sun** [comment]
@fjmartinperez If service principal credential is used, subscription_id must be provided. If subscription_id is not provided, ad_user and ad_password can be used to access it! Thank you very much!

**Comment by fjmartinperez** [comment]
@Fred-sun thank you for the feedback!

Unfortunately, my AAD admin doesn't want to provide ad_user and ad_password due to security reasons.

I´ve been testing and found a workaround. By setting 'null' client_id field looks like you can bypass the issue, but now I get another error:

`"msg": "failed to get ad group info Insufficient privileges to complete the operation.",
  "exception": "  File \"/tmp/ansible_azure_rm_adgroup_info_payload_c9kja8jg/ansible_azure_rm_adgroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup_info.py\", line 238, in exec_module\n  File \"/usr/local/lib/python3.8/site-packages/msrest/paging.py\", line 143, in __next__\n    self.advance_page()\n  File \"/usr/local/lib/python3.8/site-packages/msrest/paging.py\", line 129, in advance_page\n    self._response = self._get_next(self.next_link)\n  File \"/usr/local/lib/python3.8/site-packages/azure/graphrbac/operations/groups_operations.py\", line 339, in internal_paging\n    raise models.GraphErrorException(self._deserialize, response)\n",`

Given user has Group.Read.All permissions, so I wonder if the problem comes from user permissions or not.

Greetings.

**Comment by Fred-sun** [comment]
@fjmartinperez Yes, user authorization is required,  and add permissions! thank you!

**Comment by fjmartinperez** [comment]
Hi all,

Still with this issue.

I´m testing with a personal instance of Azure AD from the scratch, in which i can manage user and application permissions.  

An Azure AD instance does not have any subscription id, so if you only want to manage Azure AD groups, you will not have this  value to configure in AAP credential. My workaround to this was setting it to null but it seems this setting causes the authentication issue.

Even giving all permissions to the application , I still get same error. 

I wonder if this collection uses Cloud Shell or Graph API.

Regards.

**Comment by fjmartinperez** [comment]
Update:

After testing it in an Azure educational instance in which I have full management:

subscription_id is mandatory because you need storage for using cloud shell.

So first of all you must create a storage resurce for cloud shell, which will have a subscription. This subscription is the subscription_id you need.

But after that I have same error "Insuficient Permissions". I wonder now I have same issue of this thread:

https://github.com/ansible-collections/azure/issues/573

Azure AD Groups Management should be a basic sollution for azcollection, because on a near future most companies will begin migrating their AD On Premise environments to Azure AD, and all will need this module working.

**Comment by fjmartinperez** [comment]
Update:

Tested with azure.azcollection 1.13.0 (recently updated) and still with same issue "Insuficient Permissions"

**Comment by fjmartinperez** [comment]
Reviewing docs:

Microsoft is migrating Graph API endpoints:

https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-faq

So from now, API requests must call to another url:

https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-request-differences

Checking random code of azcollection:

https://github.com/ansible-collections/azure/blob/dev/plugins/module_utils/azure_rm_common.py

You can find old URL endpoint in the code:

def _get_azure_cli_credentials(self, subscription_id=None, resource=None):
        if self.is_ad_resource:
            resource = 'https://graph.windows.net/'
        subscription_id = subscription_id or self._get_env('subscription_id')

After that, for me it's clear what's going on, the collection must be migrated to Microsoft Graph instead of Azure AD Graph.

**Comment by Fred-sun** [comment]
@fjmartinperez AD related modules should work in ”az login;  az account set -s subscription_id " mode and specify auth_source: CLI in PlayBook. Thank you very much!

**Comment by fjmartinperez** [comment]
It worked in my educational instance simply giving permissions to the old Azure AD Graph and without changing anything else. This is de issue. So, authentication method is ok for me.

But in my production environment I am not the Azure administrator, witch will not want to give permissions to an API wich is retired.

I insist, the collection should work with Microsoft Graph API the same that works with the old Azure AD Graph. This and no other is the key.

Thank you.

**Comment by fjmartinperez** [comment]
Hi,

Any updates about Graph API migration date?? We need to interact with the new API and we are stopped since may.

Thank you very much.

**Comment by Fred-sun** [comment]
@fjmartinperez Sorry to reply later, It has migrated, related PR https://github.com/ansible-collections/azure/pull/1325
