### ISSUE TITLE
Couldn't find api version for Microsoft.DataFactory/factories?api-version=2018-06-01

### ISSUE THREAD

**Issue by t8mas062184** [ansible/ansible_collections_azure#887]
- name: Check if Data Factory ({{ az_datafactory_name }}) already exists
    azure.azcollection.azure_rm_resource_info:
      auth_source: auto
      client_id: "{{ az_client_id }}"
      secret: "{{ az_secret }}"
      tenant: "{{ az_tenant_id }}"
      subscription_id: "{{ az_subscription_id }}"
      url: "https://management.azure.com/subscriptions/{{ az_subscription_id }}/resourceGroups/{{ az_resource_group_name }}/providers/Microsoft.DataFactory/factories?api-version=2018-06-01"
    register: az_datafactory

Output:
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Couldn't find api version for Microsoft.DataFactory/factories?api-version=2018-06-01"}

**Comment by Fred-sun** [comment]
@t8mas062184 The self.url for this location should be resource ID, as follows, please try again. Thank you very much!
```e.g.
name: Check if Data Factory ({{ az_datafactory_name }}) already exists
azure.azcollection.azure_rm_resource_info:
auth_source: auto
client_id: "{{ az_client_id }}"
secret: "{{ az_secret }}"
tenant: "{{ az_tenant_id }}"
subscription_id: "{{ az_subscription_id }}"
url: "/subscriptions/{{ az_subscription_id }}/resourceGroups/{{ az_resource_group_name }}/providers/Microsoft.DataFactory/factories/{{ factories_name }}"

register: az_datafactory
