### ISSUE TITLE
Route Table of Subnet gets cleared when using a AKS

### ISSUE THREAD

**Issue by SpikePy** [ansible/ansible_collections_azure#890]
##### SUMMARY
Recreating a Azure Subnet flushes the route_table with the entries genereated by an AKS

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_subnet.py

##### ANSIBLE VERSION
ansible 2.10.7
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.4 (default, Apr 10 2021, 15:39:19) [GCC 8.3.0]

##### COLLECTION VERSION
1.12.0

##### STEPS TO REPRODUCE
1. create a Subnet
2. create a AKS that uses the Subnet
3. run step 1 again and it flushed the `route_table`

##### EXPECTED RESULTS
As ansible tasks should be idempotent and the AKS should still work when running the steps above again and again

##### ACTUAL RESULTS
AKS does not work anymore when running a second time (internal networking does not function) and we have to restart to whole cluster to make it work again.

The problem seems to be that the AKS-Module also automatically creates a routing_table. but when we rerun the "create subnet" step it doesn't know that there is already routing_table assigned (and therefore flushes it. this problem seems to be caused by this change in the subnet module:

###### 1.10.0

```python
if self.route_table is not None and self.route_table != results['route_table'].get('id'):
    changed = True
    results['route_table']['id'] = self.route_table
    self.log("CHANGED: subnet {0} route_table to {1}".format(self.name, route_table.get('name')))
```

###### 1.11.0

```python
if self.route_table is not None:
    if self.route_table != results['route_table'].get('id'):
        changed = True
        results['route_table']['id'] = self.route_table
        self.log("CHANGED: subnet {0} route_table to {1}".format(self.name, route_table.get('name')))
else:
    if results['route_table'].get('id') is not None:
        changed = True
        results['route_table']['id'] = None
        self.log("CHANGED: subnet {0} will dissociate to route_table {1}".format(self.name, route_table.get('name')))
```

I also created a diff between the outputs of version 1.4.0 (left) and 1.12.0 (right)
![image](https://user-images.githubusercontent.com/16565183/174597288-5f49812b-9efd-4fd9-96d5-54c315088110.png)

as you can see the old version keeps the route_table and the new one resets it. after this the name resolution in the AKS does not work anymore and we have to restart it.

**Comment by Fred-sun** [comment]
@SpikePy We are very sorry for the trouble caused to you. At present, our azure_rm_subnet disconnects the subnet and routing table. If there is a good way in the future, we will update again. Therefore, when managing subnets, you can add the ID of the routing table to subnet parameters to avoid association. You can obtain the current subnet routing table configuration information in the following way: Thank you very much!
```e.g.
- name: Get subnet info
  azure_rm_subnet_info:
    name: ****
    virtual_network_name: ****
    resource_group: ****
  register: output
- name: Managed the subnet again
  azure_rm_subnet:
    name: ****
    virtual_network_name: ********
    resource_group: ****
    address_prefix_cidr: ****
    route_table: "{{ route_table.id }}"

**Comment by Fred-sun** [comment]
@SpikePy Do you have any other questions? Thank you very much!

**Comment by SpikePy** [comment]
@Fred-sun no, thanks for your workaround but in our case this is very complicated implement. So my solution is to split the playbook and try to avoid this module whenever possible. Would be great if you could fix the aks behavior in the future.

**Comment by Fred-sun** [comment]
@SpikePy Thank you very much! Once there is a better way, we will update and inform you in time!
