### ISSUE TITLE
Adding exclude_host_filters in dynamic inventory yaml

### ISSUE THREAD

**Issue by garamirseokim** [ansible/ansible_collections_azure#914]
##### SUMMARY

Need to create filter on Azure's dynamic inventories yaml to list the hosts only which is having tag key "Provisionedby=Test" , "Provisionedby=AAA" and "Provisionedby=BBB"

However, the below codes are not working, Is it fine if we declare two times for "'"ManagedOS" not in tags.keys()'" and "'"Provisionedby" not in tags.keys()'"

~~~~~
default_host_filters: []
exclude_host_filters:
- '"ManagedOS" not in tags.keys()'
- tags["ManagedOS"] != "True"
- location not in ['australiaeast', 'australiasoutheast']
- '"Provisionedby" not in tags.keys()'
- tags["Provisionedby"] != "Test" and tags["Provisionedby"] != "AAA" and tags["Provisionedby"] != "BBB"
~~~~~

##### ANSIBLE VERSION

```paste below
2.9
```
##### COLLECTION VERSION

```paste below
latest
```

**Comment by jackmahesh** [comment]
I also tried below filter on Azure's dynamic inventories yaml, seems it should work, any one please confirm whether its a correct method to filter.

 ```
exclude_host_filters:
 - '"ManagedOS" and "Provisionedby" not in tags.keys()'
 - tags["ManagedOS"] != "True" and tags["Provisionedby"] != "Name1" and tags["Provisionedby"] != "Name2" and tags["Provisionedby"] != "Name3"
```

**Comment by Fred-sun** [comment]
@jackmahesh Yes, do you have any problems now?

**Comment by Fred-sun** [comment]
@garamirseokim 'exclude_host_filters' is already used to filter hosts. You can refer to the link -https://github.com/ansible-collections/azure/blob/dev/plugins/inventory/azure_rm.py,   the Ansible version you use is the ansible-azcollection version. Thank you very much!

**Comment by jackmahesh** [comment]
Hi All,

It works in below filter option. thanks all your support.

exclude_host_filters:
- '"ManagedOS" and "Provisionedby" not in tags.keys()'
- tags["ManagedOS"] != "True" and tags["Provisionedby"] != "Name1" and tags["Provisionedby"] != "Name2" and tags["Provisionedby"] != "Name3"
