### ISSUE TITLE
Public IPs from Azure Scale Sets not shown on ansible-inventory

### ISSUE THREAD

**Issue by stevenspinoza** [ansible/ansible_collections_azure#923]
##### SUMMARY

Hey guys, I try to get public Ips from my azure scale sets using ansible-inventory, but the output is empty, even though on azure they are shown, thanks. See images

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible/plugins/inventory/azure_rm.py
##### ANSIBLE VERSION

```paste below
2.13.1
```

##### COLLECTION VERSION

```paste below
1.13.0
```

##### OS / ENVIRONMENT

Ubuntu 22.04 LTS

##### EXPECTED RESULTS

Public IPs shown when run ansible-inventory

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/5944011/179882811-6e6f34cc-95f5-43ad-ac3c-670fd3be99d1.png)
![image](https://user-images.githubusercontent.com/5944011/179882990-f83e4b04-7968-4112-a2c5-951b1d3cb58a.png)
![image](https://user-images.githubusercontent.com/5944011/179883631-5d5e198c-f6b9-414d-bd3b-72548e6551ac.png)
![image](https://user-images.githubusercontent.com/5944011/179883086-b3d891e4-46bd-4196-b2c0-204a0a2e21d1.png)

**Comment by stevenspinoza** [comment]
Ok, forgot adding a public NIC. Case closed :+1:

**Comment by Fred-sun** [comment]
@stevenspinoza You are welcome to submit your problems? Before you get the VMSS instance information, can you verify that your instance VM is also configured with a public IP address?

**Comment by kingsleyadam** [comment]
Can confirm this is also an issue for me. Public IP address is assigned to the VM, I can access the VM via the public IP address.

It seems as though azure doesn't assign a public ip address id `pip_id = ipc['properties'].get('publicIPAddress', {}).get('id')` and because of this no public ip information is populated.

**Comment by emoshaya** [comment]
I have the same issue here. The VMSS VM has a public ip address but is not showing in the inventory
