### ISSUE TITLE
azure_rm_storageaccount does not include valid account types of Standard_GZRS and Standard_RAGZRS

### ISSUE THREAD

**Issue by bbaileyod** [ansible/ansible_collections_azure#926]
##### SUMMARY
azure_rm_storageaccount.py should now include support for types Standard_GZRS and Standard_RAGZRS

##### ISSUE TYPE
Need the ability to request the additional storage types at creation.  Converting to them requires engaging Azure to change to them and unfortunately the CLI support changing from them.  So if you deploy as ZRS and ask Azure to convert to GZRS, a job could convert it back to ZRS.

##### COMPONENT NAME
azure_rm_storageaccount.py

##### ADDITIONAL INFORMATION
Documentation conforms with the error received with trying to request the storage type.   Supported types do not include all of what Azure is offering.
    account_type:
        description:
            - Type of storage account. Required when creating a storage account.
            - C(Standard_ZRS) and C(Premium_LRS) accounts cannot be changed to other account types.
            - Other account types cannot be changed to C(Standard_ZRS) or C(Premium_LRS).
        choices:
            - Premium_LRS
            - Standard_GRS
            - Standard_LRS
            - Standard_RAGRS
            - Standard_ZRS
            - Premium_ZRS

**Microsoft documentation showing supported types**			
https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create
 [--sku {Premium_LRS, Premium_ZRS, Standard_GRS, **Standard_GZRS**, Standard_LRS, Standard_RAGRS, **Standard_RAGZRS**, Standard_ZRS}]			

    "msg": "value of account_type must be one of: Premium_LRS, Standard_GRS, Standard_LRS, Standard_RAGRS, Standard_ZRS, Premium_ZRS, got: Standard_GZRS",
    "invocation": {
        "module_args": {
            "account_type": "Standard_GZRS",

**Comment by Fred-sun** [comment]
Added by #931
