### ISSUE TITLE
Azure inventory plugin docs say install azure > 2.0.0, but now pip does not allow install azure meta package

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible_collections_azure#93]
##### SUMMARY

ansible core docs for inventory plugin here: https://docs.ansible.com/ansible/latest/plugins/inventory/azure_rm.html say install `azure` package:

```
The below requirements are needed on the local master node that executes this inventory.

I'm not 100% sure where docs for the plugin going forward will live, e.g. the plugin distributed by the collection, but I want to make sure the docs get fixed for the future as well as back in the core docs (hence https://github.com/ansible/ansible/issues/68940)

python >= 2.7
azure >= 2.0.0
Parameters
```

current docs in collection repo: https://github.com/ansible-collections/azure#requirements don't list any requirements

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

azure inventory plugin

##### ANSIBLE VERSION

any ansible version since azure inventory plugin was introduced

##### OS / ENVIRONMENT

n/a

##### ADDITIONAL INFORMATION

Traceback from pip when you try and install `azure`:

```
        RuntimeError:
  
        Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
        Please install the service specific packages prefixed by `azure` needed for your application.
  
        The complete list of available packages can be found at:
        https://aka.ms/azsdk/python/all
  
        Here's a non-exhaustive list of common packages:
  
        -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
        -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
        -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
        -  azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
        -  azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts
  
        A more comprehensive discussion of the rationale for this decision can be found in the following issue:
        https://github.com/Azure/azure-sdk-for-python/issues/10646
  ```

**Comment by Fred-sun** [comment]
@kdelee Error log prompt: "Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore", because the latest version of v5.0.0 cannot be installed directly by "pip install azure", you can install by specifying the version, for example: "sudo pip install azure==4.0.0". Thanks!

**Comment by Fred-sun** [comment]
kindly ping!

**Comment by Fred-sun** [comment]
@kdelee I'm so glad for your contribution to ansible-colleciton. This error has nothing to do with ansible-collecitons repo, the installation also prompts that it is no longer used, it is recommended to close it. If there is no reply, I will close it in a week. Thank you very much!

**Comment by Fred-sun** [comment]
Close this issue, if you have other questions, please submit a new issue!
