### ISSUE TITLE
Application Gateway ssl_certificates - Add support to reference a key vault secret ID

### ISSUE THREAD

**Issue by pwakano** [ansible/ansible_collections_azure#972]
##### SUMMARY

The **key-vault-secret-id** is a parameter supported both in the az cli (https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/ssl-cert?view=azure-cli-latest#az-network-application-gateway-ssl-cert-create-optional-parameters) and terraform (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#key_vault_secret_id), so it is expected to have Ansible supporting this parameter too.

##### ISSUE TYPE
- Feature Idea
- Match Ansible functionality with other tools

##### COMPONENT NAME

azure_rm_appgateway

##### ADDITIONAL INFORMATION

Having this parameter would make the playbook a lot simpler, since currently, the only way to handle a certificate saved in Azure Key Vault and used in an Application Gateway is to save the certificate as a _secret_ in Key Vault, so then the playbook can read the contents of the secret to upload it as the _ssl_certificate.data_ field.
This is all too cumbersome, because, first, there is no ansible module to support the Azure Key Vault Certificates (only for keys and secrets, that's why the certificate has to be saved as _secret_ and not _certificate_) but most importantly, the application gateway already support the key vault reference so it is just a matter of adding it to the ansible module.

**Comment by Fred-sun** [comment]
fixes in #990

**Comment by Fred-sun** [comment]
#990 has merged!

**Comment by michael-andretta** [comment]
@Fred-sun sorry to comment on a closed issue, but, how is the Vault Secret URL accessed? In Azure CLI you use the managed identity with 'Key Vault Secrets User' RBAC over the vault or specific cert for that application gateway. What/how are permissions associated to the vault for this parameter to work properly?

**Comment by pwakano** [comment]
Just giving my feedback in here. When I opened this ticket I was after the support for the key vault ID in the SSL certificates of the app gw, the equivalent of this: https://learn.microsoft.com/en-us/cli/azure/network/application-gateway/ssl-cert?view=azure-cli-latest#az-network-application-gateway-ssl-cert-create-optional-parameters.
However what was implemented in ansible (https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_appgateway_module.html#parameter-trusted_root_certificates/key_vault_secret_id), was the support for the key vault ID in the trusted root certificate, which is the equivalent of this: https://learn.microsoft.com/en-us/cli/azure/network/application-gateway/root-cert?view=azure-cli-latest#az-network-application-gateway-root-cert-create-optional-parameters
Those 2 things are not the same and from some test I've done, the ssl_certificate still doesn't support a key vault ID parameter...

**Comment by michael-andretta** [comment]
@pwakano Thank you! This clears up the ask and usage of the new parameter. I was looking for the same thing you were, were we can use the module in conjunction with a Manage Identify to pull a cert from the Vault to be used on the Listener.
