### ISSUE TITLE
Ansible modules required for Azure Managed SQL Instance

### ISSUE THREAD

**Issue by pingtouskar** [ansible/ansible_collections_azure#997]
##### SUMMARY
Currently there is no ansible modules to deploy and manage the SQL managed instances on Azure. As a result its difficult to automate the operational aspects of Azure Managed SQL instances.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- Azure Managed SQL instance
  
##### ADDITIONAL INFORMATION
- Currently there is no ansible modules available for azure sql managed instances for deployment/configuration purpose.
- Azure managed sql instances is a great way to take the enterprise sql workload to azure cloud but there is no support from ansible side to make the operation espects better on azure for managed sql instances.

**Comment by pingtouskar** [comment]
Hi @xuzhang3,
Let me know if anything will be ready. I should be able to test and update you based on the functionality.

**Comment by Fred-sun** [comment]
Added in #1039

**Comment by pingtouskar** [comment]
Thank you @Fred-sun . I will test it on Monday and get back to you with my findings.

**Comment by pingtouskar** [comment]
@Fred-sun 
Just want to understand that will this module support connecting to an existing **sql managed instance** db and **administrate** it ? Because in the actual code, I can't see any information related to the same.

Currently I am using [sqlcmd ](https://learn.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver16)command to administrator the dbs in managed sql instance.

**Comment by Fred-sun** [comment]
@pingtouskar Yes, it creates a new sql managed instance,

**Comment by pingtouskar** [comment]
> @pingtouskar Yes, it creates a new sql managed instance,

   Thanks for the reply but I am not talking about the sql managed instance. I am talking about the DB inside the managed instance.

Will it create DB inside the managed instance or we need to use sqlcmd for the same ?

**Comment by Fred-sun** [comment]
Yes, It's need to create DB. Thanks!

**Comment by pingtouskar** [comment]
Thanks for the confirmation. I am good for now. Closing this request.
